slogo_team04: viewcontroller.GUIReferenceLibrary Class Reference
viewcontroller.GUIReferenceLibrary Class Reference
Static Public Member Functions
static void setGUIReference (String language)
static String getStringTranslation (String GUIlabel)
static void setHelpReference ()
static void setPathReference ()
static String getPath (String pathKey)
static String getURL (String URLID)
Static Private Attributes
static Map< String, String > myGUIMap
static ResourceBundle myCommandReference
static ResourceBundle myPathReference
static ResourceBundle myHelpReference
static Set< String > myKeySet
Detailed Description
Reference library for all strings in the GUI. We were instructed in class that we would be able to make this mapping static.
Author
Abhishek B
Definition at line 16 of file GUIReferenceLibrary.java.
Member Function Documentation
static String viewcontroller.GUIReferenceLibrary.getPath (String pathKey) static
Definition at line 72 of file GUIReferenceLibrary.java.
Referenced by viewcontroller.commands.CommandWindowViewController.addStyleSheets().
static String viewcontroller.GUIReferenceLibrary.getStringTranslation (String GUIlabel) static
Reads the GUI map to get the string translation for any text that appears in GUI.
Parameters
GUIlabel
Returns
the value of the GUILabel key in the GUI Reference Map
Definition at line 49 of file GUIReferenceLibrary.java.
Referenced by viewcontroller.View.addWorkspace(), viewcontroller.commands.UserDefinedMethodsViewController.applyTranslations(), viewcontroller.commands.UserDefinedVariablesViewController.applyTranslations(), viewcontroller.commands.CommandHistoryViewController.applyTranslations(), viewcontroller.turtlegrid.TurtleStatusViewController.applyTranslations(), viewcontroller.commands.CommandStatusViewController.applyTranslations(), viewcontroller.commands.CommandPromptViewController.applyTranslations(), application.Form.createSubmitButton(), viewcontroller.turtlegrid.GridButtonBar.GridButtonBar(), viewcontroller.SLogoMenuBar.initializeEditMenu(), viewcontroller.SLogoMenuBar.initializeFileMenu(), viewcontroller.SLogoMenuBar.initializeGridMenu(), application.PenForm.initializePenStyles(), application.PenForm.PenForm(), application.PenFormResult.PenFormResult(), and viewcontroller.View.View().
static String viewcontroller.GUIReferenceLibrary.getURL (String URLID) static
Gets the URL from the Help Reference Resource Bundle
Parameters
URLID
Returns
URL String
Definition at line 82 of file GUIReferenceLibrary.java.
Referenced by viewcontroller.HelpDialogBox.setUpGUIStrings().
static void viewcontroller.GUIReferenceLibrary.setGUIReference (String language) static
Sets the Reference Language for GUI Text Elements of the SLogo Project
Parameters
language to set to.
Definition at line 30 of file GUIReferenceLibrary.java.
References viewcontroller.GUIReferenceLibrary.setPathReference().
Referenced by viewcontroller.View.View().
static void viewcontroller.GUIReferenceLibrary.setHelpReference () static
Sets the Reference for GUI Help Elements of the SLogo Project
Definition at line 56 of file GUIReferenceLibrary.java.
Referenced by viewcontroller.HelpDialogBox.setUpGUIStrings().
static void viewcontroller.GUIReferenceLibrary.setPathReference () static
Definition at line 64 of file GUIReferenceLibrary.java.
Referenced by viewcontroller.GUIReferenceLibrary.setGUIReference().
Member Data Documentation
ResourceBundle viewcontroller.GUIReferenceLibrary.myCommandReference static private
Definition at line 19 of file GUIReferenceLibrary.java.
Map<String, String> viewcontroller.GUIReferenceLibrary.myGUIMap static private
Definition at line 18 of file GUIReferenceLibrary.java.
ResourceBundle viewcontroller.GUIReferenceLibrary.myHelpReference static private
Definition at line 21 of file GUIReferenceLibrary.java.
Set<String> viewcontroller.GUIReferenceLibrary.myKeySet static private
Definition at line 22 of file GUIReferenceLibrary.java.
ResourceBundle viewcontroller.GUIReferenceLibrary.myPathReference static private
Definition at line 20 of file GUIReferenceLibrary.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/viewcontroller/GUIReferenceLibrary.java