slogo_team04: model.ModelUpdater Class Reference
model.ModelUpdater Class Reference
Public Member Functions
Map< Turtle, List< TransitionState > > updateModel (Collection< Turtle > turtles, List< TransitionState > states)
Private Member Functions
Map< Turtle, List< TransitionState > > createTurtleTransitionMapping (Collection< Turtle > turtles, List< TransitionState > states)
Collection< Turtle > findSelectedTurtles (Collection< Turtle > turtles)
Detailed Description
Definition at line 14 of file ModelUpdater.java.
Member Function Documentation
Map<Turtle, List<TransitionState> > model.ModelUpdater.createTurtleTransitionMapping (Collection< Turtle > turtles, List< TransitionState > states) private
Definition at line 22 of file ModelUpdater.java.
References model.ModelUpdater.findSelectedTurtles().
Referenced by model.ModelUpdater.updateModel().
Collection<Turtle> model.ModelUpdater.findSelectedTurtles (Collection< Turtle > turtles) private
Definition at line 45 of file ModelUpdater.java.
Referenced by model.ModelUpdater.createTurtleTransitionMapping().
Map<Turtle, List<TransitionState> > model.ModelUpdater.updateModel (Collection< Turtle > turtles, List< TransitionState > states)
Definition at line 16 of file ModelUpdater.java.
References model.ModelUpdater.createTurtleTransitionMapping().
Referenced by model.MainModel.updateModel().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/model/ModelUpdater.java