slogo_team04: viewcontroller.SLogoMenuBar Class Reference
viewcontroller.SLogoMenuBar Class Reference
Public Member Functions
SLogoMenuBar (View parentView)
Private Member Functions
MenuItem createMenuItem (String name, EventHandler< ActionEvent > handler)
void initializeEditMenu ()
void initializeFileMenu ()
void initializeGridMenu ()
Private Attributes
View myParentView
MenuItem myRedoMenuItem
MenuItem myUndoMenuItem
MenuItem myNewWorkspaceMenuItem
MenuItem myLoadWorkspaceMenuItem
MenuItem mySaveWorkspaceMenuItem
MenuItem myHelpMenuItem
MenuItem myLoadFileMenuItem
MenuItem myGridLinesMenuItem
MenuItem myAddTurtleMenuItem
MenuItem myTurtleImageMenuItem
MenuItem myPenSettingsMenuItem
Static Private Attributes
static final String GRID_KEY = "Grid"
static final String ADD_TURTLE_KEY = "Add"
static final String GRID_LINES_KEY = "Toggle"
static final String TURTLE_IMAGE_KEY = "TurtleImage"
static final String PEN_SETTINGS_KEY = "PenSettings"
static final String FILE_KEY = "File"
static final String HELP_KEY = "Help"
static final String NEW_WORKSPACE_KEY = "New"
static final String LOAD_FILE_KEY ="LoadFile"
static final String LOAD_WORKSPACE_KEY = "LoadWorkspace"
static final String SAVE_WORKSPACE_KEY = "SaveWorkspace"
static final String EDIT_KEY = "Edit"
static final String REDO_KEY = "Redo"
static final String UNDO_KEY = "Undo"
Detailed Description
Menu Bar for the SLogo interface
Author
Jonathan Tseng
Definition at line 15 of file SLogoMenuBar.java.
Constructor & Destructor Documentation
viewcontroller.SLogoMenuBar.SLogoMenuBar (View parentView)
Definition at line 54 of file SLogoMenuBar.java.
References viewcontroller.SLogoMenuBar.initializeEditMenu(), viewcontroller.SLogoMenuBar.initializeFileMenu(), and viewcontroller.SLogoMenuBar.initializeGridMenu().
Member Function Documentation
MenuItem viewcontroller.SLogoMenuBar.createMenuItem (String name, EventHandler< ActionEvent > handler) private
Definition at line 63 of file SLogoMenuBar.java.
Referenced by viewcontroller.SLogoMenuBar.initializeEditMenu(), viewcontroller.SLogoMenuBar.initializeFileMenu(), and viewcontroller.SLogoMenuBar.initializeGridMenu().
void viewcontroller.SLogoMenuBar.initializeEditMenu () private
Definition at line 70 of file SLogoMenuBar.java.
References viewcontroller.SLogoMenuBar.createMenuItem(), viewcontroller.GUIReferenceLibrary.getStringTranslation(), viewcontroller.View.redoClicked(), and viewcontroller.View.undoClicked().
Referenced by viewcontroller.SLogoMenuBar.SLogoMenuBar().
void viewcontroller.SLogoMenuBar.initializeFileMenu () private
Definition at line 80 of file SLogoMenuBar.java.
References viewcontroller.View.addNewWorkspace(), viewcontroller.SLogoMenuBar.createMenuItem(), viewcontroller.GUIReferenceLibrary.getStringTranslation(), viewcontroller.View.loadFile(), viewcontroller.View.loadWorkspace(), viewcontroller.View.saveWorkspace(), and viewcontroller.View.showHelp().
Referenced by viewcontroller.SLogoMenuBar.SLogoMenuBar().
void viewcontroller.SLogoMenuBar.initializeGridMenu () private
Definition at line 101 of file SLogoMenuBar.java.
References viewcontroller.View.addTurtleClicked(), viewcontroller.View.changeTurtleImages(), viewcontroller.SLogoMenuBar.createMenuItem(), viewcontroller.View.editPenSettings(), viewcontroller.GUIReferenceLibrary.getStringTranslation(), and viewcontroller.View.toggleGridLines().
Referenced by viewcontroller.SLogoMenuBar.SLogoMenuBar().
Member Data Documentation
final String viewcontroller.SLogoMenuBar.ADD_TURTLE_KEY = "Add" static private
Definition at line 18 of file SLogoMenuBar.java.
final String viewcontroller.SLogoMenuBar.EDIT_KEY = "Edit" static private
Definition at line 30 of file SLogoMenuBar.java.
final String viewcontroller.SLogoMenuBar.FILE_KEY = "File" static private
Definition at line 23 of file SLogoMenuBar.java.
final String viewcontroller.SLogoMenuBar.GRID_KEY = "Grid" static private
Definition at line 17 of file SLogoMenuBar.java.
final String viewcontroller.SLogoMenuBar.GRID_LINES_KEY = "Toggle" static private
Definition at line 19 of file SLogoMenuBar.java.
final String viewcontroller.SLogoMenuBar.HELP_KEY = "Help" static private
Definition at line 24 of file SLogoMenuBar.java.
final String viewcontroller.SLogoMenuBar.LOAD_FILE_KEY ="LoadFile" static private
Definition at line 26 of file SLogoMenuBar.java.
final String viewcontroller.SLogoMenuBar.LOAD_WORKSPACE_KEY = "LoadWorkspace" static private
Definition at line 27 of file SLogoMenuBar.java.
MenuItem viewcontroller.SLogoMenuBar.myAddTurtleMenuItem private
Definition at line 50 of file SLogoMenuBar.java.
MenuItem viewcontroller.SLogoMenuBar.myGridLinesMenuItem private
Definition at line 49 of file SLogoMenuBar.java.
MenuItem viewcontroller.SLogoMenuBar.myHelpMenuItem private
Definition at line 45 of file SLogoMenuBar.java.
MenuItem viewcontroller.SLogoMenuBar.myLoadFileMenuItem private
Definition at line 46 of file SLogoMenuBar.java.
MenuItem viewcontroller.SLogoMenuBar.myLoadWorkspaceMenuItem private
Definition at line 43 of file SLogoMenuBar.java.
MenuItem viewcontroller.SLogoMenuBar.myNewWorkspaceMenuItem private
Definition at line 42 of file SLogoMenuBar.java.
View viewcontroller.SLogoMenuBar.myParentView private
Definition at line 35 of file SLogoMenuBar.java.
MenuItem viewcontroller.SLogoMenuBar.myPenSettingsMenuItem private
Definition at line 52 of file SLogoMenuBar.java.
MenuItem viewcontroller.SLogoMenuBar.myRedoMenuItem private
Definition at line 38 of file SLogoMenuBar.java.
MenuItem viewcontroller.SLogoMenuBar.mySaveWorkspaceMenuItem private
Definition at line 44 of file SLogoMenuBar.java.
MenuItem viewcontroller.SLogoMenuBar.myTurtleImageMenuItem private
Definition at line 51 of file SLogoMenuBar.java.
MenuItem viewcontroller.SLogoMenuBar.myUndoMenuItem private
Definition at line 39 of file SLogoMenuBar.java.
final String viewcontroller.SLogoMenuBar.NEW_WORKSPACE_KEY = "New" static private
Definition at line 25 of file SLogoMenuBar.java.
final String viewcontroller.SLogoMenuBar.PEN_SETTINGS_KEY = "PenSettings" static private
Definition at line 21 of file SLogoMenuBar.java.
final String viewcontroller.SLogoMenuBar.REDO_KEY = "Redo" static private
Definition at line 31 of file SLogoMenuBar.java.
final String viewcontroller.SLogoMenuBar.SAVE_WORKSPACE_KEY = "SaveWorkspace" static private
Definition at line 28 of file SLogoMenuBar.java.
final String viewcontroller.SLogoMenuBar.TURTLE_IMAGE_KEY = "TurtleImage" static private
Definition at line 20 of file SLogoMenuBar.java.
final String viewcontroller.SLogoMenuBar.UNDO_KEY = "Undo" static private
Definition at line 32 of file SLogoMenuBar.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/viewcontroller/SLogoMenuBar.java