slogo_team04: viewcontroller.commands.UserDefinedVariablesViewController Class Reference
viewcontroller.commands.UserDefinedVariablesViewController Class Reference
Public Member Functions
UserDefinedVariablesViewController (int width, int height, CommandWindowContainerViewController parent)
void applyTranslations ()
Node getNode ()
void update (MainModel model)
Public Member Functions inherited from viewcontroller.commands.CommandListWindowViewController
CommandListWindowViewController (int width, int height)
Public Member Functions inherited from viewcontroller.commands.CommandWindowViewController
CommandWindowViewController (int width, int height)
Private Member Functions
void updateVariableList ()
void addVariableToList (String variable, double value)
void variableClicked (HBox variableHBox, Label variableLabel, Label valueLabel)
void keyPressed (KeyEvent event, TextField editableValueLabel, HBox variableHBox, Label variableLabel, Label valueLabel)
Private Attributes
CommandWindowContainerViewController myParent
Map< String, Double > myVariableMap
final String UserVariables = "UserVariables"
String myUserTranslation
Static Private Attributes
static final String MAKE_KEY = "MakeVariable"
Additional Inherited Members
Protected Member Functions inherited from viewcontroller.commands.CommandListWindowViewController
void updateScroller ()
Protected Member Functions inherited from viewcontroller.commands.CommandWindowViewController
void setTitle (String titleText)
Protected Attributes inherited from viewcontroller.commands.CommandListWindowViewController
ScrollPane myScrollPane
VBox myListVerticalBox
Protected Attributes inherited from viewcontroller.commands.CommandWindowViewController
BorderPane myPane
VBox myCommandWindowVerticalBox
Label myTitleLabel
Dimension SIZE = new Dimension()
Detailed Description
ViewController contained User-Defined Variable string names and values
Author
Abhishek B
Definition at line 21 of file UserDefinedVariablesViewController.java.
Constructor & Destructor Documentation
viewcontroller.commands.UserDefinedVariablesViewController.UserDefinedVariablesViewController (int width, int height, CommandWindowContainerViewController parent)
Definition at line 28 of file UserDefinedVariablesViewController.java.
References viewcontroller.commands.UserDefinedVariablesViewController.applyTranslations(), and viewcontroller.commands.CommandWindowViewController.setTitle().
Member Function Documentation
void viewcontroller.commands.UserDefinedVariablesViewController.addVariableToList (String variable, double value) private
Definition at line 59 of file UserDefinedVariablesViewController.java.
References viewcontroller.commands.CommandListWindowViewController.myListVerticalBox, viewcontroller.commands.CommandWindowViewController.SIZE, and viewcontroller.commands.UserDefinedVariablesViewController.variableClicked().
Referenced by viewcontroller.commands.UserDefinedVariablesViewController.updateVariableList().
void viewcontroller.commands.UserDefinedVariablesViewController.applyTranslations ()
translate the string using the GUI Reference Library
Implements viewcontroller.ViewController.
Definition at line 36 of file UserDefinedVariablesViewController.java.
References viewcontroller.GUIReferenceLibrary.getStringTranslation().
Referenced by viewcontroller.commands.UserDefinedVariablesViewController.update(), and viewcontroller.commands.UserDefinedVariablesViewController.UserDefinedVariablesViewController().
Node viewcontroller.commands.UserDefinedVariablesViewController.getNode ()
returns the Node representing the view for a view controller
Returns
Implements viewcontroller.ViewController.
Definition at line 41 of file UserDefinedVariablesViewController.java.
References viewcontroller.commands.CommandWindowViewController.myPane.
Referenced by viewcontroller.commands.CommandWindowContainerViewController.placeUserDefinedBoxes().
void viewcontroller.commands.UserDefinedVariablesViewController.keyPressed (KeyEvent event, TextField editableValueLabel, HBox variableHBox, Label variableLabel, Label valueLabel) private
Definition at line 78 of file UserDefinedVariablesViewController.java.
References viewcontroller.commands.CommandWindowContainerViewController.passSLogoCommand().
Referenced by viewcontroller.commands.UserDefinedVariablesViewController.variableClicked().
void viewcontroller.commands.UserDefinedVariablesViewController.update (MainModel model)
Extract the appropriate data from the model to update the view
Parameters
model - MainModel
Implements viewcontroller.MainModelObserver.
Definition at line 45 of file UserDefinedVariablesViewController.java.
References viewcontroller.commands.UserDefinedVariablesViewController.applyTranslations(), model.UserDefinedVariablesModel.getAllVariables(), model.MainModel.getUserDefinedVariables(), and viewcontroller.commands.UserDefinedVariablesViewController.updateVariableList().
void viewcontroller.commands.UserDefinedVariablesViewController.updateVariableList () private
Definition at line 52 of file UserDefinedVariablesViewController.java.
References viewcontroller.commands.UserDefinedVariablesViewController.addVariableToList(), viewcontroller.commands.CommandListWindowViewController.myListVerticalBox, and viewcontroller.commands.CommandListWindowViewController.updateScroller().
Referenced by viewcontroller.commands.UserDefinedVariablesViewController.update().
void viewcontroller.commands.UserDefinedVariablesViewController.variableClicked (HBox variableHBox, Label variableLabel, Label valueLabel) private
Definition at line 69 of file UserDefinedVariablesViewController.java.
References viewcontroller.commands.UserDefinedVariablesViewController.keyPressed().
Referenced by viewcontroller.commands.UserDefinedVariablesViewController.addVariableToList().
Member Data Documentation
final String viewcontroller.commands.UserDefinedVariablesViewController.MAKE_KEY = "MakeVariable" static private
Definition at line 23 of file UserDefinedVariablesViewController.java.
CommandWindowContainerViewController viewcontroller.commands.UserDefinedVariablesViewController.myParent private
Definition at line 24 of file UserDefinedVariablesViewController.java.
String viewcontroller.commands.UserDefinedVariablesViewController.myUserTranslation private
Definition at line 27 of file UserDefinedVariablesViewController.java.
Map<String, Double> viewcontroller.commands.UserDefinedVariablesViewController.myVariableMap private
Definition at line 25 of file UserDefinedVariablesViewController.java.
final String viewcontroller.commands.UserDefinedVariablesViewController.UserVariables = "UserVariables" private
Definition at line 26 of file UserDefinedVariablesViewController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/viewcontroller/commands/UserDefinedVariablesViewController.java