slogo_team04: viewcontroller.turtlegrid.TurtleStatusViewController Class Reference
viewcontroller.turtlegrid.TurtleStatusViewController Class Reference
Public Member Functions
TurtleStatusViewController (int width, int height)
Node getNode ()
void applyTranslations ()
void update (MainModel model)
Public Member Functions inherited from viewcontroller.commands.CommandWindowViewController
CommandWindowViewController (int width, int height)
Private Member Functions
void placeVariableTable ()
HBox populateHBox (String turtleID, String xPosition, String yPosition)
Private Attributes
final String Status = "Status"
final String TurtleID = "TurtleID"
final String XPosition = "XPosition"
final String YPosition = "YPosition"
String myStatusTranslation
String myTurtleID
String myXPosition
String myYPosition
VBox myListVerticalBox
HBox myColumnTitles
HBox myTurtleData
Additional Inherited Members
Protected Member Functions inherited from viewcontroller.commands.CommandWindowViewController
void setTitle (String titleText)
Protected Attributes inherited from viewcontroller.commands.CommandWindowViewController
BorderPane myPane
VBox myCommandWindowVerticalBox
Label myTitleLabel
Dimension SIZE = new Dimension()
Detailed Description
view controller for status of turtle that can be toggled i.e., view that shows turtle position
Author
Jonathan Tseng, Abhishek Balakrishnan
Definition at line 21 of file TurtleStatusViewController.java.
Constructor & Destructor Documentation
viewcontroller.turtlegrid.TurtleStatusViewController.TurtleStatusViewController (int width, int height)
Definition at line 36 of file TurtleStatusViewController.java.
References viewcontroller.turtlegrid.TurtleStatusViewController.applyTranslations(), viewcontroller.commands.CommandWindowViewController.myCommandWindowVerticalBox, viewcontroller.commands.CommandWindowViewController.myTitleLabel, and viewcontroller.turtlegrid.TurtleStatusViewController.placeVariableTable().
Member Function Documentation
void viewcontroller.turtlegrid.TurtleStatusViewController.applyTranslations ()
translate the string using the GUI Reference Library
Implements viewcontroller.ViewController.
Definition at line 67 of file TurtleStatusViewController.java.
References viewcontroller.GUIReferenceLibrary.getStringTranslation().
Referenced by viewcontroller.turtlegrid.TurtleStatusViewController.TurtleStatusViewController().
Node viewcontroller.turtlegrid.TurtleStatusViewController.getNode ()
returns the Node representing the view for a view controller
Returns
Implements viewcontroller.ViewController.
Definition at line 62 of file TurtleStatusViewController.java.
References viewcontroller.commands.CommandWindowViewController.myPane.
Referenced by viewcontroller.turtlegrid.TurtleWindowViewController.placeStatusView().
void viewcontroller.turtlegrid.TurtleStatusViewController.placeVariableTable () private
Definition at line 45 of file TurtleStatusViewController.java.
References viewcontroller.turtlegrid.TurtleStatusViewController.populateHBox().
Referenced by viewcontroller.turtlegrid.TurtleStatusViewController.TurtleStatusViewController().
HBox viewcontroller.turtlegrid.TurtleStatusViewController.populateHBox (String turtleID, String xPosition, String yPosition) private
Definition at line 52 of file TurtleStatusViewController.java.
References viewcontroller.commands.CommandWindowViewController.SIZE.
Referenced by viewcontroller.turtlegrid.TurtleStatusViewController.placeVariableTable(), and viewcontroller.turtlegrid.TurtleStatusViewController.update().
void viewcontroller.turtlegrid.TurtleStatusViewController.update (MainModel model)
Extract the appropriate data from the model to update the view
Parameters
model - MainModel
Implements viewcontroller.MainModelObserver.
Definition at line 75 of file TurtleStatusViewController.java.
References model.MainModel.getActiveTurtle(), turtle.Turtle.getId(), turtle.Turtle.getX(), turtle.Turtle.getY(), and viewcontroller.turtlegrid.TurtleStatusViewController.populateHBox().
Member Data Documentation
HBox viewcontroller.turtlegrid.TurtleStatusViewController.myColumnTitles private
Definition at line 33 of file TurtleStatusViewController.java.
VBox viewcontroller.turtlegrid.TurtleStatusViewController.myListVerticalBox private
Definition at line 32 of file TurtleStatusViewController.java.
String viewcontroller.turtlegrid.TurtleStatusViewController.myStatusTranslation private
Definition at line 28 of file TurtleStatusViewController.java.
HBox viewcontroller.turtlegrid.TurtleStatusViewController.myTurtleData private
Definition at line 34 of file TurtleStatusViewController.java.
String viewcontroller.turtlegrid.TurtleStatusViewController.myTurtleID private
Definition at line 29 of file TurtleStatusViewController.java.
String viewcontroller.turtlegrid.TurtleStatusViewController.myXPosition private
Definition at line 30 of file TurtleStatusViewController.java.
String viewcontroller.turtlegrid.TurtleStatusViewController.myYPosition private
Definition at line 31 of file TurtleStatusViewController.java.
final String viewcontroller.turtlegrid.TurtleStatusViewController.Status = "Status" private
Definition at line 24 of file TurtleStatusViewController.java.
final String viewcontroller.turtlegrid.TurtleStatusViewController.TurtleID = "TurtleID" private
Definition at line 25 of file TurtleStatusViewController.java.
final String viewcontroller.turtlegrid.TurtleStatusViewController.XPosition = "XPosition" private
Definition at line 26 of file TurtleStatusViewController.java.
final String viewcontroller.turtlegrid.TurtleStatusViewController.YPosition = "YPosition" private
Definition at line 27 of file TurtleStatusViewController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/viewcontroller/turtlegrid/TurtleStatusViewController.java