slogo_team04: turtle.TurtleImage Class Reference
turtle.TurtleImage Class Reference abstract
Public Member Functions
TurtleImage ()
boolean isSelected ()
void toggleSelection ()
void setSelection (boolean isSelected)
abstract double getRadius ()
void updateVisible (boolean visible)
Static Public Member Functions
static void setSize (Dimension size)
Protected Member Functions
abstract void selectedChanged ()
Protected Attributes
boolean myIsSelected
Static Protected Attributes
static final Color ourSelectedColor = Color.GOLD
static Dimension ourSize
Detailed Description
turtle image abstract superclass for the Group representing the turtle
Author
Jonathan Tseng
Definition at line 11 of file TurtleImage.java.
Constructor & Destructor Documentation
turtle.TurtleImage.TurtleImage ()
Definition at line 17 of file TurtleImage.java.
Member Function Documentation
abstract double turtle.TurtleImage.getRadius () abstract
Referenced by turtle.TurtleViewController.getRadius().
boolean turtle.TurtleImage.isSelected ()
Definition at line 21 of file TurtleImage.java.
References turtle.TurtleImage.myIsSelected.
Referenced by turtle.TurtleViewController.isSelected(), turtle.TurtleViewController.setImage(), and turtle.TurtleImage.setSelection().
abstract void turtle.TurtleImage.selectedChanged () abstract protected
Referenced by turtle.TurtleImage.toggleSelection().
void turtle.TurtleImage.setSelection (boolean isSelected)
Definition at line 34 of file TurtleImage.java.
References turtle.TurtleImage.isSelected(), and turtle.TurtleImage.toggleSelection().
Referenced by turtle.TurtleViewController.TurtleViewController().
static void turtle.TurtleImage.setSize (Dimension size) static
Definition at line 25 of file TurtleImage.java.
Referenced by turtle.TurtleViewController.TurtleViewController().
void turtle.TurtleImage.toggleSelection ()
Definition at line 29 of file TurtleImage.java.
References turtle.TurtleImage.myIsSelected, and turtle.TurtleImage.selectedChanged().
Referenced by turtle.TurtleImage.setSelection().
void turtle.TurtleImage.updateVisible (boolean visible)
Definition at line 43 of file TurtleImage.java.
Referenced by turtle.TurtleViewController.updateVisible().
Member Data Documentation
boolean turtle.TurtleImage.myIsSelected protected
Definition at line 15 of file TurtleImage.java.
Referenced by turtle.TurtleImage.isSelected(), turtle.UserChosenTurtleImage.selectedChanged(), turtle.DefaultTurtleImage.selectedChanged(), and turtle.TurtleImage.toggleSelection().
final Color turtle.TurtleImage.ourSelectedColor = Color.GOLD static protected
Definition at line 12 of file TurtleImage.java.
Referenced by turtle.UserChosenTurtleImage.selectedChanged(), and turtle.DefaultTurtleImage.selectedChanged().
Dimension turtle.TurtleImage.ourSize static protected
Definition at line 14 of file TurtleImage.java.
Referenced by turtle.UserChosenTurtleImage.createBorder(), turtle.DefaultTurtleImage.createHeadBodyTail(), turtle.DefaultTurtleImage.createLegs(), turtle.UserChosenTurtleImage.getRadius(), turtle.DefaultTurtleImage.getRadius(), and turtle.UserChosenTurtleImage.UserChosenTurtleImage().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/turtle/TurtleImage.java