slogo_team04: interpreter.expression.TurtleQueryExpression Class Reference
interpreter.expression.TurtleQueryExpression Class Reference abstract
Public Member Functions
void setNumArgs (int value)
void loadArguments (Deque< SLogoExpression > args)
void loadLibrary (CommandReferenceLibrary library)
void loadModel (MainModel model)
SLogoResult evaluate ()
int getNumArgs ()
void setValue (String value)
String getValue ()
Protected Member Functions
abstract double getValueFromModel (MainModel model)
Protected Attributes
MainModel myModel
String myValue
Detailed Description
superclass for SLogoExpressions that are Turtle Queries
Author
Abhishek B
Definition at line 15 of file TurtleQueryExpression.java.
Member Function Documentation
SLogoResult interpreter.expression.TurtleQueryExpression.evaluate ()
evaluates the expression and returns an SLogoResult
Returns
Exceptions
SLogoParsingException
Implements interpreter.expression.SLogoExpression.
Definition at line 35 of file TurtleQueryExpression.java.
References interpreter.expression.TurtleQueryExpression.getValueFromModel(), and interpreter.result.SLogoResult.setValue().
int interpreter.expression.TurtleQueryExpression.getNumArgs ()
Gets the number of arguments for the expression.
Returns
Implements interpreter.expression.SLogoExpression.
Definition at line 41 of file TurtleQueryExpression.java.
String interpreter.expression.TurtleQueryExpression.getValue ()
Gets the String value of the expression
Returns
value
Implements interpreter.expression.SLogoExpression.
Definition at line 51 of file TurtleQueryExpression.java.
References interpreter.expression.TurtleQueryExpression.myValue.
abstract double interpreter.expression.TurtleQueryExpression.getValueFromModel (MainModel model) abstract protected
Referenced by interpreter.expression.TurtleQueryExpression.evaluate().
void interpreter.expression.TurtleQueryExpression.loadArguments (Deque< SLogoExpression > args)
Querying expressions do not take arguments, so this is not defined
Implements interpreter.expression.SLogoExpression.
Definition at line 25 of file TurtleQueryExpression.java.
void interpreter.expression.TurtleQueryExpression.loadLibrary (CommandReferenceLibrary library)
Sets the library from the CommandReferenceLibrary
Parameters
library
Implements interpreter.expression.SLogoExpression.
Definition at line 28 of file TurtleQueryExpression.java.
void interpreter.expression.TurtleQueryExpression.loadModel (MainModel model)
Loads the model
Parameters
mode
Implements interpreter.expression.SLogoExpression.
Definition at line 31 of file TurtleQueryExpression.java.
void interpreter.expression.TurtleQueryExpression.setNumArgs (int value)
Sets the number of arguments
Parameters
value
Implements interpreter.expression.SLogoExpression.
Definition at line 19 of file TurtleQueryExpression.java.
void interpreter.expression.TurtleQueryExpression.setValue (String value)
Sets the value of the expression
Parameters
value
Implements interpreter.expression.SLogoExpression.
Definition at line 46 of file TurtleQueryExpression.java.
Member Data Documentation
MainModel interpreter.expression.TurtleQueryExpression.myModel protected
Definition at line 16 of file TurtleQueryExpression.java.
String interpreter.expression.TurtleQueryExpression.myValue protected
Definition at line 17 of file TurtleQueryExpression.java.
Referenced by interpreter.expression.TurtleQueryExpression.getValue().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/interpreter/expression/TurtleQueryExpression.java