slogo_team04: viewcontroller.commands.CommandClickableListWindowViewController Class Reference
viewcontroller.commands.CommandClickableListWindowViewController Class Reference abstract
Public Member Functions
CommandClickableListWindowViewController (int width, int height)
Public Member Functions inherited from viewcontroller.commands.CommandListWindowViewController
CommandListWindowViewController (int width, int height)
Public Member Functions inherited from viewcontroller.commands.CommandWindowViewController
CommandWindowViewController (int width, int height)
Public Member Functions inherited from viewcontroller.ViewController
Node getNode ()
void applyTranslations ()
Protected Member Functions
void addCommand (String commandLabelString)
Protected Member Functions inherited from viewcontroller.commands.CommandListWindowViewController
void updateScroller ()
Protected Member Functions inherited from viewcontroller.commands.CommandWindowViewController
void setTitle (String titleText)
Protected Attributes
CommandWindowContainerViewController myCommandWindowContainer
Protected Attributes inherited from viewcontroller.commands.CommandListWindowViewController
ScrollPane myScrollPane
VBox myListVerticalBox
Protected Attributes inherited from viewcontroller.commands.CommandWindowViewController
BorderPane myPane
VBox myCommandWindowVerticalBox
Label myTitleLabel
Dimension SIZE = new Dimension()
Detailed Description
Abstract class for clickable lists - particularly, the command history and user defined methods lists.
Author
Abhishek B
Definition at line 14 of file CommandClickableListWindowViewController.java.
Constructor & Destructor Documentation
viewcontroller.commands.CommandClickableListWindowViewController.CommandClickableListWindowViewController (int width, int height)
Definition at line 17 of file CommandClickableListWindowViewController.java.
Member Function Documentation
void viewcontroller.commands.CommandClickableListWindowViewController.addCommand (String commandLabelString) protected
Add a command as a Label, and upon click, this will be populated in the command prompt window via the parent container.
Parameters
commandLabelString - Label text
Definition at line 25 of file CommandClickableListWindowViewController.java.
References viewcontroller.commands.CommandWindowContainerViewController.moveCommandTextToPromptWindow(), viewcontroller.commands.CommandListWindowViewController.myListVerticalBox, and viewcontroller.commands.CommandListWindowViewController.updateScroller().
Referenced by viewcontroller.commands.CommandHistoryViewController.update(), and viewcontroller.commands.UserDefinedMethodsViewController.update().
Member Data Documentation
CommandWindowContainerViewController viewcontroller.commands.CommandClickableListWindowViewController.myCommandWindowContainer protected
Definition at line 16 of file CommandClickableListWindowViewController.java.
Referenced by viewcontroller.commands.CommandHistoryViewController.CommandHistoryViewController(), and viewcontroller.commands.UserDefinedMethodsViewController.UserDefinedMethodsViewController().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/viewcontroller/commands/CommandClickableListWindowViewController.java