slogo_team04: turtle.TurtleViewController Class Reference
turtle.TurtleViewController Class Reference
Public Member Functions
TurtleViewController ()
boolean isSelected ()
void updateVisible (boolean visible)
void setImage (File file)
double getRadius ()
Node getNode ()
void applyTranslations ()
Private Attributes
Group myGroup
TurtleImage myTurtleImage
Static Private Attributes
static final Dimension mySize
Detailed Description
view controller for an individual turtle object
Author
Jonathan Tseng
Definition at line 18 of file TurtleViewController.java.
Constructor & Destructor Documentation
turtle.TurtleViewController.TurtleViewController ()
Definition at line 23 of file TurtleViewController.java.
References turtle.TurtleImage.setSelection(), and turtle.TurtleImage.setSize().
Member Function Documentation
void turtle.TurtleViewController.applyTranslations ()
translate the string using the GUI Reference Library
Implements viewcontroller.ViewController.
Definition at line 67 of file TurtleViewController.java.
Node turtle.TurtleViewController.getNode ()
returns the Node representing the view for a view controller
Returns
Implements viewcontroller.ViewController.
Definition at line 63 of file TurtleViewController.java.
References turtle.TurtleViewController.myGroup.
Referenced by turtle.Turtle.getTurtle().
double turtle.TurtleViewController.getRadius ()
gets the radius of the turtle
Returns
Definition at line 59 of file TurtleViewController.java.
References turtle.TurtleImage.getRadius().
Referenced by turtle.Turtle.getTurtleRadius().
boolean turtle.TurtleViewController.isSelected ()
Definition at line 30 of file TurtleViewController.java.
References turtle.TurtleImage.isSelected().
Referenced by turtle.Turtle.isSelected().
void turtle.TurtleViewController.setImage (File file)
Definition at line 37 of file TurtleViewController.java.
References turtle.TurtleImage.isSelected().
Referenced by turtle.Turtle.setImage().
void turtle.TurtleViewController.updateVisible (boolean visible)
Definition at line 33 of file TurtleViewController.java.
References turtle.TurtleImage.updateVisible().
Referenced by turtle.Turtle.updateVisualState().
Member Data Documentation
Group turtle.TurtleViewController.myGroup private
Definition at line 19 of file TurtleViewController.java.
Referenced by turtle.TurtleViewController.getNode().
final Dimension turtle.TurtleViewController.mySize static private
Initial value:
= new Dimension(Main.SIZE.width / 40,
            Main.SIZE.width / 40)
Definition at line 20 of file TurtleViewController.java.
TurtleImage turtle.TurtleViewController.myTurtleImage private
Definition at line 22 of file TurtleViewController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/turtle/TurtleViewController.java