slogo_team04: interpreter.CommandReferenceLibrary Class Reference
interpreter.CommandReferenceLibrary Class Reference
Public Member Functions
CommandReferenceLibrary (String language, UserDefinedCommandsModel commandsModel, UserDefinedVariablesModel variablesModel)
void setLanguageAndReferences (String language)
UserDefinedCommandsModel getUserDefinedCommands ()
UserDefinedVariablesModel getUserDefinedVariables ()
Map< String, Integer > getCommandsToNumArgs ()
Map< String, String > getReferencesToCommands ()
Map< String, String > getCommandsToDirectories ()
Map< String, String > getReverseSyntaxes ()
Set< String > getSyntaxSet ()
String getLogoLanguage ()
Public Attributes
final String propertiesPath = "resources.languages."
final String directory = "DirectoryListing"
final String numberArgs = "NumberArguments"
final String syntax = "Syntax"
final String splitSpace = "\\s+"
final String splitBar = "\\|"
Private Member Functions
void initializeDirectoryReferences ()
void initializeNumArgsMap ()
void initializeSyntaxMap ()
void setCommandReference (String language)
Private Attributes
Set< String > myCommandSet
Set< String > myDirectorySet
Map< String, String > mySyntaxMap
Map< String, String > myReverseSyntaxMap
Map< String, String > myCommandToDirectoryMap
Map< String, Integer > myCommandToNumArgsMap
Map< String, String > myReferenceToCommandMap
String myLanguage
ResourceBundle myCommandReference
ResourceBundle myDirectoryListing
ResourceBundle myNumberArguments
ResourceBundle mySyntaxReference
UserDefinedCommandsModel myDefinedCommands
UserDefinedVariablesModel myDefinedVariables
Detailed Description
Holds references to Syntax, Commands, and UserDefinedCommands and Variables
Author
Will Chang
Definition at line 23 of file CommandReferenceLibrary.java.
Constructor & Destructor Documentation
interpreter.CommandReferenceLibrary.CommandReferenceLibrary (String language, UserDefinedCommandsModel commandsModel, UserDefinedVariablesModel variablesModel)
Constructor
Parameters
language of the References
commandsModel the commands model
variablesModel the variables model
Definition at line 55 of file CommandReferenceLibrary.java.
References interpreter.CommandReferenceLibrary.initializeDirectoryReferences(), interpreter.CommandReferenceLibrary.initializeNumArgsMap(), interpreter.CommandReferenceLibrary.initializeSyntaxMap(), and interpreter.CommandReferenceLibrary.setLanguageAndReferences().
Member Function Documentation
Map<String, String> interpreter.CommandReferenceLibrary.getCommandsToDirectories ()
Definition at line 158 of file CommandReferenceLibrary.java.
References interpreter.CommandReferenceLibrary.myCommandToDirectoryMap.
Referenced by interpreter.SLogoExpressionFactory.SLogoExpressionFactory().
Map<String, Integer> interpreter.CommandReferenceLibrary.getCommandsToNumArgs ()
Definition at line 150 of file CommandReferenceLibrary.java.
References interpreter.CommandReferenceLibrary.myCommandToNumArgsMap.
Referenced by interpreter.SLogoExpressionFactory.SLogoExpressionFactory().
String interpreter.CommandReferenceLibrary.getLogoLanguage ()
Definition at line 170 of file CommandReferenceLibrary.java.
References interpreter.CommandReferenceLibrary.myLanguage.
Map<String, String> interpreter.CommandReferenceLibrary.getReferencesToCommands ()
Definition at line 154 of file CommandReferenceLibrary.java.
References interpreter.CommandReferenceLibrary.myReferenceToCommandMap.
Referenced by model.MainModel.interpretSLogoCommand(), and interpreter.SLogoExpressionFactory.SLogoExpressionFactory().
Map<String, String> interpreter.CommandReferenceLibrary.getReverseSyntaxes ()
Definition at line 162 of file CommandReferenceLibrary.java.
References interpreter.CommandReferenceLibrary.myReverseSyntaxMap.
Referenced by interpreter.SLogoExpressionFactory.SLogoExpressionFactory().
Set<String> interpreter.CommandReferenceLibrary.getSyntaxSet ()
Definition at line 166 of file CommandReferenceLibrary.java.
UserDefinedCommandsModel interpreter.CommandReferenceLibrary.getUserDefinedCommands ()
Getters for all References
Returns
Definition at line 142 of file CommandReferenceLibrary.java.
References interpreter.CommandReferenceLibrary.myDefinedCommands.
Referenced by interpreter.expression.userdefined.MakeUserInstruction.evaluate().
UserDefinedVariablesModel interpreter.CommandReferenceLibrary.getUserDefinedVariables ()
Definition at line 146 of file CommandReferenceLibrary.java.
References interpreter.CommandReferenceLibrary.myDefinedVariables.
Referenced by interpreter.expression.syntax.Variable.evaluate(), interpreter.expression.userdefined.MakeVariable.evaluate(), interpreter.expression.userdefined.For.evaluate(), interpreter.expression.userdefined.Repeat.evaluate(), interpreter.expression.userdefined.DoTimes.evaluate(), and interpreter.expression.syntax.Command.evaluate().
void interpreter.CommandReferenceLibrary.initializeDirectoryReferences () private
Initialize the Directory References
Definition at line 77 of file CommandReferenceLibrary.java.
Referenced by interpreter.CommandReferenceLibrary.CommandReferenceLibrary().
void interpreter.CommandReferenceLibrary.initializeNumArgsMap () private
Initializes the NumArgsMap
Definition at line 90 of file CommandReferenceLibrary.java.
Referenced by interpreter.CommandReferenceLibrary.CommandReferenceLibrary().
void interpreter.CommandReferenceLibrary.initializeSyntaxMap () private
Initializes the SyntaxMap
Definition at line 99 of file CommandReferenceLibrary.java.
Referenced by interpreter.CommandReferenceLibrary.CommandReferenceLibrary().
void interpreter.CommandReferenceLibrary.setCommandReference (String language) private
Sets the Reference Language for SLogo Commands
Parameters
language to set to.
Definition at line 122 of file CommandReferenceLibrary.java.
Referenced by interpreter.CommandReferenceLibrary.setLanguageAndReferences().
void interpreter.CommandReferenceLibrary.setLanguageAndReferences (String language)
Sets the language for the Command References
Parameters
language
Definition at line 113 of file CommandReferenceLibrary.java.
References interpreter.CommandReferenceLibrary.setCommandReference().
Referenced by interpreter.CommandReferenceLibrary.CommandReferenceLibrary(), and interpreter.Interpreter.setLanguage().
Member Data Documentation
final String interpreter.CommandReferenceLibrary.directory = "DirectoryListing"
Definition at line 26 of file CommandReferenceLibrary.java.
ResourceBundle interpreter.CommandReferenceLibrary.myCommandReference private
Definition at line 42 of file CommandReferenceLibrary.java.
Set<String> interpreter.CommandReferenceLibrary.myCommandSet private
Definition at line 32 of file CommandReferenceLibrary.java.
Map<String, String> interpreter.CommandReferenceLibrary.myCommandToDirectoryMap private
Definition at line 37 of file CommandReferenceLibrary.java.
Referenced by interpreter.CommandReferenceLibrary.getCommandsToDirectories().
Map<String, Integer> interpreter.CommandReferenceLibrary.myCommandToNumArgsMap private
Definition at line 38 of file CommandReferenceLibrary.java.
Referenced by interpreter.CommandReferenceLibrary.getCommandsToNumArgs().
UserDefinedCommandsModel interpreter.CommandReferenceLibrary.myDefinedCommands private
Definition at line 46 of file CommandReferenceLibrary.java.
Referenced by interpreter.CommandReferenceLibrary.getUserDefinedCommands().
UserDefinedVariablesModel interpreter.CommandReferenceLibrary.myDefinedVariables private
Definition at line 47 of file CommandReferenceLibrary.java.
Referenced by interpreter.CommandReferenceLibrary.getUserDefinedVariables().
ResourceBundle interpreter.CommandReferenceLibrary.myDirectoryListing private
Definition at line 43 of file CommandReferenceLibrary.java.
Set<String> interpreter.CommandReferenceLibrary.myDirectorySet private
Definition at line 33 of file CommandReferenceLibrary.java.
String interpreter.CommandReferenceLibrary.myLanguage private
Definition at line 41 of file CommandReferenceLibrary.java.
Referenced by interpreter.CommandReferenceLibrary.getLogoLanguage().
ResourceBundle interpreter.CommandReferenceLibrary.myNumberArguments private
Definition at line 44 of file CommandReferenceLibrary.java.
Map<String, String> interpreter.CommandReferenceLibrary.myReferenceToCommandMap private
Definition at line 39 of file CommandReferenceLibrary.java.
Referenced by interpreter.CommandReferenceLibrary.getReferencesToCommands().
Map<String, String> interpreter.CommandReferenceLibrary.myReverseSyntaxMap private
Definition at line 36 of file CommandReferenceLibrary.java.
Referenced by interpreter.CommandReferenceLibrary.getReverseSyntaxes().
Map<String, String> interpreter.CommandReferenceLibrary.mySyntaxMap private
Definition at line 35 of file CommandReferenceLibrary.java.
ResourceBundle interpreter.CommandReferenceLibrary.mySyntaxReference private
Definition at line 45 of file CommandReferenceLibrary.java.
final String interpreter.CommandReferenceLibrary.numberArgs = "NumberArguments"
Definition at line 27 of file CommandReferenceLibrary.java.
final String interpreter.CommandReferenceLibrary.propertiesPath = "resources.languages."
Definition at line 25 of file CommandReferenceLibrary.java.
final String interpreter.CommandReferenceLibrary.splitBar = "\\|"
Definition at line 30 of file CommandReferenceLibrary.java.
final String interpreter.CommandReferenceLibrary.splitSpace = "\\s+"
Definition at line 29 of file CommandReferenceLibrary.java.
final String interpreter.CommandReferenceLibrary.syntax = "Syntax"
Definition at line 28 of file CommandReferenceLibrary.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/interpreter/CommandReferenceLibrary.java