slogo_team04: interpreter.expression.MathExpression Class Reference
interpreter.expression.MathExpression Class Reference abstract
Public Member Functions
MathExpression ()
void setNumArgs (int value)
void loadArguments (Deque< SLogoExpression > args) throws SLogoParsingException
void loadLibrary (CommandReferenceLibrary library)
void loadModel (MainModel model)
SLogoResult evaluate ()
int getNumArgs ()
void setValue (String value)
String getValue ()
Protected Member Functions
SLogoResult applyOperatorAndMerge (Deque< SLogoResult > results)
abstract double applyMath (Deque< SLogoResult > results)
void mergePreviousResults (Deque< SLogoResult > results, SLogoResult myResult)
Protected Attributes
Deque< SLogoExpression > myArguments
int myNumArgs
CommandReferenceLibrary myLibrary
MainModel myModel
String myValue
Detailed Description
Superclass of SLogoExpressions for Math expressions
Author
Will Chang
Definition at line 24 of file MathExpression.java.
Constructor & Destructor Documentation
interpreter.expression.MathExpression.MathExpression ()
Definition at line 32 of file MathExpression.java.
Member Function Documentation
abstract double interpreter.expression.MathExpression.applyMath (Deque< SLogoResult > results) abstract protected
Applies the defined math operator in each subclass.
Parameters
results
Returns
Referenced by interpreter.expression.MathExpression.applyOperatorAndMerge().
SLogoResult interpreter.expression.MathExpression.applyOperatorAndMerge (Deque< SLogoResult > results) protected
Applies the Math operator and merges the results.
Parameters
results
Returns
Definition at line 76 of file MathExpression.java.
References interpreter.expression.MathExpression.applyMath(), interpreter.expression.MathExpression.mergePreviousResults(), and interpreter.result.SLogoResult.setValue().
Referenced by interpreter.expression.MathExpression.evaluate().
SLogoResult interpreter.expression.MathExpression.evaluate ()
evaluates the expression and returns an SLogoResult
Returns
Exceptions
SLogoParsingException
Implements interpreter.expression.SLogoExpression.
Definition at line 63 of file MathExpression.java.
References interpreter.expression.MathExpression.applyOperatorAndMerge().
int interpreter.expression.MathExpression.getNumArgs ()
Gets the number of arguments for the expression.
Returns
Implements interpreter.expression.SLogoExpression.
Definition at line 105 of file MathExpression.java.
References interpreter.expression.MathExpression.myNumArgs.
String interpreter.expression.MathExpression.getValue ()
Gets the String value of the expression
Returns
value
Implements interpreter.expression.SLogoExpression.
Definition at line 115 of file MathExpression.java.
References interpreter.expression.MathExpression.myValue.
void interpreter.expression.MathExpression.loadArguments (Deque< SLogoExpression > args) throws SLogoParsingException
loads the list of expressions as arguments for the expression
Parameters
args
Exceptions
NullPointerException
SLogoParsingException
Implements interpreter.expression.SLogoExpression.
Definition at line 42 of file MathExpression.java.
References interpreter.expression.MathExpression.myNumArgs.
void interpreter.expression.MathExpression.loadLibrary (CommandReferenceLibrary library)
Sets the library from the CommandReferenceLibrary
Parameters
library
Implements interpreter.expression.SLogoExpression.
Definition at line 53 of file MathExpression.java.
void interpreter.expression.MathExpression.loadModel (MainModel model)
Loads the model
Parameters
mode
Implements interpreter.expression.SLogoExpression.
Definition at line 58 of file MathExpression.java.
void interpreter.expression.MathExpression.mergePreviousResults (Deque< SLogoResult > results, SLogoResult myResult) protected
Merges the results
Parameters
results list to merge
myResult result current expression is returning
Definition at line 95 of file MathExpression.java.
References interpreter.result.SLogoResult.getTransition().
Referenced by interpreter.expression.MathExpression.applyOperatorAndMerge().
void interpreter.expression.MathExpression.setNumArgs (int value)
Sets the number of arguments
Parameters
value
Implements interpreter.expression.SLogoExpression.
Definition at line 37 of file MathExpression.java.
void interpreter.expression.MathExpression.setValue (String value)
Sets the value of the expression
Parameters
value
Implements interpreter.expression.SLogoExpression.
Definition at line 110 of file MathExpression.java.
Member Data Documentation
Deque<SLogoExpression> interpreter.expression.MathExpression.myArguments protected
Definition at line 26 of file MathExpression.java.
CommandReferenceLibrary interpreter.expression.MathExpression.myLibrary protected
Definition at line 28 of file MathExpression.java.
MainModel interpreter.expression.MathExpression.myModel protected
Definition at line 29 of file MathExpression.java.
int interpreter.expression.MathExpression.myNumArgs protected
Definition at line 27 of file MathExpression.java.
Referenced by interpreter.expression.MathExpression.getNumArgs(), and interpreter.expression.MathExpression.loadArguments().
String interpreter.expression.MathExpression.myValue protected
Definition at line 30 of file MathExpression.java.
Referenced by interpreter.expression.MathExpression.getValue().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/interpreter/expression/MathExpression.java