slogo_team04: turtle.DefaultTurtleImage Class Reference
turtle.DefaultTurtleImage Class Reference
Public Member Functions
DefaultTurtleImage ()
double getRadius ()
Public Member Functions inherited from turtle.TurtleImage
TurtleImage ()
boolean isSelected ()
void toggleSelection ()
void setSelection (boolean isSelected)
abstract double getRadius ()
void updateVisible (boolean visible)
Protected Member Functions
void selectedChanged ()
Protected Member Functions inherited from turtle.TurtleImage
abstract void selectedChanged ()
Private Member Functions
void createTurtle ()
void createHeadBodyTail ()
void createLegs ()
void animate ()
void animateTurtle ()
void colorTurtle (Color color)
Private Attributes
Timeline myAnimation
boolean myAnimationFlip
Circle myBody
Ellipse myHead
Ellipse myFrontLeftFoot
Ellipse myFrontRightFoot
Ellipse myBackLeftFoot
Ellipse myBackRightFoot
Ellipse myTail
List< Shape > myTurtleBodyParts
Static Private Attributes
static final int FRAMES_PER_SECOND = 7
Additional Inherited Members
Static Public Member Functions inherited from turtle.TurtleImage
static void setSize (Dimension size)
Protected Attributes inherited from turtle.TurtleImage
boolean myIsSelected
Static Protected Attributes inherited from turtle.TurtleImage
static final Color ourSelectedColor = Color.GOLD
static Dimension ourSize
Detailed Description
default turtle image (animated turtle friend)
Author
Jonathan Tseng
Definition at line 20 of file DefaultTurtleImage.java.
Constructor & Destructor Documentation
turtle.DefaultTurtleImage.DefaultTurtleImage ()
Definition at line 36 of file DefaultTurtleImage.java.
References turtle.DefaultTurtleImage.animate(), and turtle.DefaultTurtleImage.createTurtle().
Member Function Documentation
void turtle.DefaultTurtleImage.animate () private
animates the turtle indefinitely (wiggling of legs)
Definition at line 112 of file DefaultTurtleImage.java.
References turtle.DefaultTurtleImage.animateTurtle().
Referenced by turtle.DefaultTurtleImage.DefaultTurtleImage().
void turtle.DefaultTurtleImage.animateTurtle () private
animates the turtle
Definition at line 124 of file DefaultTurtleImage.java.
References turtle.DefaultTurtleImage.myAnimationFlip.
Referenced by turtle.DefaultTurtleImage.animate().
void turtle.DefaultTurtleImage.colorTurtle (Color color) private
Definition at line 133 of file DefaultTurtleImage.java.
Referenced by turtle.DefaultTurtleImage.createTurtle().
void turtle.DefaultTurtleImage.createHeadBodyTail () private
creates head, body, and tail of turtle
Definition at line 64 of file DefaultTurtleImage.java.
References turtle.DefaultTurtleImage.getRadius(), and turtle.TurtleImage.ourSize.
Referenced by turtle.DefaultTurtleImage.createTurtle().
void turtle.DefaultTurtleImage.createLegs () private
creates legs of turtle
Definition at line 79 of file DefaultTurtleImage.java.
References turtle.TurtleImage.ourSize.
Referenced by turtle.DefaultTurtleImage.createTurtle().
void turtle.DefaultTurtleImage.createTurtle () private
Definition at line 43 of file DefaultTurtleImage.java.
References turtle.DefaultTurtleImage.colorTurtle(), turtle.DefaultTurtleImage.createHeadBodyTail(), and turtle.DefaultTurtleImage.createLegs().
Referenced by turtle.DefaultTurtleImage.DefaultTurtleImage().
double turtle.DefaultTurtleImage.getRadius ()
Definition at line 160 of file DefaultTurtleImage.java.
References turtle.TurtleImage.ourSize.
Referenced by turtle.DefaultTurtleImage.createHeadBodyTail(), and turtle.DefaultTurtleImage.selectedChanged().
void turtle.DefaultTurtleImage.selectedChanged () protected
Definition at line 141 of file DefaultTurtleImage.java.
References turtle.DefaultTurtleImage.getRadius(), turtle.TurtleImage.myIsSelected, and turtle.TurtleImage.ourSelectedColor.
Member Data Documentation
final int turtle.DefaultTurtleImage.FRAMES_PER_SECOND = 7 static private
Definition at line 22 of file DefaultTurtleImage.java.
Timeline turtle.DefaultTurtleImage.myAnimation private
Definition at line 24 of file DefaultTurtleImage.java.
boolean turtle.DefaultTurtleImage.myAnimationFlip private
Definition at line 25 of file DefaultTurtleImage.java.
Referenced by turtle.DefaultTurtleImage.animateTurtle().
Ellipse turtle.DefaultTurtleImage.myBackLeftFoot private
Definition at line 31 of file DefaultTurtleImage.java.
Ellipse turtle.DefaultTurtleImage.myBackRightFoot private
Definition at line 32 of file DefaultTurtleImage.java.
Circle turtle.DefaultTurtleImage.myBody private
Definition at line 27 of file DefaultTurtleImage.java.
Ellipse turtle.DefaultTurtleImage.myFrontLeftFoot private
Definition at line 29 of file DefaultTurtleImage.java.
Ellipse turtle.DefaultTurtleImage.myFrontRightFoot private
Definition at line 30 of file DefaultTurtleImage.java.
Ellipse turtle.DefaultTurtleImage.myHead private
Definition at line 28 of file DefaultTurtleImage.java.
Ellipse turtle.DefaultTurtleImage.myTail private
Definition at line 33 of file DefaultTurtleImage.java.
List<Shape> turtle.DefaultTurtleImage.myTurtleBodyParts private
Definition at line 34 of file DefaultTurtleImage.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/turtle/DefaultTurtleImage.java