slogo_team04: transitionstate.TransitionState Class Reference
transitionstate.TransitionState Class Reference
Classes
enum PenChange
enum VisibleChange
Public Member Functions
TransitionState (PenChange penChange, VisibleChange visibleChange, double distance, double rotateClock, double rotateCounterClockwise)
void setTurtles (Collection< Integer > turtleIDs)
Collection< Integer > getTurtles ()
PenChange getPenChange ()
VisibleChange getVisibleChange ()
double getMove ()
double getRotateClockwise ()
double getRotateCounterClockwise ()
Private Attributes
PenChange myPenUp
VisibleChange myTurtleVisible
double myMove
double myRotateClockwise
double myRotateCounterClockwise
Set< Integer > myTurtleIDs
Detailed Description
wrapper class for a transition state for the Grid. Specifies how to draw the next path.
Author
Jonathan Tseng
Tanaka Jimha
Definition at line 14 of file TransitionState.java.
Constructor & Destructor Documentation
transitionstate.TransitionState.TransitionState (PenChange penChange, VisibleChange visibleChange, double distance, double rotateClock, double rotateCounterClockwise)
Definition at line 31 of file TransitionState.java.
Member Function Documentation
double transitionstate.TransitionState.getMove ()
returns double for how much the turtle moves in the forward direction
Returns
Definition at line 68 of file TransitionState.java.
References transitionstate.TransitionState.myMove.
Referenced by turtle.draw.TransitionFactory.createForwardTransition().
PenChange transitionstate.TransitionState.getPenChange ()
returns boolean of whether pen is up or down
Returns
Definition at line 52 of file TransitionState.java.
References transitionstate.TransitionState.myPenUp.
Referenced by turtle.Turtle.updateVisualState().
double transitionstate.TransitionState.getRotateClockwise ()
gets the turtle's clockwise rotation
Returns
Definition at line 76 of file TransitionState.java.
References transitionstate.TransitionState.myRotateClockwise.
Referenced by turtle.draw.TransitionFactory.createTurnTransition().
double transitionstate.TransitionState.getRotateCounterClockwise ()
gets the turtle's counterclockwise rotation
Returns
Definition at line 84 of file TransitionState.java.
References transitionstate.TransitionState.myRotateCounterClockwise.
Referenced by turtle.draw.TransitionFactory.createTurnTransition().
Collection<Integer> transitionstate.TransitionState.getTurtles ()
Definition at line 44 of file TransitionState.java.
References transitionstate.TransitionState.myTurtleIDs.
VisibleChange transitionstate.TransitionState.getVisibleChange ()
returns boolean of whether turtle is visible or not
Returns
Definition at line 60 of file TransitionState.java.
References transitionstate.TransitionState.myTurtleVisible.
Referenced by turtle.Turtle.updateVisualState().
void transitionstate.TransitionState.setTurtles (Collection< Integer > turtleIDs)
Definition at line 40 of file TransitionState.java.
Member Data Documentation
double transitionstate.TransitionState.myMove private
Definition at line 18 of file TransitionState.java.
Referenced by transitionstate.TransitionState.getMove().
PenChange transitionstate.TransitionState.myPenUp private
Definition at line 16 of file TransitionState.java.
Referenced by transitionstate.TransitionState.getPenChange().
double transitionstate.TransitionState.myRotateClockwise private
Definition at line 19 of file TransitionState.java.
Referenced by transitionstate.TransitionState.getRotateClockwise().
double transitionstate.TransitionState.myRotateCounterClockwise private
Definition at line 20 of file TransitionState.java.
Referenced by transitionstate.TransitionState.getRotateCounterClockwise().
Set<Integer> transitionstate.TransitionState.myTurtleIDs private
Definition at line 21 of file TransitionState.java.
Referenced by transitionstate.TransitionState.getTurtles().
VisibleChange transitionstate.TransitionState.myTurtleVisible private
Definition at line 17 of file TransitionState.java.
Referenced by transitionstate.TransitionState.getVisibleChange().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/transitionstate/TransitionState.java