slogo_team04: viewcontroller.turtlegrid.GridButtonBar Class Reference
viewcontroller.turtlegrid.GridButtonBar Class Reference
Public Member Functions
GridButtonBar (EventHandler< ActionEvent > gridColorEventHandler, EventHandler< ActionEvent > penColorEventHandler, ChangeListener< Number > speedSliderChangeListener)
Color getGridColor ()
Color getPenColor ()
double getAnimationSpeed ()
Private Attributes
SLogoColorPicker myGridColorPicker
SLogoColorPicker myPenColorPicker
SLogoSlider mySpeedSlider
Static Private Attributes
static final double SPEED_MIN = 0.5
static final double SPEED_MAX = 5.0
static final String GRID_COLOR_KEY = "GridColor"
static final String PEN_COLOR_KEY = "PenColor"
static final String SPEED_KEY = "Speed"
Detailed Description
button bar shown above grid with turtles
Author
Jonathan Tseng
Definition at line 16 of file GridButtonBar.java.
Constructor & Destructor Documentation
viewcontroller.turtlegrid.GridButtonBar.GridButtonBar (EventHandler< ActionEvent > gridColorEventHandler, EventHandler< ActionEvent > penColorEventHandler, ChangeListener< Number > speedSliderChangeListener)
Definition at line 29 of file GridButtonBar.java.
References viewcontroller.GUIReferenceLibrary.getStringTranslation().
Member Function Documentation
double viewcontroller.turtlegrid.GridButtonBar.getAnimationSpeed ()
Definition at line 50 of file GridButtonBar.java.
References viewcontroller.turtlegrid.SLogoSlider.getValue().
Referenced by viewcontroller.turtlegrid.TurtleWindowViewController.TurtleWindowViewController().
Color viewcontroller.turtlegrid.GridButtonBar.getGridColor ()
Definition at line 42 of file GridButtonBar.java.
References viewcontroller.turtlegrid.SLogoColorPicker.getColor().
Referenced by viewcontroller.turtlegrid.TurtleWindowViewController.gridColorChanged().
Color viewcontroller.turtlegrid.GridButtonBar.getPenColor ()
Definition at line 46 of file GridButtonBar.java.
References viewcontroller.turtlegrid.SLogoColorPicker.getColor().
Referenced by viewcontroller.turtlegrid.TurtleWindowViewController.penColorChanged().
Member Data Documentation
final String viewcontroller.turtlegrid.GridButtonBar.GRID_COLOR_KEY = "GridColor" static private
Definition at line 21 of file GridButtonBar.java.
SLogoColorPicker viewcontroller.turtlegrid.GridButtonBar.myGridColorPicker private
Definition at line 25 of file GridButtonBar.java.
SLogoColorPicker viewcontroller.turtlegrid.GridButtonBar.myPenColorPicker private
Definition at line 26 of file GridButtonBar.java.
SLogoSlider viewcontroller.turtlegrid.GridButtonBar.mySpeedSlider private
Definition at line 27 of file GridButtonBar.java.
final String viewcontroller.turtlegrid.GridButtonBar.PEN_COLOR_KEY = "PenColor" static private
Definition at line 22 of file GridButtonBar.java.
final String viewcontroller.turtlegrid.GridButtonBar.SPEED_KEY = "Speed" static private
Definition at line 23 of file GridButtonBar.java.
final double viewcontroller.turtlegrid.GridButtonBar.SPEED_MAX = 5.0 static private
Definition at line 19 of file GridButtonBar.java.
final double viewcontroller.turtlegrid.GridButtonBar.SPEED_MIN = 0.5 static private
Definition at line 18 of file GridButtonBar.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/viewcontroller/turtlegrid/GridButtonBar.java