slogo_team04: application.Form Class Reference
application.Form Class Reference
Public Member Functions
Form (String title)
void createFormBox ()
void addFormElement (FormElement formElement)
void show ()
void close ()
void setOnSubmit (EventHandler< ActionEvent > event)
Private Member Functions
void createTitle (String title)
void createSubmitButton ()
Private Attributes
Stage myStage
BorderPane myPane
Button mySubmitButton
VBox myFormBox
List< FormElement > myFormElements
Static Private Attributes
static final String SUBMIT_KEY = "SubmitForm"
Detailed Description
abstract class for a form
Author
Jonathan Tseng
Definition at line 25 of file Form.java.
Constructor & Destructor Documentation
application.Form.Form (String title)
Definition at line 35 of file Form.java.
References application.Form.createFormBox(), application.Form.createSubmitButton(), and application.Form.createTitle().
Member Function Documentation
void application.Form.addFormElement (FormElement formElement)
Definition at line 51 of file Form.java.
References application.FormElement.getNode().
Referenced by application.PenForm.PenForm().
void application.Form.close ()
Definition at line 82 of file Form.java.
Referenced by application.Form.createSubmitButton(), and viewcontroller.View.shit().
void application.Form.createFormBox ()
Definition at line 43 of file Form.java.
Referenced by application.Form.Form().
void application.Form.createSubmitButton () private
Definition at line 73 of file Form.java.
References application.Form.close(), and viewcontroller.GUIReferenceLibrary.getStringTranslation().
Referenced by application.Form.Form().
void application.Form.createTitle (String title) private
Definition at line 65 of file Form.java.
Referenced by application.Form.Form().
void application.Form.setOnSubmit (EventHandler< ActionEvent > event)
Definition at line 86 of file Form.java.
Referenced by viewcontroller.View.editPenSettings().
void application.Form.show ()
Definition at line 56 of file Form.java.
Referenced by viewcontroller.View.editPenSettings().
Member Data Documentation
VBox application.Form.myFormBox private
Definition at line 32 of file Form.java.
List<FormElement> application.Form.myFormElements private
Definition at line 33 of file Form.java.
BorderPane application.Form.myPane private
Definition at line 30 of file Form.java.
Stage application.Form.myStage private
Definition at line 29 of file Form.java.
Button application.Form.mySubmitButton private
Definition at line 31 of file Form.java.
final String application.Form.SUBMIT_KEY = "SubmitForm" static private
Definition at line 27 of file Form.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/application/Form.java