slogo_team04: interpreter.expression.ConditionalExpression Class Reference
interpreter.expression.ConditionalExpression Class Reference abstract
Public Member Functions
ConditionalExpression ()
void setNumArgs (int value)
void loadArguments (Deque< SLogoExpression > args) throws SLogoParsingException, NullPointerException
void loadLibrary (CommandReferenceLibrary library)
void loadModel (MainModel model)
SLogoResult evaluate ()
int getNumArgs ()
void setValue (String value)
String getValue ()
Protected Member Functions
SLogoResult applyOperatorAndMerge (Deque< SLogoResult > results)
abstract boolean hasSatisfiedCondition (SLogoResult argument)
Protected Attributes
Deque< SLogoExpression > myArguments
Deque< Double > valuesToCompare
int myNumArgs
CommandReferenceLibrary myLibrary
MainModel myModel
String myValue
Detailed Description
superclass of SLogoExpressions for conditionals
Author
Will Chang
Definition at line 14 of file ConditionalExpression.java.
Constructor & Destructor Documentation
interpreter.expression.ConditionalExpression.ConditionalExpression ()
Definition at line 28 of file ConditionalExpression.java.
Member Function Documentation
SLogoResult interpreter.expression.ConditionalExpression.applyOperatorAndMerge (Deque< SLogoResult > results) protected
Definition at line 70 of file ConditionalExpression.java.
References interpreter.result.SLogoResult.getTransition(), interpreter.expression.ConditionalExpression.hasSatisfiedCondition(), and interpreter.result.SLogoResult.setValue().
Referenced by interpreter.expression.ConditionalExpression.evaluate().
SLogoResult interpreter.expression.ConditionalExpression.evaluate ()
evaluates the expression and returns an SLogoResult
Returns
Exceptions
SLogoParsingException
Implements interpreter.expression.SLogoExpression.
Definition at line 62 of file ConditionalExpression.java.
References interpreter.expression.ConditionalExpression.applyOperatorAndMerge().
int interpreter.expression.ConditionalExpression.getNumArgs ()
Gets the number of arguments for the expression.
Returns
Implements interpreter.expression.SLogoExpression.
Definition at line 85 of file ConditionalExpression.java.
References interpreter.expression.ConditionalExpression.myNumArgs.
String interpreter.expression.ConditionalExpression.getValue ()
Gets the String value of the expression
Returns
value
Implements interpreter.expression.SLogoExpression.
Definition at line 95 of file ConditionalExpression.java.
References interpreter.expression.ConditionalExpression.myValue.
abstract boolean interpreter.expression.ConditionalExpression.hasSatisfiedCondition (SLogoResult argument) abstract protected
Referenced by interpreter.expression.ConditionalExpression.applyOperatorAndMerge().
void interpreter.expression.ConditionalExpression.loadArguments (Deque< SLogoExpression > args) throws SLogoParsingException, NullPointerException
loads the list of expressions as arguments for the expression
Parameters
args
Exceptions
NullPointerException
SLogoParsingException
Implements interpreter.expression.SLogoExpression.
Definition at line 38 of file ConditionalExpression.java.
References interpreter.expression.ConditionalExpression.myNumArgs.
void interpreter.expression.ConditionalExpression.loadLibrary (CommandReferenceLibrary library)
Sets the library from the CommandReferenceLibrary
Parameters
library
Implements interpreter.expression.SLogoExpression.
Definition at line 46 of file ConditionalExpression.java.
void interpreter.expression.ConditionalExpression.loadModel (MainModel model)
Loads the model
Parameters
mode
Implements interpreter.expression.SLogoExpression.
Definition at line 51 of file ConditionalExpression.java.
void interpreter.expression.ConditionalExpression.setNumArgs (int value)
Sets the number of arguments
Parameters
value
Implements interpreter.expression.SLogoExpression.
Definition at line 33 of file ConditionalExpression.java.
void interpreter.expression.ConditionalExpression.setValue (String value)
Sets the value of the expression
Parameters
value
Implements interpreter.expression.SLogoExpression.
Definition at line 90 of file ConditionalExpression.java.
Member Data Documentation
Deque<SLogoExpression> interpreter.expression.ConditionalExpression.myArguments protected
Definition at line 20 of file ConditionalExpression.java.
CommandReferenceLibrary interpreter.expression.ConditionalExpression.myLibrary protected
Definition at line 24 of file ConditionalExpression.java.
MainModel interpreter.expression.ConditionalExpression.myModel protected
Definition at line 25 of file ConditionalExpression.java.
int interpreter.expression.ConditionalExpression.myNumArgs protected
Definition at line 22 of file ConditionalExpression.java.
Referenced by interpreter.expression.ConditionalExpression.getNumArgs(), and interpreter.expression.ConditionalExpression.loadArguments().
String interpreter.expression.ConditionalExpression.myValue protected
Definition at line 26 of file ConditionalExpression.java.
Referenced by interpreter.expression.ConditionalExpression.getValue().
Deque<Double> interpreter.expression.ConditionalExpression.valuesToCompare protected
Definition at line 21 of file ConditionalExpression.java.
Referenced by interpreter.expression.conditional.Equal.hasSatisfiedCondition(), interpreter.expression.conditional.GreaterThan.hasSatisfiedCondition(), interpreter.expression.conditional.LessThan.hasSatisfiedCondition(), and interpreter.expression.conditional.NotEqual.hasSatisfiedCondition().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/interpreter/expression/ConditionalExpression.java