slogo_team04: turtle.Turtle Class Reference
turtle.Turtle Class Reference
Public Member Functions
Turtle ()
Transition createAnimation (List< TransitionState > states)
void updateVisualState (TransitionState transitionState)
TurtleHistoryState redo ()
TurtleHistoryState undo ()
int getId ()
double getX ()
double getY ()
boolean getIsVisible ()
boolean isSelected ()
double getHeading ()
Pen getPen ()
Node getTurtle ()
double getTurtleRadius ()
void setImage (File file)
Private Member Functions
void updateVisible (VisibleChange visibleChange)
Private Attributes
int myId
TurtleViewController myTurtleViewController
Pen myPen
boolean myIsVisible
TurtleHistory myTurtleHistory
Static Private Attributes
static int ourTurtleCount = 0
Detailed Description
Turtle Object. contains its own state and image view
Author
Jonathan Tseng
Definition at line 19 of file Turtle.java.
Constructor & Destructor Documentation
turtle.Turtle.Turtle ()
Definition at line 26 of file Turtle.java.
References turtle.Turtle.getTurtle(), and turtle.Turtle.ourTurtleCount.
Member Function Documentation
Transition turtle.Turtle.createAnimation (List< TransitionState > states)
Definition at line 34 of file Turtle.java.
References turtle.draw.TransitionFactory.createAnimation().
double turtle.Turtle.getHeading ()
Definition at line 74 of file Turtle.java.
References turtle.Turtle.getTurtle().
Referenced by interpreter.expression.singleturtle.SetHeading.setNextTransition(), and interpreter.expression.singleturtle.SetPosition.setNextTransition().
int turtle.Turtle.getId ()
Definition at line 58 of file Turtle.java.
References turtle.Turtle.myId.
Referenced by turtle.SerialisableTurtle.SerialisableTurtle(), and viewcontroller.turtlegrid.TurtleStatusViewController.update().
boolean turtle.Turtle.getIsVisible ()
Definition at line 68 of file Turtle.java.
References turtle.Turtle.myIsVisible.
Pen turtle.Turtle.getPen ()
Definition at line 77 of file Turtle.java.
References turtle.Turtle.myPen.
Referenced by turtle.draw.TransitionFactory.createForwardTransition(), turtle.draw.PenTransition.drawLine(), turtle.draw.PenTransition.formatLine(), and turtle.SerialisableTurtle.SerialisableTurtle().
Node turtle.Turtle.getTurtle ()
Definition at line 80 of file Turtle.java.
References turtle.TurtleViewController.getNode().
Referenced by turtle.draw.LinearTransition.checkWrapping(), turtle.Turtle.getHeading(), turtle.Turtle.getX(), turtle.Turtle.getY(), turtle.draw.TurnTransition.interpolate(), turtle.draw.MoveTransition.interpolateChanges(), turtle.SerialisableTurtle.SerialisableTurtle(), turtle.draw.LinearTransition.setChanges(), turtle.draw.MoveTransition.setStartPoint(), turtle.draw.PenTransition.setStartPoint(), and turtle.Turtle.Turtle().
double turtle.Turtle.getTurtleRadius ()
Definition at line 83 of file Turtle.java.
References turtle.TurtleViewController.getRadius().
Referenced by turtle.draw.LinearTransition.checkWrapping().
double turtle.Turtle.getX ()
Definition at line 61 of file Turtle.java.
References turtle.Turtle.getTurtle(), and viewcontroller.turtlegrid.GridViewController.SIZE.
Referenced by interpreter.expression.singleturtle.SetPosition.setNextTransition(), and viewcontroller.turtlegrid.TurtleStatusViewController.update().
double turtle.Turtle.getY ()
Definition at line 64 of file Turtle.java.
References turtle.Turtle.getTurtle(), and viewcontroller.turtlegrid.GridViewController.SIZE.
Referenced by interpreter.expression.singleturtle.SetPosition.setNextTransition(), and viewcontroller.turtlegrid.TurtleStatusViewController.update().
boolean turtle.Turtle.isSelected ()
Definition at line 71 of file Turtle.java.
References turtle.TurtleViewController.isSelected().
TurtleHistoryState turtle.Turtle.redo ()
Definition at line 52 of file Turtle.java.
References turtle.TurtleHistory.redo().
void turtle.Turtle.setImage (File file)
Definition at line 86 of file Turtle.java.
References turtle.TurtleViewController.setImage().
TurtleHistoryState turtle.Turtle.undo ()
Definition at line 55 of file Turtle.java.
References turtle.TurtleHistory.undo().
void turtle.Turtle.updateVisible (VisibleChange visibleChange) private
Definition at line 89 of file Turtle.java.
References transitionstate.TransitionState.VisibleChange.CHANGE_INVISIBLE, and transitionstate.TransitionState.VisibleChange.CHANGE_VISIBLE.
Referenced by turtle.Turtle.updateVisualState().
void turtle.Turtle.updateVisualState (TransitionState transitionState)
Definition at line 47 of file Turtle.java.
References transitionstate.TransitionState.getPenChange(), transitionstate.TransitionState.getVisibleChange(), turtle.draw.Pen.update(), turtle.TurtleViewController.updateVisible(), and turtle.Turtle.updateVisible().
Referenced by turtle.draw.TransitionFactory.createTurtleTransition().
Member Data Documentation
int turtle.Turtle.myId private
Definition at line 21 of file Turtle.java.
Referenced by turtle.Turtle.getId().
boolean turtle.Turtle.myIsVisible private
Definition at line 24 of file Turtle.java.
Referenced by turtle.Turtle.getIsVisible().
Pen turtle.Turtle.myPen private
Definition at line 23 of file Turtle.java.
Referenced by turtle.Turtle.getPen().
TurtleHistory turtle.Turtle.myTurtleHistory private
Definition at line 25 of file Turtle.java.
TurtleViewController turtle.Turtle.myTurtleViewController private
Definition at line 22 of file Turtle.java.
int turtle.Turtle.ourTurtleCount = 0 static private
Definition at line 20 of file Turtle.java.
Referenced by turtle.Turtle.Turtle().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/turtle/Turtle.java