slogo_team04: viewcontroller.commands.CommandPromptViewController Class Reference
viewcontroller.commands.CommandPromptViewController Class Reference
Public Member Functions
CommandPromptViewController (int width, int height, CommandWindowContainerViewController parent)
void setCommandPromptText (String commandText)
String getCommandPromptText ()
Node getNode ()
void applyTranslations ()
Public Member Functions inherited from viewcontroller.commands.CommandWindowViewController
CommandWindowViewController (int width, int height)
Private Member Functions
void setUpCommandPromptHorizontalBox ()
void setUpCommandPrompt (int parentWidth, int parentHeight)
void setUpSubmitButton (int parentWidth, int parentHeight)
void passCommandToModel (String commandFromPromptTextArea)
Private Attributes
CommandWindowContainerViewController myParent
HBox myCommandPromptHorizontalBox
TextArea myCommandPromptTextArea
Button mySubmitButton
final String PROMPT_KEY = "Prompt"
final String SUBMIT_KEY = "Submit"
final String TEXTAREA_CSS = "text-area"
String myPromptTranslation
String mySubmitTranslation
Additional Inherited Members
Protected Member Functions inherited from viewcontroller.commands.CommandWindowViewController
void setTitle (String titleText)
Protected Attributes inherited from viewcontroller.commands.CommandWindowViewController
BorderPane myPane
VBox myCommandWindowVerticalBox
Label myTitleLabel
Dimension SIZE = new Dimension()
Detailed Description
View Controller for the TextArea where the user types the commands as strings to be sent to the back end.
Author
Abhishek B
Definition at line 21 of file CommandPromptViewController.java.
Constructor & Destructor Documentation
viewcontroller.commands.CommandPromptViewController.CommandPromptViewController (int width, int height, CommandWindowContainerViewController parent)
Definition at line 33 of file CommandPromptViewController.java.
References viewcontroller.commands.CommandPromptViewController.applyTranslations(), viewcontroller.commands.CommandWindowViewController.myCommandWindowVerticalBox, viewcontroller.commands.CommandWindowViewController.setTitle(), and viewcontroller.commands.CommandPromptViewController.setUpCommandPromptHorizontalBox().
Member Function Documentation
void viewcontroller.commands.CommandPromptViewController.applyTranslations ()
translate the string using the GUI Reference Library
Implements viewcontroller.ViewController.
Definition at line 119 of file CommandPromptViewController.java.
References viewcontroller.GUIReferenceLibrary.getStringTranslation().
Referenced by viewcontroller.commands.CommandPromptViewController.CommandPromptViewController().
String viewcontroller.commands.CommandPromptViewController.getCommandPromptText ()
Definition at line 53 of file CommandPromptViewController.java.
Referenced by unittest.CommandPromptTextTest.testTransferOfString().
Node viewcontroller.commands.CommandPromptViewController.getNode ()
returns the Node representing the view for a view controller
Returns
Implements viewcontroller.ViewController.
Definition at line 114 of file CommandPromptViewController.java.
References viewcontroller.commands.CommandWindowViewController.myPane.
Referenced by viewcontroller.commands.CommandWindowContainerViewController.placeCommandWindows().
void viewcontroller.commands.CommandPromptViewController.passCommandToModel (String commandFromPromptTextArea) private
Called by submit button
Parameters
commandFromPromptTextArea
Definition at line 108 of file CommandPromptViewController.java.
References viewcontroller.commands.CommandWindowContainerViewController.passSLogoCommand().
Referenced by viewcontroller.commands.CommandPromptViewController.setUpSubmitButton().
void viewcontroller.commands.CommandPromptViewController.setCommandPromptText (String commandText)
Set the command prompt text area with the input text string.
Parameters
commandText
Definition at line 49 of file CommandPromptViewController.java.
Referenced by viewcontroller.commands.CommandWindowContainerViewController.loadScript(), and viewcontroller.commands.CommandWindowContainerViewController.moveCommandTextToPromptWindow().
void viewcontroller.commands.CommandPromptViewController.setUpCommandPrompt (int parentWidth, int parentHeight) private
Initialize the TextArea for inputting command text
Parameters
parentWidth
parentHeight
Definition at line 76 of file CommandPromptViewController.java.
Referenced by viewcontroller.commands.CommandPromptViewController.setUpCommandPromptHorizontalBox().
void viewcontroller.commands.CommandPromptViewController.setUpCommandPromptHorizontalBox () private
Initialize the HBox containing the TextArea and Button
Definition at line 60 of file CommandPromptViewController.java.
References viewcontroller.commands.CommandPromptViewController.setUpCommandPrompt(), viewcontroller.commands.CommandPromptViewController.setUpSubmitButton(), and viewcontroller.commands.CommandWindowViewController.SIZE.
Referenced by viewcontroller.commands.CommandPromptViewController.CommandPromptViewController().
void viewcontroller.commands.CommandPromptViewController.setUpSubmitButton (int parentWidth, int parentHeight) private
Initialize button, which will send all content from TextArea and clear the TextArea upon execution.
Parameters
parentWidth
parentHeight
Definition at line 91 of file CommandPromptViewController.java.
References viewcontroller.commands.CommandPromptViewController.passCommandToModel().
Referenced by viewcontroller.commands.CommandPromptViewController.setUpCommandPromptHorizontalBox().
Member Data Documentation
HBox viewcontroller.commands.CommandPromptViewController.myCommandPromptHorizontalBox private
Definition at line 24 of file CommandPromptViewController.java.
TextArea viewcontroller.commands.CommandPromptViewController.myCommandPromptTextArea private
Definition at line 25 of file CommandPromptViewController.java.
CommandWindowContainerViewController viewcontroller.commands.CommandPromptViewController.myParent private
Definition at line 23 of file CommandPromptViewController.java.
String viewcontroller.commands.CommandPromptViewController.myPromptTranslation private
Definition at line 30 of file CommandPromptViewController.java.
Button viewcontroller.commands.CommandPromptViewController.mySubmitButton private
Definition at line 26 of file CommandPromptViewController.java.
String viewcontroller.commands.CommandPromptViewController.mySubmitTranslation private
Definition at line 31 of file CommandPromptViewController.java.
final String viewcontroller.commands.CommandPromptViewController.PROMPT_KEY = "Prompt" private
Definition at line 27 of file CommandPromptViewController.java.
final String viewcontroller.commands.CommandPromptViewController.SUBMIT_KEY = "Submit" private
Definition at line 28 of file CommandPromptViewController.java.
final String viewcontroller.commands.CommandPromptViewController.TEXTAREA_CSS = "text-area" private
Definition at line 29 of file CommandPromptViewController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/viewcontroller/commands/CommandPromptViewController.java