slogo_team04: model.UserDefinedVariablesModel Class Reference
model.UserDefinedVariablesModel Class Reference
Public Member Functions
UserDefinedVariablesModel ()
Map< String, Double > getAllVariables ()
Double getVariable (String variable)
void putVariable (String variable, double value)
boolean containsVariable (String myValue)
void remove (String repCount)
Private Attributes
Map< String, Double > myDefinedVariables
Set< String > myVariables
Detailed Description
Model for User Defined Variables
Author
Tanaka Jimha and Jonathan Tseng
Definition at line 14 of file UserDefinedVariablesModel.java.
Constructor & Destructor Documentation
model.UserDefinedVariablesModel.UserDefinedVariablesModel ()
Definition at line 19 of file UserDefinedVariablesModel.java.
Member Function Documentation
boolean model.UserDefinedVariablesModel.containsVariable (String myValue)
Definition at line 45 of file UserDefinedVariablesModel.java.
Referenced by interpreter.expression.syntax.Variable.evaluate().
Map<String, Double> model.UserDefinedVariablesModel.getAllVariables ()
returns the current list of user defined variables
Returns
Definition at line 28 of file UserDefinedVariablesModel.java.
References model.UserDefinedVariablesModel.myDefinedVariables.
Referenced by viewcontroller.commands.UserDefinedVariablesViewController.update().
Double model.UserDefinedVariablesModel.getVariable (String variable)
Definition at line 32 of file UserDefinedVariablesModel.java.
Referenced by interpreter.expression.syntax.Variable.evaluate().
void model.UserDefinedVariablesModel.putVariable (String variable, double value)
adds an SLogo expression to the list of user defined variables if variable already exists with same name, then it is replaced
Parameters
expression
Definition at line 41 of file UserDefinedVariablesModel.java.
Referenced by interpreter.expression.userdefined.MakeVariable.evaluate(), and interpreter.expression.syntax.Command.evaluate().
void model.UserDefinedVariablesModel.remove (String repCount)
Definition at line 49 of file UserDefinedVariablesModel.java.
Referenced by interpreter.expression.syntax.Command.evaluate().
Member Data Documentation
Map<String, Double> model.UserDefinedVariablesModel.myDefinedVariables private
Definition at line 16 of file UserDefinedVariablesModel.java.
Referenced by model.UserDefinedVariablesModel.getAllVariables().
Set<String> model.UserDefinedVariablesModel.myVariables private
Definition at line 17 of file UserDefinedVariablesModel.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/model/UserDefinedVariablesModel.java