slogo_team04: turtle.SerialisableTurtle Class Reference
turtle.SerialisableTurtle Class Reference
Public Member Functions
SerialisableTurtle (Turtle turtle)
int getMyId ()
double getTranslateX ()
double getTranslateY ()
double getRotate ()
boolean isSelected ()
File getImageFile ()
String getPenColour ()
boolean getIsPenDown ()
List< Line > getLines ()
Static Public Member Functions
static int getOurTurtleCount ()
Private Attributes
int myId
double translateX
double translateY
double rotate
boolean isSelected
File imageFile
String penColour
boolean isPenDown
List< Line > lines
Static Private Attributes
static int ourTurtleCount
Detailed Description
Serialisable Version of the Turtle class which doesn't hold the non serialisable javafx components
Author
Tanaka Jimha
Definition at line 14 of file SerialisableTurtle.java.
Constructor & Destructor Documentation
turtle.SerialisableTurtle.SerialisableTurtle (Turtle turtle)
Definition at line 28 of file SerialisableTurtle.java.
References turtle.draw.Pen.getColor(), turtle.draw.Pen.getDrawnLines(), turtle.Turtle.getId(), turtle.Turtle.getPen(), turtle.draw.Pen.getPenDown(), and turtle.Turtle.getTurtle().
Member Function Documentation
File turtle.SerialisableTurtle.getImageFile ()
Definition at line 64 of file SerialisableTurtle.java.
References turtle.SerialisableTurtle.imageFile.
boolean turtle.SerialisableTurtle.getIsPenDown ()
Definition at line 72 of file SerialisableTurtle.java.
References turtle.SerialisableTurtle.isPenDown.
List<Line> turtle.SerialisableTurtle.getLines ()
Definition at line 76 of file SerialisableTurtle.java.
References turtle.SerialisableTurtle.lines.
int turtle.SerialisableTurtle.getMyId ()
Definition at line 44 of file SerialisableTurtle.java.
References turtle.SerialisableTurtle.myId.
static int turtle.SerialisableTurtle.getOurTurtleCount () static
Definition at line 40 of file SerialisableTurtle.java.
References turtle.SerialisableTurtle.ourTurtleCount.
String turtle.SerialisableTurtle.getPenColour ()
Definition at line 68 of file SerialisableTurtle.java.
References turtle.SerialisableTurtle.penColour.
double turtle.SerialisableTurtle.getRotate ()
Definition at line 56 of file SerialisableTurtle.java.
References turtle.SerialisableTurtle.rotate.
double turtle.SerialisableTurtle.getTranslateX ()
Definition at line 48 of file SerialisableTurtle.java.
References turtle.SerialisableTurtle.translateX.
double turtle.SerialisableTurtle.getTranslateY ()
Definition at line 52 of file SerialisableTurtle.java.
References turtle.SerialisableTurtle.translateY.
boolean turtle.SerialisableTurtle.isSelected ()
Definition at line 60 of file SerialisableTurtle.java.
Member Data Documentation
File turtle.SerialisableTurtle.imageFile private
Definition at line 22 of file SerialisableTurtle.java.
Referenced by turtle.SerialisableTurtle.getImageFile().
boolean turtle.SerialisableTurtle.isPenDown private
Definition at line 24 of file SerialisableTurtle.java.
Referenced by turtle.SerialisableTurtle.getIsPenDown().
boolean turtle.SerialisableTurtle.isSelected private
Definition at line 21 of file SerialisableTurtle.java.
List<Line> turtle.SerialisableTurtle.lines private
Definition at line 25 of file SerialisableTurtle.java.
Referenced by turtle.SerialisableTurtle.getLines().
int turtle.SerialisableTurtle.myId private
Definition at line 17 of file SerialisableTurtle.java.
Referenced by turtle.SerialisableTurtle.getMyId().
int turtle.SerialisableTurtle.ourTurtleCount static private
Definition at line 16 of file SerialisableTurtle.java.
Referenced by turtle.SerialisableTurtle.getOurTurtleCount().
String turtle.SerialisableTurtle.penColour private
Definition at line 23 of file SerialisableTurtle.java.
Referenced by turtle.SerialisableTurtle.getPenColour().
double turtle.SerialisableTurtle.rotate private
Definition at line 20 of file SerialisableTurtle.java.
Referenced by turtle.SerialisableTurtle.getRotate().
double turtle.SerialisableTurtle.translateX private
Definition at line 18 of file SerialisableTurtle.java.
Referenced by turtle.SerialisableTurtle.getTranslateX().
double turtle.SerialisableTurtle.translateY private
Definition at line 19 of file SerialisableTurtle.java.
Referenced by turtle.SerialisableTurtle.getTranslateY().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/turtle/SerialisableTurtle.java