slogo_team04: viewcontroller.turtlegrid.TurtleWindowViewController Class Reference
viewcontroller.turtlegrid.TurtleWindowViewController Class Reference
Public Member Functions
TurtleWindowViewController (MainViewController parent)
void passSLogoCommand (String commandKey, String operands)
void toggleGridLines ()
Node getNode ()
void update (MainModel model)
void applyTranslations ()
Static Public Attributes
static final Dimension SIZE
Private Member Functions
void animationSpeedChanged (double newSpeed)
void gridColorChanged ()
void penColorChanged ()
void placeStatusView ()
void placeGridView ()
Private Attributes
MainViewController myParent
BorderPane myPane
TurtleStatusViewController myStatusView
GridViewController myGridView
List< MainModelObserver > myChildObservers
GridButtonBar myGridButtonBar
Detailed Description
View Controller for Grid View (Where drawing and turtle is located on)
Author
Jonathan Tseng
Definition at line 24 of file TurtleWindowViewController.java.
Constructor & Destructor Documentation
viewcontroller.turtlegrid.TurtleWindowViewController.TurtleWindowViewController (MainViewController parent)
Definition at line 37 of file TurtleWindowViewController.java.
References viewcontroller.turtlegrid.TurtleWindowViewController.animationSpeedChanged(), viewcontroller.turtlegrid.GridButtonBar.getAnimationSpeed(), viewcontroller.turtlegrid.TurtleWindowViewController.gridColorChanged(), viewcontroller.turtlegrid.TurtleWindowViewController.penColorChanged(), viewcontroller.turtlegrid.TurtleWindowViewController.placeGridView(), and viewcontroller.turtlegrid.TurtleWindowViewController.placeStatusView().
Member Function Documentation
void viewcontroller.turtlegrid.TurtleWindowViewController.animationSpeedChanged (double newSpeed) private
Definition at line 65 of file TurtleWindowViewController.java.
References viewcontroller.MainViewController.animationSpeedChanged().
Referenced by viewcontroller.turtlegrid.TurtleWindowViewController.TurtleWindowViewController().
void viewcontroller.turtlegrid.TurtleWindowViewController.applyTranslations ()
translate the string using the GUI Reference Library
Implements viewcontroller.ViewController.
Definition at line 106 of file TurtleWindowViewController.java.
Node viewcontroller.turtlegrid.TurtleWindowViewController.getNode ()
returns the Node representing the view for a view controller
Returns
Implements viewcontroller.ViewController.
Definition at line 94 of file TurtleWindowViewController.java.
References viewcontroller.turtlegrid.TurtleWindowViewController.myPane.
Referenced by viewcontroller.MainViewController.placeCommandWindowView(), and viewcontroller.MainViewController.placeTurtleWindowView().
void viewcontroller.turtlegrid.TurtleWindowViewController.gridColorChanged () private
Definition at line 69 of file TurtleWindowViewController.java.
References viewcontroller.turtlegrid.GridButtonBar.getGridColor(), and viewcontroller.MainViewController.gridColorChanged().
Referenced by viewcontroller.turtlegrid.TurtleWindowViewController.TurtleWindowViewController().
void viewcontroller.turtlegrid.TurtleWindowViewController.passSLogoCommand (String commandKey, String operands)
Definition at line 61 of file TurtleWindowViewController.java.
References viewcontroller.MainViewController.passSLogoCommand().
Referenced by viewcontroller.turtlegrid.GridViewController.forwardKeyPressed(), and viewcontroller.turtlegrid.GridViewController.rightKeyPressed().
void viewcontroller.turtlegrid.TurtleWindowViewController.penColorChanged () private
Definition at line 73 of file TurtleWindowViewController.java.
References viewcontroller.turtlegrid.GridButtonBar.getPenColor(), and viewcontroller.MainViewController.penColorChanged().
Referenced by viewcontroller.turtlegrid.TurtleWindowViewController.TurtleWindowViewController().
void viewcontroller.turtlegrid.TurtleWindowViewController.placeGridView () private
Definition at line 83 of file TurtleWindowViewController.java.
References viewcontroller.turtlegrid.GridViewController.getNode().
Referenced by viewcontroller.turtlegrid.TurtleWindowViewController.TurtleWindowViewController().
void viewcontroller.turtlegrid.TurtleWindowViewController.placeStatusView () private
Definition at line 77 of file TurtleWindowViewController.java.
References viewcontroller.turtlegrid.TurtleStatusViewController.getNode().
Referenced by viewcontroller.turtlegrid.TurtleWindowViewController.TurtleWindowViewController().
void viewcontroller.turtlegrid.TurtleWindowViewController.toggleGridLines ()
Definition at line 89 of file TurtleWindowViewController.java.
References viewcontroller.turtlegrid.GridViewController.toggleGridLines().
Referenced by viewcontroller.MainViewController.toggleGridLines().
void viewcontroller.turtlegrid.TurtleWindowViewController.update (MainModel model)
Extract the appropriate data from the model to update the view
Parameters
model - MainModel
Implements viewcontroller.MainModelObserver.
Definition at line 99 of file TurtleWindowViewController.java.
Member Data Documentation
List<MainModelObserver> viewcontroller.turtlegrid.TurtleWindowViewController.myChildObservers private
Definition at line 34 of file TurtleWindowViewController.java.
GridButtonBar viewcontroller.turtlegrid.TurtleWindowViewController.myGridButtonBar private
Definition at line 35 of file TurtleWindowViewController.java.
GridViewController viewcontroller.turtlegrid.TurtleWindowViewController.myGridView private
Definition at line 33 of file TurtleWindowViewController.java.
BorderPane viewcontroller.turtlegrid.TurtleWindowViewController.myPane private
Definition at line 31 of file TurtleWindowViewController.java.
Referenced by viewcontroller.turtlegrid.TurtleWindowViewController.getNode().
MainViewController viewcontroller.turtlegrid.TurtleWindowViewController.myParent private
Definition at line 30 of file TurtleWindowViewController.java.
TurtleStatusViewController viewcontroller.turtlegrid.TurtleWindowViewController.myStatusView private
Definition at line 32 of file TurtleWindowViewController.java.
final Dimension viewcontroller.turtlegrid.TurtleWindowViewController.SIZE static
Initial value:
= new Dimension(
            Main.SIZE.width / 2 * 9 / 10, Main.SIZE.height * 9 / 10)
Definition at line 27 of file TurtleWindowViewController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/viewcontroller/turtlegrid/TurtleWindowViewController.java