slogo_team04: application.PenFormResult Class Reference
application.PenFormResult Class Reference
Public Member Functions
PenFormResult (String penWidth, String penUp, String penStroke)
double getPenWidth ()
boolean getPenUp ()
List< Double > getPenDash ()
Private Attributes
double myPenWidth
boolean myPenUp
List< Double > myPenDash
Detailed Description
result from submitting a pen form
Author
Jonathan Tseng
Definition at line 13 of file PenFormResult.java.
Constructor & Destructor Documentation
application.PenFormResult.PenFormResult (String penWidth, String penUp, String penStroke)
Definition at line 19 of file PenFormResult.java.
References viewcontroller.GUIReferenceLibrary.getStringTranslation(), application.PenForm.PEN_DASH_KEY, application.PenForm.PEN_DOT_KEY, and application.PenForm.PEN_UP_KEY.
Member Function Documentation
List<Double> application.PenFormResult.getPenDash ()
Definition at line 53 of file PenFormResult.java.
References application.PenFormResult.myPenDash.
Referenced by model.MainModel.updatePen().
boolean application.PenFormResult.getPenUp ()
Definition at line 49 of file PenFormResult.java.
References application.PenFormResult.myPenUp.
Referenced by model.MainModel.updatePen().
double application.PenFormResult.getPenWidth ()
Definition at line 45 of file PenFormResult.java.
References application.PenFormResult.myPenWidth.
Referenced by model.MainModel.updatePen().
Member Data Documentation
List<Double> application.PenFormResult.myPenDash private
Definition at line 17 of file PenFormResult.java.
Referenced by application.PenFormResult.getPenDash().
boolean application.PenFormResult.myPenUp private
Definition at line 16 of file PenFormResult.java.
Referenced by application.PenFormResult.getPenUp().
double application.PenFormResult.myPenWidth private
Definition at line 15 of file PenFormResult.java.
Referenced by application.PenFormResult.getPenWidth().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/application/PenFormResult.java