slogo_team04: interpreter.expression.DisplayExpression Class Reference
interpreter.expression.DisplayExpression Class Reference abstract
Public Member Functions
DisplayExpression ()
void setNumArgs (int value)
int getNumArgs ()
void setValue (String value)
String getValue ()
void loadArguments (Deque< SLogoExpression > args) throws SLogoParsingException, NullPointerException
void loadLibrary (CommandReferenceLibrary library)
void loadModel (MainModel model)
SLogoResult evaluate ()
Protected Member Functions
SLogoResult applyOperatorAndMerge (Deque< SLogoResult > results)
Protected Attributes
Deque< SLogoExpression > myArguments
Deque< Double > valuesToCompare
int myNumArgs
CommandReferenceLibrary myLibrary
MainModel myModel
String myValue
Detailed Description
superclass of SLogoExpressions for Display
Author
Abhishek B
Definition at line 17 of file DisplayExpression.java.
Constructor & Destructor Documentation
interpreter.expression.DisplayExpression.DisplayExpression ()
Definition at line 27 of file DisplayExpression.java.
Member Function Documentation
SLogoResult interpreter.expression.DisplayExpression.applyOperatorAndMerge (Deque< SLogoResult > results) protected
Definition at line 79 of file DisplayExpression.java.
References interpreter.result.SLogoResult.getTransition(), and interpreter.result.SLogoResult.setValue().
Referenced by interpreter.expression.DisplayExpression.evaluate().
SLogoResult interpreter.expression.DisplayExpression.evaluate ()
evaluates the expression and returns an SLogoResult
Returns
Exceptions
SLogoParsingException
Implements interpreter.expression.SLogoExpression.
Definition at line 71 of file DisplayExpression.java.
References interpreter.expression.DisplayExpression.applyOperatorAndMerge().
int interpreter.expression.DisplayExpression.getNumArgs ()
Gets the number of arguments for the expression.
Returns
Implements interpreter.expression.SLogoExpression.
Definition at line 37 of file DisplayExpression.java.
References interpreter.expression.DisplayExpression.myNumArgs.
String interpreter.expression.DisplayExpression.getValue ()
Gets the String value of the expression
Returns
value
Implements interpreter.expression.SLogoExpression.
Definition at line 47 of file DisplayExpression.java.
References interpreter.expression.DisplayExpression.myValue.
void interpreter.expression.DisplayExpression.loadArguments (Deque< SLogoExpression > args) throws SLogoParsingException, NullPointerException
loads the list of expressions as arguments for the expression
Parameters
args
Exceptions
NullPointerException
SLogoParsingException
Implements interpreter.expression.SLogoExpression.
Definition at line 52 of file DisplayExpression.java.
References interpreter.expression.DisplayExpression.myNumArgs.
void interpreter.expression.DisplayExpression.loadLibrary (CommandReferenceLibrary library)
Sets the library from the CommandReferenceLibrary
Parameters
library
Implements interpreter.expression.SLogoExpression.
Definition at line 61 of file DisplayExpression.java.
void interpreter.expression.DisplayExpression.loadModel (MainModel model)
Loads the model
Parameters
mode
Implements interpreter.expression.SLogoExpression.
Definition at line 66 of file DisplayExpression.java.
void interpreter.expression.DisplayExpression.setNumArgs (int value)
Sets the number of arguments
Parameters
value
Implements interpreter.expression.SLogoExpression.
Definition at line 32 of file DisplayExpression.java.
void interpreter.expression.DisplayExpression.setValue (String value)
Sets the value of the expression
Parameters
value
Implements interpreter.expression.SLogoExpression.
Definition at line 42 of file DisplayExpression.java.
Member Data Documentation
Deque<SLogoExpression> interpreter.expression.DisplayExpression.myArguments protected
Definition at line 19 of file DisplayExpression.java.
CommandReferenceLibrary interpreter.expression.DisplayExpression.myLibrary protected
Definition at line 23 of file DisplayExpression.java.
MainModel interpreter.expression.DisplayExpression.myModel protected
Definition at line 24 of file DisplayExpression.java.
int interpreter.expression.DisplayExpression.myNumArgs protected
Definition at line 21 of file DisplayExpression.java.
Referenced by interpreter.expression.DisplayExpression.getNumArgs(), and interpreter.expression.DisplayExpression.loadArguments().
String interpreter.expression.DisplayExpression.myValue protected
Definition at line 25 of file DisplayExpression.java.
Referenced by interpreter.expression.DisplayExpression.getValue().
Deque<Double> interpreter.expression.DisplayExpression.valuesToCompare protected
Definition at line 20 of file DisplayExpression.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/interpreter/expression/DisplayExpression.java