slogo_team04: turtle.TurtleListHistory Class Reference
turtle.TurtleListHistory Class Reference
Public Member Functions
TurtleListHistory ()
void updateList (Collection< Turtle > movedTurtles)
TurtleHistoryState undo ()
TurtleHistoryState redo ()
Private Attributes
List< Set< Turtle > > myMovedTurtlesHistory
int myIndex
Detailed Description
history for the list of turtles used for undo/redo
Author
Jonathan Tseng
Definition at line 17 of file TurtleListHistory.java.
Constructor & Destructor Documentation
turtle.TurtleListHistory.TurtleListHistory ()
Definition at line 22 of file TurtleListHistory.java.
Member Function Documentation
TurtleHistoryState turtle.TurtleListHistory.redo ()
Definition at line 55 of file TurtleListHistory.java.
References turtle.TurtleHistoryState.getAnimation(), and turtle.TurtleHistoryState.getLines().
Referenced by model.MainModel.redoClicked().
TurtleHistoryState turtle.TurtleListHistory.undo ()
Definition at line 37 of file TurtleListHistory.java.
References turtle.TurtleHistoryState.getAnimation(), and turtle.TurtleHistoryState.getLines().
Referenced by model.MainModel.undoClicked().
void turtle.TurtleListHistory.updateList (Collection< Turtle > movedTurtles)
Definition at line 27 of file TurtleListHistory.java.
References turtle.TurtleListHistory.myIndex.
Referenced by model.MainModel.setMyAnimation().
Member Data Documentation
int turtle.TurtleListHistory.myIndex private
Definition at line 20 of file TurtleListHistory.java.
Referenced by turtle.TurtleListHistory.updateList().
List<Set<Turtle> > turtle.TurtleListHistory.myMovedTurtlesHistory private
Definition at line 19 of file TurtleListHistory.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/turtle/TurtleListHistory.java