slogo_team04: application.PenForm Class Reference
application.PenForm Class Reference
Public Member Functions
PenForm ()
PenFormResult getResult ()
Public Member Functions inherited from application.Form
Form (String title)
void createFormBox ()
void addFormElement (FormElement formElement)
void show ()
void close ()
void setOnSubmit (EventHandler< ActionEvent > event)
Static Public Attributes
static final String PEN_SETTINGS_KEY = "PenSettings"
static final String PEN_WIDTH_KEY = "PenWidth"
static final String PEN_UP_KEY = "PenUp"
static final String PEN_DOWN_KEY = "PenDown"
static final String PEN_DASH_KEY = "PenDash"
static final String PEN_SOLID_KEY = "PenSolid"
static final String PEN_DOT_KEY = "PenDot"
Package Attributes
NumberInputFormElement myPenWidthFormElement
ToggleFormElement myPenUpToggleFormElement
DropDownFormElement myPenStyleFormElement
Private Member Functions
void initializePenStyles ()
Private Attributes
List< String > myPenStyles
Detailed Description
form for setting pen properties
Author
Jonathan Tseng
Definition at line 13 of file PenForm.java.
Constructor & Destructor Documentation
application.PenForm.PenForm ()
Definition at line 28 of file PenForm.java.
References application.Form.addFormElement(), viewcontroller.GUIReferenceLibrary.getStringTranslation(), application.PenForm.initializePenStyles(), application.DropDownFormElement.setInitialValue(), application.NumberInputFormElement.setInitialValue(), and application.ToggleFormElement.setInitialValue().
Member Function Documentation
PenFormResult application.PenForm.getResult ()
Definition at line 45 of file PenForm.java.
References application.DropDownFormElement.getSelectedValue(), application.NumberInputFormElement.getSelectedValue(), and application.ToggleFormElement.getSelectedValue().
Referenced by model.MainModel.updatePen().
void application.PenForm.initializePenStyles () private
Definition at line 52 of file PenForm.java.
References viewcontroller.GUIReferenceLibrary.getStringTranslation().
Referenced by application.PenForm.PenForm().
Member Data Documentation
DropDownFormElement application.PenForm.myPenStyleFormElement package
Definition at line 26 of file PenForm.java.
List<String> application.PenForm.myPenStyles private
Definition at line 23 of file PenForm.java.
ToggleFormElement application.PenForm.myPenUpToggleFormElement package
Definition at line 25 of file PenForm.java.
NumberInputFormElement application.PenForm.myPenWidthFormElement package
Definition at line 24 of file PenForm.java.
final String application.PenForm.PEN_DASH_KEY = "PenDash" static
Definition at line 19 of file PenForm.java.
Referenced by application.PenFormResult.PenFormResult().
final String application.PenForm.PEN_DOT_KEY = "PenDot" static
Definition at line 21 of file PenForm.java.
Referenced by application.PenFormResult.PenFormResult().
final String application.PenForm.PEN_DOWN_KEY = "PenDown" static
Definition at line 18 of file PenForm.java.
final String application.PenForm.PEN_SETTINGS_KEY = "PenSettings" static
Definition at line 15 of file PenForm.java.
final String application.PenForm.PEN_SOLID_KEY = "PenSolid" static
Definition at line 20 of file PenForm.java.
final String application.PenForm.PEN_UP_KEY = "PenUp" static
Definition at line 17 of file PenForm.java.
Referenced by application.PenFormResult.PenFormResult().
final String application.PenForm.PEN_WIDTH_KEY = "PenWidth" static
Definition at line 16 of file PenForm.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/application/PenForm.java