slogo_team04: model.SerialisableModel Class Reference
model.SerialisableModel Class Reference
Public Member Functions
SerialisableModel (MainModel model)
String getMyLanguage ()
CommandHistoryModel getMyCommandHistoryModel ()
UserDefinedCommandsModel getMyUserDefinedMethodsModel ()
UserDefinedVariablesModel getMyUserDefinedVariablesModel ()
String getBackGroundColorName ()
Private Attributes
SLogoResult mySLogoResult
String myLanguage
CommandHistoryModel myCommandHistoryModel
UserDefinedCommandsModel myUserDefinedMethodsModel
UserDefinedVariablesModel myUserDefinedVariablesModel
String backGroundColorName
Detailed Description
Serialisable Version of the MainModel which doesn't hold the non serialisable javafx components
Author
Tanaka Jimha
Definition at line 10 of file SerialisableModel.java.
Constructor & Destructor Documentation
model.SerialisableModel.SerialisableModel (MainModel model)
Definition at line 19 of file SerialisableModel.java.
References model.MainModel.getBackgroundColorName(), model.MainModel.getCommandHistory(), model.MainModel.getLanguage(), model.MainModel.getUserDefinedMethods(), and model.MainModel.getUserDefinedVariables().
Member Function Documentation
String model.SerialisableModel.getBackGroundColorName ()
Definition at line 46 of file SerialisableModel.java.
References model.SerialisableModel.backGroundColorName.
Referenced by model.Deserialiser.deserialise().
CommandHistoryModel model.SerialisableModel.getMyCommandHistoryModel ()
Definition at line 36 of file SerialisableModel.java.
References model.SerialisableModel.myCommandHistoryModel.
Referenced by model.Deserialiser.deserialise().
String model.SerialisableModel.getMyLanguage ()
Definition at line 33 of file SerialisableModel.java.
References model.SerialisableModel.myLanguage.
Referenced by model.Deserialiser.deserialise().
UserDefinedCommandsModel model.SerialisableModel.getMyUserDefinedMethodsModel ()
Definition at line 39 of file SerialisableModel.java.
References model.SerialisableModel.myUserDefinedMethodsModel.
Referenced by model.Deserialiser.deserialise().
UserDefinedVariablesModel model.SerialisableModel.getMyUserDefinedVariablesModel ()
Definition at line 42 of file SerialisableModel.java.
References model.SerialisableModel.myUserDefinedVariablesModel.
Referenced by model.Deserialiser.deserialise().
Member Data Documentation
String model.SerialisableModel.backGroundColorName private
Definition at line 17 of file SerialisableModel.java.
Referenced by model.SerialisableModel.getBackGroundColorName().
CommandHistoryModel model.SerialisableModel.myCommandHistoryModel private
Definition at line 14 of file SerialisableModel.java.
Referenced by model.SerialisableModel.getMyCommandHistoryModel().
String model.SerialisableModel.myLanguage private
Definition at line 13 of file SerialisableModel.java.
Referenced by model.SerialisableModel.getMyLanguage().
SLogoResult model.SerialisableModel.mySLogoResult private
Definition at line 12 of file SerialisableModel.java.
UserDefinedCommandsModel model.SerialisableModel.myUserDefinedMethodsModel private
Definition at line 15 of file SerialisableModel.java.
Referenced by model.SerialisableModel.getMyUserDefinedMethodsModel().
UserDefinedVariablesModel model.SerialisableModel.myUserDefinedVariablesModel private
Definition at line 16 of file SerialisableModel.java.
Referenced by model.SerialisableModel.getMyUserDefinedVariablesModel().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/model/SerialisableModel.java