slogo_team04: viewcontroller.MainViewController Class Reference
viewcontroller.MainViewController Class Reference
Public Member Functions
MainViewController (MainModel mainModel)
void passSLogoCommand (String command)
void passSLogoCommand (String commandKey, String operands)
void loadScript (String script)
void toggleGridLines ()
void gridColorChanged (Color color)
void penColorChanged (Color color)
void animationSpeedChanged (double speed)
CommandWindowContainerViewController getCommandWindowContainer ()
Node getNode ()
void update (MainModel model)
void applyTranslations ()
Private Member Functions
void placeTurtleWindowView ()
void placeCommandWindowView ()
Private Attributes
MainModel myMainModel
BorderPane myPane
TurtleWindowViewController myTurtleWindow
CommandWindowContainerViewController myCommandWindowContainer
List< MainModelObserver > myChildObservers
Static Private Attributes
static final Insets GRID_MARGIN = new Insets(15)
Detailed Description
view controller for main view–contains rest of views and places them accordingly
Author
Jonathan Tseng
Definition at line 22 of file MainViewController.java.
Constructor & Destructor Documentation
viewcontroller.MainViewController.MainViewController (MainModel mainModel)
Definition at line 32 of file MainViewController.java.
References model.MainModel.attachObserver(), viewcontroller.MainViewController.placeCommandWindowView(), and viewcontroller.MainViewController.placeTurtleWindowView().
Member Function Documentation
void viewcontroller.MainViewController.animationSpeedChanged (double speed)
Definition at line 65 of file MainViewController.java.
References model.MainModel.updateAnimationSpeed().
Referenced by viewcontroller.turtlegrid.TurtleWindowViewController.animationSpeedChanged().
void viewcontroller.MainViewController.applyTranslations ()
translate the string using the GUI Reference Library
Implements viewcontroller.ViewController.
Definition at line 109 of file MainViewController.java.
CommandWindowContainerViewController viewcontroller.MainViewController.getCommandWindowContainer ()
Definition at line 92 of file MainViewController.java.
References viewcontroller.MainViewController.myCommandWindowContainer.
Referenced by unittest.CommandPromptTextTest.testTransferOfString().
Node viewcontroller.MainViewController.getNode ()
returns the Node representing the view for a view controller
Returns
Implements viewcontroller.ViewController.
Definition at line 97 of file MainViewController.java.
References viewcontroller.MainViewController.myPane.
Referenced by viewcontroller.View.addWorkspace().
void viewcontroller.MainViewController.gridColorChanged (Color color)
Definition at line 57 of file MainViewController.java.
References model.MainModel.setBackgroundColor().
Referenced by viewcontroller.turtlegrid.TurtleWindowViewController.gridColorChanged().
void viewcontroller.MainViewController.loadScript (String script)
Definition at line 49 of file MainViewController.java.
References viewcontroller.commands.CommandWindowContainerViewController.loadScript().
Referenced by viewcontroller.View.loadFile().
void viewcontroller.MainViewController.passSLogoCommand (String command)
Definition at line 41 of file MainViewController.java.
References model.MainModel.interpretSLogoCommand().
Referenced by viewcontroller.turtlegrid.TurtleWindowViewController.passSLogoCommand(), and viewcontroller.commands.CommandWindowContainerViewController.passSLogoCommand().
void viewcontroller.MainViewController.passSLogoCommand (String commandKey, String operands)
Definition at line 45 of file MainViewController.java.
References model.MainModel.interpretSLogoCommand().
void viewcontroller.MainViewController.penColorChanged (Color color)
Definition at line 61 of file MainViewController.java.
References model.MainModel.updatePenColor().
Referenced by viewcontroller.turtlegrid.TurtleWindowViewController.penColorChanged().
void viewcontroller.MainViewController.placeCommandWindowView () private
Sets up right side of the screen - the Command Window related panes
Definition at line 84 of file MainViewController.java.
References viewcontroller.turtlegrid.TurtleWindowViewController.getNode(), viewcontroller.commands.CommandWindowContainerViewController.getNode(), and viewcontroller.MainViewController.GRID_MARGIN.
Referenced by viewcontroller.MainViewController.MainViewController().
void viewcontroller.MainViewController.placeTurtleWindowView () private
Sets up left side of the screen - the Turtle Window/Grid related animations
Definition at line 73 of file MainViewController.java.
References viewcontroller.turtlegrid.TurtleWindowViewController.getNode(), and viewcontroller.MainViewController.GRID_MARGIN.
Referenced by viewcontroller.MainViewController.MainViewController().
void viewcontroller.MainViewController.toggleGridLines ()
Definition at line 53 of file MainViewController.java.
References viewcontroller.turtlegrid.TurtleWindowViewController.toggleGridLines().
Referenced by viewcontroller.View.toggleGridLines().
void viewcontroller.MainViewController.update (MainModel model)
Extract the appropriate data from the model to update the view
Parameters
model - MainModel
Implements viewcontroller.MainModelObserver.
Definition at line 102 of file MainViewController.java.
Member Data Documentation
final Insets viewcontroller.MainViewController.GRID_MARGIN = new Insets(15) static private
Definition at line 24 of file MainViewController.java.
Referenced by viewcontroller.MainViewController.placeCommandWindowView(), and viewcontroller.MainViewController.placeTurtleWindowView().
List<MainModelObserver> viewcontroller.MainViewController.myChildObservers private
Definition at line 30 of file MainViewController.java.
CommandWindowContainerViewController viewcontroller.MainViewController.myCommandWindowContainer private
Definition at line 29 of file MainViewController.java.
Referenced by viewcontroller.MainViewController.getCommandWindowContainer().
MainModel viewcontroller.MainViewController.myMainModel private
Definition at line 26 of file MainViewController.java.
BorderPane viewcontroller.MainViewController.myPane private
Definition at line 27 of file MainViewController.java.
Referenced by viewcontroller.MainViewController.getNode().
TurtleWindowViewController viewcontroller.MainViewController.myTurtleWindow private
Definition at line 28 of file MainViewController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/viewcontroller/MainViewController.java