slogo_team04: interpreter.SLogoResultMerger Class Reference
interpreter.SLogoResultMerger Class Reference
Public Member Functions
SLogoResultMerger ()
SLogoResultMerger (Deque< SLogoResult > results)
Protected Member Functions
void append (SLogoResult result)
SLogoResult mergeAndReturn ()
Private Attributes
Deque< SLogoResult > myResultsToMerge
Detailed Description
Merges Expressions from a High Level in the Interpreter
Author
Will Chang
Definition at line 13 of file SLogoResultMerger.java.
Constructor & Destructor Documentation
interpreter.SLogoResultMerger.SLogoResultMerger ()
Constructors
Definition at line 19 of file SLogoResultMerger.java.
interpreter.SLogoResultMerger.SLogoResultMerger (Deque< SLogoResult > results)
Definition at line 23 of file SLogoResultMerger.java.
Member Function Documentation
void interpreter.SLogoResultMerger.append (SLogoResult result) protected
Adds an SLogoResult to be merged
Parameters
result to be merged
Definition at line 31 of file SLogoResultMerger.java.
Referenced by interpreter.ExpressionEvaluator.evaluateExpressionsAndMerge().
SLogoResult interpreter.SLogoResultMerger.mergeAndReturn () protected
Merges all SLogoResults
Returns
one SLogo result containing all changes
Definition at line 39 of file SLogoResultMerger.java.
References interpreter.result.SLogoResult.getTransition(), interpreter.result.SLogoResult.getValue(), and interpreter.result.SLogoResult.setValue().
Referenced by interpreter.ExpressionEvaluator.evaluateExpressionsAndMerge().
Member Data Documentation
Deque<SLogoResult> interpreter.SLogoResultMerger.myResultsToMerge private
Definition at line 15 of file SLogoResultMerger.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/interpreter/SLogoResultMerger.java