slogo_team04: viewcontroller.View Class Reference
viewcontroller.View Class Reference
Public Member Functions
View (Stage stage, String language)
void addNewWorkspace ()
void editPenSettings ()
void saveWorkspace ()
void loadWorkspace ()
void init ()
void toggleGridLines ()
void undoClicked ()
void redoClicked ()
void addTurtleClicked ()
void changeTurtleImages ()
void loadFile ()
String readFile (File file) throws IOException
void showHelp ()
Scene getScene ()
Static Public Attributes
static final Color BACKGROUND_COLOR = Color.DARKSLATEGREY
Private Member Functions
void shit (PenForm penForm)
void showMessage (String message)
void noCurrentWorkspace ()
void addWorkspace (Workspace workspace)
void loadSerialisedWorkspace (File file)
void initializeTabPane ()
void tabChanged (ObservableValue<?extends Tab > observable, Tab oldTab, Tab newTab)
void placeMenuBar ()
Private Attributes
Stage myStage
Scene myScene
BorderPane myPane
TabPane myTabPane
List< Workspace > myWorkspaces
Workspace myCurrentWorkspace
SLogoMenuBar myMenuBar
String myLanguage
final String Title = "Title"
final String Workspace = "Workspace"
Detailed Description
Overall main view that can has menu bar and tabbed view that can hold multiple workspaces
Author
Jonathan Tseng
Definition at line 38 of file View.java.
Constructor & Destructor Documentation
viewcontroller.View.View (Stage stage, String language)
Definition at line 57 of file View.java.
References viewcontroller.View.addNewWorkspace(), viewcontroller.GUIReferenceLibrary.getStringTranslation(), viewcontroller.View.initializeTabPane(), viewcontroller.View.placeMenuBar(), viewcontroller.GUIReferenceLibrary.setGUIReference(), and application.Main.SIZE.
Member Function Documentation
void viewcontroller.View.addNewWorkspace ()
Definition at line 73 of file View.java.
References viewcontroller.View.addWorkspace(), and viewcontroller.View.Workspace.
Referenced by viewcontroller.SLogoMenuBar.initializeFileMenu(), and viewcontroller.View.View().
void viewcontroller.View.addTurtleClicked ()
Definition at line 174 of file View.java.
References model.MainModel.addTurtle(), viewcontroller.Workspace.getMainModel(), and viewcontroller.View.noCurrentWorkspace().
Referenced by viewcontroller.SLogoMenuBar.initializeGridMenu().
void viewcontroller.View.addWorkspace (Workspace workspace) private
Definition at line 98 of file View.java.
References viewcontroller.MainViewController.getNode(), viewcontroller.GUIReferenceLibrary.getStringTranslation(), and viewcontroller.Workspace.getViewController().
Referenced by viewcontroller.View.addNewWorkspace(), and viewcontroller.View.loadSerialisedWorkspace().
void viewcontroller.View.changeTurtleImages ()
Definition at line 182 of file View.java.
References model.MainModel.changeTurtleImages(), viewcontroller.Workspace.getMainModel(), and viewcontroller.View.noCurrentWorkspace().
Referenced by viewcontroller.SLogoMenuBar.initializeGridMenu().
void viewcontroller.View.editPenSettings ()
Definition at line 78 of file View.java.
References application.Form.setOnSubmit(), viewcontroller.View.shit(), and application.Form.show().
Referenced by viewcontroller.SLogoMenuBar.initializeGridMenu().
Scene viewcontroller.View.getScene ()
Definition at line 225 of file View.java.
References viewcontroller.View.myScene.
void viewcontroller.View.init ()
Definition at line 146 of file View.java.
Referenced by application.StartMenu.createOkayButton().
void viewcontroller.View.initializeTabPane () private
Definition at line 229 of file View.java.
References viewcontroller.View.tabChanged().
Referenced by viewcontroller.View.View().
void viewcontroller.View.loadFile ()
Definition at line 198 of file View.java.
References viewcontroller.Workspace.getViewController(), viewcontroller.MainViewController.loadScript(), viewcontroller.View.noCurrentWorkspace(), viewcontroller.View.readFile(), and viewcontroller.View.showMessage().
Referenced by viewcontroller.SLogoMenuBar.initializeFileMenu().
void viewcontroller.View.loadSerialisedWorkspace (File file) private
Definition at line 109 of file View.java.
References viewcontroller.View.addWorkspace(), model.Deserialiser.deserialise(), viewcontroller.View.showMessage(), and viewcontroller.View.Workspace.
Referenced by viewcontroller.View.loadWorkspace().
void viewcontroller.View.loadWorkspace ()
Definition at line 135 of file View.java.
References viewcontroller.View.loadSerialisedWorkspace().
Referenced by viewcontroller.SLogoMenuBar.initializeFileMenu().
void viewcontroller.View.noCurrentWorkspace () private
Definition at line 94 of file View.java.
References viewcontroller.View.showMessage().
Referenced by viewcontroller.View.addTurtleClicked(), viewcontroller.View.changeTurtleImages(), viewcontroller.View.loadFile(), viewcontroller.View.redoClicked(), viewcontroller.View.saveWorkspace(), viewcontroller.View.toggleGridLines(), and viewcontroller.View.undoClicked().
void viewcontroller.View.placeMenuBar () private
Definition at line 244 of file View.java.
Referenced by viewcontroller.View.View().
String viewcontroller.View.readFile (File file) throws IOException
Definition at line 215 of file View.java.
Referenced by viewcontroller.View.loadFile().
void viewcontroller.View.redoClicked ()
Definition at line 166 of file View.java.
References viewcontroller.Workspace.getMainModel(), viewcontroller.View.noCurrentWorkspace(), and model.MainModel.redoClicked().
Referenced by viewcontroller.SLogoMenuBar.initializeEditMenu().
void viewcontroller.View.saveWorkspace ()
Definition at line 120 of file View.java.
References viewcontroller.Workspace.getMainModel(), viewcontroller.View.noCurrentWorkspace(), and model.Serialiser.serialise().
Referenced by viewcontroller.SLogoMenuBar.initializeFileMenu().
void viewcontroller.View.shit (PenForm penForm) private
Definition at line 84 of file View.java.
References application.Form.close(), viewcontroller.Workspace.getMainModel(), and model.MainModel.updatePen().
Referenced by viewcontroller.View.editPenSettings().
void viewcontroller.View.showHelp ()
Definition at line 220 of file View.java.
References viewcontroller.HelpDialogBox.show().
Referenced by viewcontroller.SLogoMenuBar.initializeFileMenu().
void viewcontroller.View.showMessage (String message) private
Definition at line 89 of file View.java.
References application.MessageBox.show().
Referenced by viewcontroller.View.loadFile(), viewcontroller.View.loadSerialisedWorkspace(), and viewcontroller.View.noCurrentWorkspace().
void viewcontroller.View.tabChanged (ObservableValue<?extends Tab > observable, Tab oldTab, Tab newTab) private
Definition at line 236 of file View.java.
Referenced by viewcontroller.View.initializeTabPane().
void viewcontroller.View.toggleGridLines ()
Definition at line 150 of file View.java.
References viewcontroller.Workspace.getViewController(), viewcontroller.View.noCurrentWorkspace(), and viewcontroller.MainViewController.toggleGridLines().
Referenced by viewcontroller.SLogoMenuBar.initializeGridMenu().
void viewcontroller.View.undoClicked ()
Definition at line 158 of file View.java.
References viewcontroller.Workspace.getMainModel(), viewcontroller.View.noCurrentWorkspace(), and model.MainModel.undoClicked().
Referenced by viewcontroller.SLogoMenuBar.initializeEditMenu().
Member Data Documentation
final Color viewcontroller.View.BACKGROUND_COLOR = Color.DARKSLATEGREY static
Definition at line 40 of file View.java.
Referenced by viewcontroller.turtlegrid.GridViewController.createBackground().
Workspace viewcontroller.View.myCurrentWorkspace private
Definition at line 48 of file View.java.
String viewcontroller.View.myLanguage private
Definition at line 52 of file View.java.
SLogoMenuBar viewcontroller.View.myMenuBar private
Definition at line 50 of file View.java.
BorderPane viewcontroller.View.myPane private
Definition at line 44 of file View.java.
Scene viewcontroller.View.myScene private
Definition at line 43 of file View.java.
Referenced by viewcontroller.View.getScene().
Stage viewcontroller.View.myStage private
Definition at line 42 of file View.java.
TabPane viewcontroller.View.myTabPane private
Definition at line 45 of file View.java.
List<Workspace> viewcontroller.View.myWorkspaces private
Definition at line 47 of file View.java.
final String viewcontroller.View.Title = "Title" private
Definition at line 54 of file View.java.
final String viewcontroller.View.Workspace = "Workspace" private
Definition at line 55 of file View.java.
Referenced by viewcontroller.View.addNewWorkspace(), and viewcontroller.View.loadSerialisedWorkspace().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/viewcontroller/View.java