slogo_team04: turtle.draw.MoveTransition Class Reference
turtle.draw.MoveTransition Class Reference
Public Member Functions
void setTurtle (Turtle turtle)
Public Member Functions inherited from turtle.draw.LinearTransition
void setDistance (double distance)
Public Member Functions inherited from turtle.draw.SLogoTransition
void setTurtle (Turtle turtle)
Protected Member Functions
void setStartPoint ()
void interpolateChanges (double frac)
void performWrappingChanges (Point2D newStartPoint, double frac)
Protected Member Functions inherited from turtle.draw.LinearTransition
LinearTransition ()
void interpolate (double frac)
abstract void interpolateChanges (double frac)
abstract void performWrappingChanges (Point2D newStartPoint, double frac)
void setStartPoint (double x, double y)
abstract void setStartPoint ()
Point2D checkWrapping ()
Protected Member Functions inherited from turtle.draw.SLogoTransition
SLogoTransition ()
Additional Inherited Members
Protected Attributes inherited from turtle.draw.LinearTransition
double myStartX
double myStartY
double myX
double myY
double myDistance
double myDoneFrac
boolean myWrappingOccurred
Protected Attributes inherited from turtle.draw.SLogoTransition
Turtle myTurtle
Detailed Description
animation for a turtle moving forward/backward
Author
Jonathan Tseng
Definition at line 11 of file MoveTransition.java.
Member Function Documentation
void turtle.draw.MoveTransition.interpolateChanges (double frac) protected
Definition at line 25 of file MoveTransition.java.
References turtle.Turtle.getTurtle(), turtle.draw.LinearTransition.myDoneFrac, turtle.draw.LinearTransition.myStartX, turtle.draw.LinearTransition.myStartY, turtle.draw.SLogoTransition.myTurtle, turtle.draw.LinearTransition.myX, and turtle.draw.LinearTransition.myY.
void turtle.draw.MoveTransition.performWrappingChanges (Point2D newStartPoint, double frac) protected
Definition at line 31 of file MoveTransition.java.
References turtle.draw.LinearTransition.myDoneFrac, turtle.draw.LinearTransition.myX, turtle.draw.LinearTransition.myY, and turtle.draw.MoveTransition.setStartPoint().
void turtle.draw.MoveTransition.setStartPoint () protected
Definition at line 20 of file MoveTransition.java.
References turtle.Turtle.getTurtle(), and turtle.draw.SLogoTransition.myTurtle.
Referenced by turtle.draw.MoveTransition.performWrappingChanges(), and turtle.draw.MoveTransition.setTurtle().
void turtle.draw.MoveTransition.setTurtle (Turtle turtle)
Definition at line 14 of file MoveTransition.java.
References turtle.draw.MoveTransition.setStartPoint().
Referenced by turtle.draw.TransitionFactory.createForwardTransition().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/turtle/draw/MoveTransition.java