slogo_team04: interpreter.Interpreter Class Reference
interpreter.Interpreter Class Reference
Public Member Functions
Interpreter (MainModel model)
SLogoResult interpret (String input)
void setLanguage (String language)
CommandReferenceLibrary getCommandReferenceLibrary ()
Private Attributes
Parser myParser
ExpressionEvaluator myEvaluator
CommandReferenceLibrary myLibrary
MainModel myModel
Detailed Description
Interprets and processes user input, sending results to the model
Author
Will Chang
Definition at line 17 of file Interpreter.java.
Constructor & Destructor Documentation
interpreter.Interpreter.Interpreter (MainModel model)
Constructor
Definition at line 27 of file Interpreter.java.
References model.MainModel.getLanguage(), model.MainModel.getUserDefinedMethods(), and model.MainModel.getUserDefinedVariables().
Member Function Documentation
CommandReferenceLibrary interpreter.Interpreter.getCommandReferenceLibrary ()
Gets the Library
Returns
myCommandReferenceLibrary
Definition at line 63 of file Interpreter.java.
References interpreter.Interpreter.myLibrary.
Referenced by model.MainModel.interpretSLogoCommand().
SLogoResult interpreter.Interpreter.interpret (String input)
Interprets user input, parses into SLogoExpressions, and returns an SLogo result
Parameters
command
Returns
Definition at line 41 of file Interpreter.java.
References interpreter.ExpressionEvaluator.evaluateExpressionsAndMerge(), and interpreter.Parser.parseSLogoExpression().
Referenced by test.MathExpressionTester.arcTanTest(), model.MainModel.interpretSLogoCommand(), and test.MathExpressionTester.sumTest().
void interpreter.Interpreter.setLanguage (String language)
Set the language
Parameters
language
Definition at line 55 of file Interpreter.java.
References interpreter.CommandReferenceLibrary.setLanguageAndReferences().
Member Data Documentation
ExpressionEvaluator interpreter.Interpreter.myEvaluator private
Definition at line 20 of file Interpreter.java.
CommandReferenceLibrary interpreter.Interpreter.myLibrary private
Definition at line 21 of file Interpreter.java.
Referenced by interpreter.Interpreter.getCommandReferenceLibrary().
MainModel interpreter.Interpreter.myModel private
Definition at line 22 of file Interpreter.java.
Parser interpreter.Interpreter.myParser private
Definition at line 19 of file Interpreter.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/interpreter/Interpreter.java