slogo_team04: viewcontroller.commands.CommandWindowViewController Class Reference
viewcontroller.commands.CommandWindowViewController Class Reference abstract
Public Member Functions
CommandWindowViewController (int width, int height)
Public Member Functions inherited from viewcontroller.ViewController
Node getNode ()
void applyTranslations ()
Protected Member Functions
void setTitle (String titleText)
Protected Attributes
BorderPane myPane
VBox myCommandWindowVerticalBox
Label myTitleLabel
Dimension SIZE = new Dimension()
Private Member Functions
void addStyleSheets ()
Private Attributes
final String PANE_KEY = "pane"
final String TEXT_KEY = "text"
final String VBOX_KEY = "vbox"
Detailed Description
Abstract class for command window units Sets up the BorderPane, overall VBox for ViewController elements, TitleLabel, and the preferred size for this node.
Author
Abhishek B
Definition at line 22 of file CommandWindowViewController.java.
Constructor & Destructor Documentation
viewcontroller.commands.CommandWindowViewController.CommandWindowViewController (int width, int height)
Definition at line 32 of file CommandWindowViewController.java.
References viewcontroller.commands.CommandWindowViewController.addStyleSheets().
Member Function Documentation
void viewcontroller.commands.CommandWindowViewController.addStyleSheets () private
Back up elements in this by CSS files
Definition at line 51 of file CommandWindowViewController.java.
References viewcontroller.GUIReferenceLibrary.getPath().
Referenced by viewcontroller.commands.CommandWindowViewController.CommandWindowViewController().
void viewcontroller.commands.CommandWindowViewController.setTitle (String titleText) protected
Definition at line 57 of file CommandWindowViewController.java.
Referenced by viewcontroller.commands.CommandHistoryViewController.CommandHistoryViewController(), viewcontroller.commands.CommandPromptViewController.CommandPromptViewController(), viewcontroller.commands.CommandStatusViewController.CommandStatusViewController(), viewcontroller.commands.UserDefinedMethodsViewController.UserDefinedMethodsViewController(), and viewcontroller.commands.UserDefinedVariablesViewController.UserDefinedVariablesViewController().
Member Data Documentation
VBox viewcontroller.commands.CommandWindowViewController.myCommandWindowVerticalBox protected
Definition at line 24 of file CommandWindowViewController.java.
Referenced by viewcontroller.commands.CommandListWindowViewController.CommandListWindowViewController(), viewcontroller.commands.CommandPromptViewController.CommandPromptViewController(), viewcontroller.commands.CommandStatusViewController.setStatusLabel(), and viewcontroller.turtlegrid.TurtleStatusViewController.TurtleStatusViewController().
BorderPane viewcontroller.commands.CommandWindowViewController.myPane protected
Definition at line 23 of file CommandWindowViewController.java.
Referenced by viewcontroller.commands.CommandListWindowViewController.CommandListWindowViewController(), viewcontroller.commands.CommandHistoryViewController.getNode(), viewcontroller.commands.UserDefinedMethodsViewController.getNode(), viewcontroller.commands.UserDefinedVariablesViewController.getNode(), viewcontroller.turtlegrid.TurtleStatusViewController.getNode(), viewcontroller.commands.CommandStatusViewController.getNode(), and viewcontroller.commands.CommandPromptViewController.getNode().
Label viewcontroller.commands.CommandWindowViewController.myTitleLabel protected
Definition at line 25 of file CommandWindowViewController.java.
Referenced by viewcontroller.turtlegrid.TurtleStatusViewController.TurtleStatusViewController().
final String viewcontroller.commands.CommandWindowViewController.PANE_KEY = "pane" private
Definition at line 28 of file CommandWindowViewController.java.
Dimension viewcontroller.commands.CommandWindowViewController.SIZE = new Dimension() protected
Definition at line 26 of file CommandWindowViewController.java.
Referenced by viewcontroller.commands.UserDefinedVariablesViewController.addVariableToList(), viewcontroller.turtlegrid.TurtleStatusViewController.populateHBox(), and viewcontroller.commands.CommandPromptViewController.setUpCommandPromptHorizontalBox().
final String viewcontroller.commands.CommandWindowViewController.TEXT_KEY = "text" private
Definition at line 29 of file CommandWindowViewController.java.
final String viewcontroller.commands.CommandWindowViewController.VBOX_KEY = "vbox" private
Definition at line 30 of file CommandWindowViewController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/viewcontroller/commands/CommandWindowViewController.java