slogo_team04: viewcontroller.HelpDialogBox Class Reference
viewcontroller.HelpDialogBox Class Reference
Public Member Functions
HelpDialogBox ()
void show ()
Private Member Functions
void setUpGUIStrings ()
Node makePageDisplay ()
Private Attributes
String myHTTPString
String myPrefixString
String myCommandURLString
Stage myStage
String myURL
Static Private Attributes
static final String HTTP_KEY = "http"
static final String PREFIX_KEY = "urlPrefix"
static final String COMMANDS_KEY = "commands1"
Detailed Description
webview for help dialog box opened by file->help
Author
Jonathan Tseng
Definition at line 15 of file HelpDialogBox.java.
Constructor & Destructor Documentation
viewcontroller.HelpDialogBox.HelpDialogBox ()
Sets up GUI Reference Mapping Constructs the URL from the prefixes and the specific command page ending
Definition at line 31 of file HelpDialogBox.java.
References viewcontroller.HelpDialogBox.myCommandURLString, and viewcontroller.HelpDialogBox.setUpGUIStrings().
Member Function Documentation
Node viewcontroller.HelpDialogBox.makePageDisplay () private
Open up the browser and load this URL to open the page
Returns
Definition at line 63 of file HelpDialogBox.java.
Referenced by viewcontroller.HelpDialogBox.show().
void viewcontroller.HelpDialogBox.setUpGUIStrings () private
Sets up the GUI Library for help reference
Definition at line 39 of file HelpDialogBox.java.
References viewcontroller.GUIReferenceLibrary.getURL(), and viewcontroller.GUIReferenceLibrary.setHelpReference().
Referenced by viewcontroller.HelpDialogBox.HelpDialogBox().
void viewcontroller.HelpDialogBox.show ()
Display the Help Dialog Window
Definition at line 49 of file HelpDialogBox.java.
References viewcontroller.HelpDialogBox.makePageDisplay().
Referenced by viewcontroller.View.showHelp().
Member Data Documentation
final String viewcontroller.HelpDialogBox.COMMANDS_KEY = "commands1" static private
Definition at line 19 of file HelpDialogBox.java.
final String viewcontroller.HelpDialogBox.HTTP_KEY = "http" static private
Definition at line 17 of file HelpDialogBox.java.
String viewcontroller.HelpDialogBox.myCommandURLString private
Definition at line 22 of file HelpDialogBox.java.
Referenced by viewcontroller.HelpDialogBox.HelpDialogBox().
String viewcontroller.HelpDialogBox.myHTTPString private
Definition at line 20 of file HelpDialogBox.java.
String viewcontroller.HelpDialogBox.myPrefixString private
Definition at line 21 of file HelpDialogBox.java.
Stage viewcontroller.HelpDialogBox.myStage private
Definition at line 24 of file HelpDialogBox.java.
String viewcontroller.HelpDialogBox.myURL private
Definition at line 25 of file HelpDialogBox.java.
final String viewcontroller.HelpDialogBox.PREFIX_KEY = "urlPrefix" static private
Definition at line 18 of file HelpDialogBox.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/viewcontroller/HelpDialogBox.java