slogo_team04: model.MainModel Class Reference
model.MainModel Class Reference
Public Member Functions
MainModel (String language)
MainModel (String language, CommandHistoryModel cHM, UserDefinedCommandsModel uDCM, UserDefinedVariablesModel uDVM, String backGroundColor)
void changeTurtleImages (File file)
Color getBackgroundColor ()
String getBackgroundColorName ()
void updateAnimationSpeed (double speed)
void setBackgroundColor (Color color)
void updatePen (PenForm penForm)
void updatePenColor (Color color)
Turtle getActiveTurtle ()
void addTurtle ()
List< Turtle > getTurtles ()
boolean isTurtleAdded ()
SLogoResult getResult ()
void interpretSLogoCommand (String sLogoCommand)
void interpretSLogoCommand (String commandKey, String operands)
boolean getFailedParse ()
ParallelTransition getAnimation ()
void setLanguage (String languageName)
void attachObserver (MainModelObserver observer)
CommandHistoryModel getCommandHistory ()
UserDefinedCommandsModel getUserDefinedMethods ()
UserDefinedVariablesModel getUserDefinedVariables ()
String getLanguage ()
void undoClicked ()
void redoClicked ()
void setmyInterpreter ()
Package Attributes
final String PROPERTIES_FILENAME = "SLogoState"
final String LANGUAGE_PROPERTY = "Language"
Private Member Functions
void updateModel ()
void setMyAnimation (Map< Turtle, List< TransitionState >> map)
void notifyObservers ()
void setProperty (String propertyName, String value)
Private Attributes
Color myBackgroundColor
boolean myTurtleAdded
boolean myFailedParse
List< MainModelObserver > myObservers
transient Interpreter myInterpreter
transient List< Turtle > myTurtles
transient TurtleListHistory myTurtleListHistory
SLogoResult mySLogoResult
String myLanguage
CommandHistoryModel myCommandHistoryModel
UserDefinedCommandsModel myUserDefinedMethodsModel
UserDefinedVariablesModel myUserDefinedVariablesModel
double myAnimationSpeed
transient ParallelTransition myAnimation
Static Private Attributes
static final Color DEFAULT_BACKGROUND_COLOR = Color.DARKBLUE
Detailed Description
Main model of program–Holds the state of the program, also holds and updates other models
Author
Tanaka Jimha
Definition at line 29 of file MainModel.java.
Constructor & Destructor Documentation
model.MainModel.MainModel (String language)
Definition at line 49 of file MainModel.java.
References model.MainModel.DEFAULT_BACKGROUND_COLOR.
model.MainModel.MainModel (String language, CommandHistoryModel cHM, UserDefinedCommandsModel uDCM, UserDefinedVariablesModel uDVM, String backGroundColor)
Definition at line 64 of file MainModel.java.
Member Function Documentation
void model.MainModel.addTurtle ()
adds a turtle
Definition at line 139 of file MainModel.java.
References model.MainModel.notifyObservers().
Referenced by viewcontroller.View.addTurtleClicked(), and viewcontroller.Workspace.Workspace().
void model.MainModel.attachObserver (MainModelObserver observer)
Definition at line 220 of file MainModel.java.
Referenced by viewcontroller.MainViewController.MainViewController().
void model.MainModel.changeTurtleImages (File file)
Definition at line 81 of file MainModel.java.
Referenced by viewcontroller.View.changeTurtleImages().
Turtle model.MainModel.getActiveTurtle ()
Definition at line 127 of file MainModel.java.
Referenced by viewcontroller.turtlegrid.TurtleStatusViewController.update().
ParallelTransition model.MainModel.getAnimation ()
Definition at line 207 of file MainModel.java.
References model.MainModel.myAnimation.
Referenced by viewcontroller.turtlegrid.GridViewController.update().
Color model.MainModel.getBackgroundColor ()
Definition at line 89 of file MainModel.java.
References model.MainModel.myBackgroundColor.
Referenced by viewcontroller.turtlegrid.GridViewController.update().
String model.MainModel.getBackgroundColorName ()
Definition at line 93 of file MainModel.java.
Referenced by model.SerialisableModel.SerialisableModel().
CommandHistoryModel model.MainModel.getCommandHistory ()
Definition at line 230 of file MainModel.java.
References model.MainModel.myCommandHistoryModel.
Referenced by model.SerialisableModel.SerialisableModel(), and viewcontroller.commands.CommandHistoryViewController.update().
boolean model.MainModel.getFailedParse ()
Definition at line 187 of file MainModel.java.
References model.MainModel.myFailedParse.
Referenced by viewcontroller.turtlegrid.GridViewController.update().
String model.MainModel.getLanguage ()
Definition at line 264 of file MainModel.java.
References model.MainModel.myLanguage.
Referenced by interpreter.Interpreter.Interpreter(), and model.SerialisableModel.SerialisableModel().
SLogoResult model.MainModel.getResult ()
Definition at line 154 of file MainModel.java.
References model.MainModel.mySLogoResult.
Referenced by viewcontroller.commands.CommandStatusViewController.update().
List<Turtle> model.MainModel.getTurtles ()
Definition at line 146 of file MainModel.java.
References model.MainModel.myTurtles.
Referenced by interpreter.expression.query.YCoordinate.getValueFromModel(), interpreter.expression.query.XCoordinate.getValueFromModel(), interpreter.expression.query.Heading.getValueFromModel(), interpreter.expression.query.IsPenDown.getValueFromModel(), interpreter.expression.query.IsShowing.getValueFromModel(), interpreter.expression.singleturtle.SetPosition.setNextTransition(), interpreter.expression.singleturtle.SetHeading.setNextTransition(), interpreter.expression.display.SetPenSize.setPenSize(), and viewcontroller.turtlegrid.GridViewController.update().
UserDefinedCommandsModel model.MainModel.getUserDefinedMethods ()
Definition at line 234 of file MainModel.java.
References model.MainModel.myUserDefinedMethodsModel.
Referenced by interpreter.Interpreter.Interpreter(), interpreter.expression.syntax.Command.loadArguments(), model.SerialisableModel.SerialisableModel(), and viewcontroller.commands.UserDefinedMethodsViewController.update().
UserDefinedVariablesModel model.MainModel.getUserDefinedVariables ()
Definition at line 238 of file MainModel.java.
References model.MainModel.myUserDefinedVariablesModel.
Referenced by interpreter.Interpreter.Interpreter(), model.SerialisableModel.SerialisableModel(), and viewcontroller.commands.UserDefinedVariablesViewController.update().
void model.MainModel.interpretSLogoCommand (String sLogoCommand)
interprets a String SLogoCommand by passing it to the Interpreter
Parameters
sLogoCommand
Definition at line 164 of file MainModel.java.
References model.CommandHistoryModel.addCommand(), interpreter.result.SLogoResult.getHasError(), interpreter.Interpreter.interpret(), model.MainModel.notifyObservers(), and model.MainModel.updateModel().
Referenced by model.MainModel.interpretSLogoCommand(), and viewcontroller.MainViewController.passSLogoCommand().
void model.MainModel.interpretSLogoCommand (String commandKey, String operands)
Definition at line 175 of file MainModel.java.
References interpreter.Interpreter.getCommandReferenceLibrary(), interpreter.CommandReferenceLibrary.getReferencesToCommands(), and model.MainModel.interpretSLogoCommand().
boolean model.MainModel.isTurtleAdded ()
Definition at line 150 of file MainModel.java.
References model.MainModel.myTurtleAdded.
Referenced by viewcontroller.turtlegrid.GridViewController.update().
void model.MainModel.notifyObservers () private
Definition at line 224 of file MainModel.java.
Referenced by model.MainModel.addTurtle(), model.MainModel.interpretSLogoCommand(), model.MainModel.redoClicked(), model.MainModel.setBackgroundColor(), and model.MainModel.undoClicked().
void model.MainModel.redoClicked ()
Definition at line 276 of file MainModel.java.
References turtle.TurtleHistoryState.getAnimation(), turtle.TurtleHistoryState.getLines(), model.MainModel.notifyObservers(), and turtle.TurtleListHistory.redo().
Referenced by viewcontroller.View.redoClicked().
void model.MainModel.setBackgroundColor (Color color)
Definition at line 102 of file MainModel.java.
References model.MainModel.notifyObservers().
Referenced by viewcontroller.MainViewController.gridColorChanged().
void model.MainModel.setLanguage (String languageName)
used to set the language in which the commands are written in
Parameters
myLanguage
Definition at line 215 of file MainModel.java.
References model.MainModel.setProperty().
void model.MainModel.setMyAnimation (Map< Turtle, List< TransitionState >> map) private
Definition at line 197 of file MainModel.java.
References turtle.TurtleListHistory.updateList().
Referenced by model.MainModel.updateModel().
void model.MainModel.setmyInterpreter ()
Definition at line 286 of file MainModel.java.
void model.MainModel.setProperty (String propertyName, String value) private
Definition at line 242 of file MainModel.java.
Referenced by model.MainModel.setLanguage().
void model.MainModel.undoClicked ()
Definition at line 267 of file MainModel.java.
References turtle.TurtleHistoryState.getAnimation(), turtle.TurtleHistoryState.getLines(), model.MainModel.notifyObservers(), and turtle.TurtleListHistory.undo().
Referenced by viewcontroller.View.undoClicked().
void model.MainModel.updateAnimationSpeed (double speed)
Definition at line 97 of file MainModel.java.
Referenced by viewcontroller.MainViewController.animationSpeedChanged().
void model.MainModel.updateModel () private
Definition at line 191 of file MainModel.java.
References interpreter.result.SLogoResult.getTransition(), model.MainModel.setMyAnimation(), and model.ModelUpdater.updateModel().
Referenced by model.MainModel.interpretSLogoCommand().
void model.MainModel.updatePen (PenForm penForm)
Definition at line 108 of file MainModel.java.
References application.PenFormResult.getPenDash(), application.PenFormResult.getPenUp(), application.PenFormResult.getPenWidth(), and application.PenForm.getResult().
Referenced by viewcontroller.View.shit().
void model.MainModel.updatePenColor (Color color)
Definition at line 119 of file MainModel.java.
Referenced by viewcontroller.MainViewController.penColorChanged().
Member Data Documentation
final Color model.MainModel.DEFAULT_BACKGROUND_COLOR = Color.DARKBLUE static private
Definition at line 31 of file MainModel.java.
Referenced by model.MainModel.MainModel().
final String model.MainModel.LANGUAGE_PROPERTY = "Language" package
Definition at line 47 of file MainModel.java.
transient ParallelTransition model.MainModel.myAnimation private
Definition at line 45 of file MainModel.java.
Referenced by model.MainModel.getAnimation().
double model.MainModel.myAnimationSpeed private
Definition at line 44 of file MainModel.java.
Color model.MainModel.myBackgroundColor private
Definition at line 32 of file MainModel.java.
Referenced by model.MainModel.getBackgroundColor().
CommandHistoryModel model.MainModel.myCommandHistoryModel private
Definition at line 41 of file MainModel.java.
Referenced by model.MainModel.getCommandHistory().
boolean model.MainModel.myFailedParse private
Definition at line 34 of file MainModel.java.
Referenced by model.MainModel.getFailedParse().
transient Interpreter model.MainModel.myInterpreter private
Definition at line 36 of file MainModel.java.
String model.MainModel.myLanguage private
Definition at line 40 of file MainModel.java.
Referenced by model.MainModel.getLanguage().
List<MainModelObserver> model.MainModel.myObservers private
Definition at line 35 of file MainModel.java.
SLogoResult model.MainModel.mySLogoResult private
Definition at line 39 of file MainModel.java.
Referenced by model.MainModel.getResult().
boolean model.MainModel.myTurtleAdded private
Definition at line 33 of file MainModel.java.
Referenced by model.MainModel.isTurtleAdded().
transient TurtleListHistory model.MainModel.myTurtleListHistory private
Definition at line 38 of file MainModel.java.
transient List<Turtle> model.MainModel.myTurtles private
Definition at line 37 of file MainModel.java.
Referenced by model.MainModel.getTurtles().
UserDefinedCommandsModel model.MainModel.myUserDefinedMethodsModel private
Definition at line 42 of file MainModel.java.
Referenced by model.MainModel.getUserDefinedMethods().
UserDefinedVariablesModel model.MainModel.myUserDefinedVariablesModel private
Definition at line 43 of file MainModel.java.
Referenced by model.MainModel.getUserDefinedVariables().
final String model.MainModel.PROPERTIES_FILENAME = "SLogoState" package
Definition at line 46 of file MainModel.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/model/MainModel.java