slogo_team04: viewcontroller.Workspace Class Reference
viewcontroller.Workspace Class Reference
Public Member Functions
Workspace (String language)
Workspace (MainModel model)
MainViewController getViewController ()
MainModel getMainModel ()
Private Attributes
MainViewController myMainViewController
MainModel myMainModel
Detailed Description
Workspace that contains a view-controller and model.
Author
Jonathan Tseng
Definition at line 10 of file Workspace.java.
Constructor & Destructor Documentation
viewcontroller.Workspace.Workspace (String language)
Definition at line 15 of file Workspace.java.
viewcontroller.Workspace.Workspace (MainModel model)
Definition at line 19 of file Workspace.java.
References model.MainModel.addTurtle().
Member Function Documentation
MainModel viewcontroller.Workspace.getMainModel ()
Definition at line 29 of file Workspace.java.
References viewcontroller.Workspace.myMainModel.
Referenced by viewcontroller.View.addTurtleClicked(), viewcontroller.View.changeTurtleImages(), viewcontroller.View.redoClicked(), viewcontroller.View.saveWorkspace(), viewcontroller.View.shit(), and viewcontroller.View.undoClicked().
MainViewController viewcontroller.Workspace.getViewController ()
Definition at line 25 of file Workspace.java.
References viewcontroller.Workspace.myMainViewController.
Referenced by viewcontroller.View.addWorkspace(), viewcontroller.View.loadFile(), unittest.CommandPromptTextTest.testTransferOfString(), and viewcontroller.View.toggleGridLines().
Member Data Documentation
MainModel viewcontroller.Workspace.myMainModel private
Definition at line 13 of file Workspace.java.
Referenced by viewcontroller.Workspace.getMainModel().
MainViewController viewcontroller.Workspace.myMainViewController private
Definition at line 12 of file Workspace.java.
Referenced by viewcontroller.Workspace.getViewController().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/viewcontroller/Workspace.java