slogo_team04: interpreter.Parser Class Reference
interpreter.Parser Class Reference
Public Member Functions
Parser (CommandReferenceLibrary library, MainModel model)
Deque< SLogoExpression > parseSLogoExpression (String input) throws SLogoParsingException, NoSuchElementException
Private Member Functions
Deque< SLogoExpression > makeExpressionsFromInput (Deque< String > processedInputStack) throws SLogoParsingException, NullPointerException
Deque< String > processInput (String input)
void loadAllExpressionParameters (Deque< SLogoExpression > expressionStack) throws SLogoParsingException, NoSuchElementException
String parseOutComments (String input)
Private Attributes
final String spaceSplit = "\\s+"
final String comment = "#"
final String newline = "\n"
Deque< SLogoExpression > myParameterStack
Deque< SLogoExpression > myLoadedExpressions
SLogoExpressionFactory myFactory
Detailed Description
Parses the input and creates an SLogoExpression representing it throws parsing exception if fails
Author
Will Chang
Definition at line 18 of file Parser.java.
Constructor & Destructor Documentation
interpreter.Parser.Parser (CommandReferenceLibrary library, MainModel model)
Constructor
Parameters
library
Definition at line 30 of file Parser.java.
Member Function Documentation
void interpreter.Parser.loadAllExpressionParameters (Deque< SLogoExpression > expressionStack) throws SLogoParsingException, NoSuchElementException private
Loads all parameters into all generated expressions.
Parameters
expressionStack
Definition at line 79 of file Parser.java.
References interpreter.expression.SLogoExpression.loadArguments().
Referenced by interpreter.Parser.parseSLogoExpression().
Deque<SLogoExpression> interpreter.Parser.makeExpressionsFromInput (Deque< String > processedInputStack) throws SLogoParsingException, NullPointerException private
Calls Factory to create all SLogoExpressions from user input
Parameters
processedInputStack processed String deque
Returns
Deque of SLogoExpressions
Exceptions
SLogoParsingException
Definition at line 56 of file Parser.java.
References interpreter.SLogoExpressionFactory.createExpression(), and interpreter.Parser.myParameterStack.
Referenced by interpreter.Parser.parseSLogoExpression().
String interpreter.Parser.parseOutComments (String input) private
Removes comments from the string
Parameters
input string
Returns
string without comments
Definition at line 94 of file Parser.java.
Referenced by interpreter.Parser.parseSLogoExpression().
Deque<SLogoExpression> interpreter.Parser.parseSLogoExpression (String input) throws SLogoParsingException, NoSuchElementException
Reads expression from back, parsing using a stack and returns list of expressions to evaluate
Parameters
input String read from frontend
Returns
a deque of SLogoExpressions to evaluate
Exceptions
SLogoParsingException if invalid input
Definition at line 42 of file Parser.java.
References interpreter.Parser.loadAllExpressionParameters(), interpreter.Parser.makeExpressionsFromInput(), interpreter.Parser.myLoadedExpressions, interpreter.Parser.parseOutComments(), and interpreter.Parser.processInput().
Referenced by interpreter.Interpreter.interpret().
Deque<String> interpreter.Parser.processInput (String input) private
Processes initial String input
Parameters
input String from frontend
Returns
Deque of all potential user specified commands
Definition at line 70 of file Parser.java.
Referenced by interpreter.Parser.parseSLogoExpression().
Member Data Documentation
final String interpreter.Parser.comment = "#" private
Definition at line 20 of file Parser.java.
SLogoExpressionFactory interpreter.Parser.myFactory private
Definition at line 24 of file Parser.java.
Deque<SLogoExpression> interpreter.Parser.myLoadedExpressions private
Definition at line 23 of file Parser.java.
Referenced by interpreter.Parser.parseSLogoExpression().
Deque<SLogoExpression> interpreter.Parser.myParameterStack private
Definition at line 22 of file Parser.java.
Referenced by interpreter.Parser.makeExpressionsFromInput().
final String interpreter.Parser.newline = "\n" private
Definition at line 21 of file Parser.java.
final String interpreter.Parser.spaceSplit = "\\s+" private
Definition at line 19 of file Parser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/interpreter/Parser.java