slogo_team04: interpreter.SLogoExpressionFactory Class Reference
interpreter.SLogoExpressionFactory Class Reference
Classes
enum stringType
Public Member Functions
SLogoExpressionFactory (CommandReferenceLibrary library, MainModel model)
SLogoExpression createExpression (String command) throws SLogoParsingException
Private Member Functions
SLogoExpression checkTypeAndInitialize (String command, Map< String, String > referenceMap, stringType type) throws SLogoParsingException
boolean isMatch (String command, String reference, stringType type)
void initializeExpression (SLogoExpression expression, String name)
Private Attributes
final String myClassPath = "interpreter.expression."
Map< String, String > myReferenceToCommandMap
Map< String, String > myReverseSyntaxMap
Map< String, String > myCommandToDirectoryMap
Map< String, Integer > myCommandToNumArgsMap
CommandReferenceLibrary myLibrary
MainModel myModel
Detailed Description
factory for creating an SLogoExpression for a given string throws exception for unimplemented or nonexistent method names
Author
Will Chang
Definition at line 14 of file SLogoExpressionFactory.java.
Constructor & Destructor Documentation
interpreter.SLogoExpressionFactory.SLogoExpressionFactory (CommandReferenceLibrary library, MainModel model)
Constructor
Parameters
library
Definition at line 34 of file SLogoExpressionFactory.java.
References interpreter.CommandReferenceLibrary.getCommandsToDirectories(), interpreter.CommandReferenceLibrary.getCommandsToNumArgs(), interpreter.CommandReferenceLibrary.getReferencesToCommands(), and interpreter.CommandReferenceLibrary.getReverseSyntaxes().
Member Function Documentation
SLogoExpression interpreter.SLogoExpressionFactory.checkTypeAndInitialize (String command, Map< String, String > referenceMap, stringType type) throws SLogoParsingException private
Checks whether the type of input is a predefined command or a regex and initializes the expression using reflection
Parameters
command the command's name the user inputted
referenceMap the map which holds the type of references to check
type the type of input it is
Returns
the desired SLogoExpression
Definition at line 64 of file SLogoExpressionFactory.java.
References interpreter.SLogoExpressionFactory.initializeExpression(), interpreter.SLogoExpressionFactory.isMatch(), and interpreter.expression.SLogoExpression.setValue().
Referenced by interpreter.SLogoExpressionFactory.createExpression().
SLogoExpression interpreter.SLogoExpressionFactory.createExpression (String command) throws SLogoParsingException
creates an SLogoExpression based on given command string throws parsing exception if no command exists for given string
Parameters
command
Returns
Exceptions
ParsingException
Definition at line 50 of file SLogoExpressionFactory.java.
References interpreter.SLogoExpressionFactory.checkTypeAndInitialize(), interpreter.SLogoExpressionFactory.stringType.NORMAL, and interpreter.SLogoExpressionFactory.stringType.REGEX.
Referenced by interpreter.Parser.makeExpressionsFromInput().
void interpreter.SLogoExpressionFactory.initializeExpression (SLogoExpression expression, String name) private
Initializes the parameters of the Expression.
Parameters
expression to initialize
name of the expression
Definition at line 105 of file SLogoExpressionFactory.java.
References interpreter.expression.SLogoExpression.loadLibrary(), interpreter.expression.SLogoExpression.loadModel(), and interpreter.expression.SLogoExpression.setNumArgs().
Referenced by interpreter.SLogoExpressionFactory.checkTypeAndInitialize().
boolean interpreter.SLogoExpressionFactory.isMatch (String command, String reference, stringType type) private
Checks the type of the Command and returns the proper
Parameters
command
reference
type
Returns
Definition at line 96 of file SLogoExpressionFactory.java.
References interpreter.SLogoExpressionFactory.stringType.NORMAL.
Referenced by interpreter.SLogoExpressionFactory.checkTypeAndInitialize().
Member Data Documentation
final String interpreter.SLogoExpressionFactory.myClassPath = "interpreter.expression." private
Definition at line 16 of file SLogoExpressionFactory.java.
Map<String, String> interpreter.SLogoExpressionFactory.myCommandToDirectoryMap private
Definition at line 20 of file SLogoExpressionFactory.java.
Map<String, Integer> interpreter.SLogoExpressionFactory.myCommandToNumArgsMap private
Definition at line 21 of file SLogoExpressionFactory.java.
CommandReferenceLibrary interpreter.SLogoExpressionFactory.myLibrary private
Definition at line 23 of file SLogoExpressionFactory.java.
MainModel interpreter.SLogoExpressionFactory.myModel private
Definition at line 24 of file SLogoExpressionFactory.java.
Map<String, String> interpreter.SLogoExpressionFactory.myReferenceToCommandMap private
Definition at line 18 of file SLogoExpressionFactory.java.
Map<String, String> interpreter.SLogoExpressionFactory.myReverseSyntaxMap private
Definition at line 19 of file SLogoExpressionFactory.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/interpreter/SLogoExpressionFactory.java