slogo_team04: viewcontroller.commands.CommandWindowContainerViewController Class Reference
viewcontroller.commands.CommandWindowContainerViewController Class Reference
Public Member Functions
CommandWindowContainerViewController (MainViewController parent)
void loadScript (String script)
void passSLogoCommand (String command)
void passSLogoCommand (String commandKey, String operands)
void moveCommandTextToPromptWindow (String commandFromPrelists)
CommandPromptViewController getCommandPrompt ()
Node getNode ()
void update (MainModel model)
void applyTranslations ()
Private Member Functions
void placeCommandWindows ()
HBox placeUserDefinedBoxes ()
Private Attributes
MainViewController myParent
BorderPane myPane
VBox myCommandWindowVerticalBox
UserDefinedMethodsViewController myUserDefinedMethodsView
UserDefinedVariablesViewController myUserDefinedVariablesView
CommandHistoryViewController myCommandHistoryView
CommandPromptViewController myCommandPromptView
CommandStatusViewController myCommandStatusView
List< MainModelObserver > myChildObservers
Static Private Attributes
static Dimension SIZE
Detailed Description
ViewController for containing all of the command windows (where prompt/status/history/user-defined windows are located)
Author
Abhishek B
Definition at line 26 of file CommandWindowContainerViewController.java.
Constructor & Destructor Documentation
viewcontroller.commands.CommandWindowContainerViewController.CommandWindowContainerViewController (MainViewController parent)
Definition at line 40 of file CommandWindowContainerViewController.java.
References viewcontroller.commands.CommandWindowContainerViewController.placeCommandWindows().
Member Function Documentation
void viewcontroller.commands.CommandWindowContainerViewController.applyTranslations ()
translate the string using the GUI Reference Library
Implements viewcontroller.ViewController.
Definition at line 148 of file CommandWindowContainerViewController.java.
CommandPromptViewController viewcontroller.commands.CommandWindowContainerViewController.getCommandPrompt ()
Definition at line 127 of file CommandWindowContainerViewController.java.
References viewcontroller.commands.CommandWindowContainerViewController.myCommandPromptView.
Referenced by unittest.CommandPromptTextTest.testTransferOfString().
Node viewcontroller.commands.CommandWindowContainerViewController.getNode ()
returns the Node representing the view for a view controller
Returns
Implements viewcontroller.ViewController.
Definition at line 132 of file CommandWindowContainerViewController.java.
References viewcontroller.commands.CommandWindowContainerViewController.myPane.
Referenced by viewcontroller.MainViewController.placeCommandWindowView().
void viewcontroller.commands.CommandWindowContainerViewController.loadScript (String script)
Dump the text from the loaded script (file system) into the Command Prompt TextArea.
Parameters
script
Definition at line 54 of file CommandWindowContainerViewController.java.
References viewcontroller.commands.CommandPromptViewController.setCommandPromptText().
Referenced by viewcontroller.MainViewController.loadScript().
void viewcontroller.commands.CommandWindowContainerViewController.moveCommandTextToPromptWindow (String commandFromPrelists)
Parameters
commandFromPrelists
Definition at line 123 of file CommandWindowContainerViewController.java.
References viewcontroller.commands.CommandPromptViewController.setCommandPromptText().
Referenced by viewcontroller.commands.CommandClickableListWindowViewController.addCommand(), and unittest.CommandPromptTextTest.testTransferOfString().
void viewcontroller.commands.CommandWindowContainerViewController.passSLogoCommand (String command)
Pass the SLogo Command to the parent to go to the model
Parameters
command
Definition at line 63 of file CommandWindowContainerViewController.java.
References viewcontroller.MainViewController.passSLogoCommand().
Referenced by viewcontroller.commands.UserDefinedVariablesViewController.keyPressed(), and viewcontroller.commands.CommandPromptViewController.passCommandToModel().
void viewcontroller.commands.CommandWindowContainerViewController.passSLogoCommand (String commandKey, String operands)
Pass the key to be mapped to a command. For example, UP arrow key maps to the Forward expression.
Parameters
commandKey
operands
Definition at line 74 of file CommandWindowContainerViewController.java.
References viewcontroller.MainViewController.passSLogoCommand().
void viewcontroller.commands.CommandWindowContainerViewController.placeCommandWindows () private
Place all child ViewController nodes into this overall container.
Definition at line 81 of file CommandWindowContainerViewController.java.
References viewcontroller.commands.CommandHistoryViewController.getNode(), viewcontroller.commands.CommandStatusViewController.getNode(), viewcontroller.commands.CommandPromptViewController.getNode(), and viewcontroller.commands.CommandWindowContainerViewController.placeUserDefinedBoxes().
Referenced by viewcontroller.commands.CommandWindowContainerViewController.CommandWindowContainerViewController().
HBox viewcontroller.commands.CommandWindowContainerViewController.placeUserDefinedBoxes () private
Set up the HBox to contain the User-Defined models
Returns
HBox containing User-Defined Models
Definition at line 104 of file CommandWindowContainerViewController.java.
References viewcontroller.commands.UserDefinedMethodsViewController.getNode(), and viewcontroller.commands.UserDefinedVariablesViewController.getNode().
Referenced by viewcontroller.commands.CommandWindowContainerViewController.placeCommandWindows().
void viewcontroller.commands.CommandWindowContainerViewController.update (MainModel model)
Run update on every child view controller (in the container), these being contained in myChildObservers
Implements viewcontroller.MainModelObserver.
Definition at line 141 of file CommandWindowContainerViewController.java.
Member Data Documentation
List<MainModelObserver> viewcontroller.commands.CommandWindowContainerViewController.myChildObservers private
Definition at line 38 of file CommandWindowContainerViewController.java.
CommandHistoryViewController viewcontroller.commands.CommandWindowContainerViewController.myCommandHistoryView private
Definition at line 35 of file CommandWindowContainerViewController.java.
CommandPromptViewController viewcontroller.commands.CommandWindowContainerViewController.myCommandPromptView private
Definition at line 36 of file CommandWindowContainerViewController.java.
Referenced by viewcontroller.commands.CommandWindowContainerViewController.getCommandPrompt().
CommandStatusViewController viewcontroller.commands.CommandWindowContainerViewController.myCommandStatusView private
Definition at line 37 of file CommandWindowContainerViewController.java.
VBox viewcontroller.commands.CommandWindowContainerViewController.myCommandWindowVerticalBox private
Definition at line 32 of file CommandWindowContainerViewController.java.
BorderPane viewcontroller.commands.CommandWindowContainerViewController.myPane private
Definition at line 31 of file CommandWindowContainerViewController.java.
Referenced by viewcontroller.commands.CommandWindowContainerViewController.getNode().
MainViewController viewcontroller.commands.CommandWindowContainerViewController.myParent private
Definition at line 30 of file CommandWindowContainerViewController.java.
UserDefinedMethodsViewController viewcontroller.commands.CommandWindowContainerViewController.myUserDefinedMethodsView private
Definition at line 33 of file CommandWindowContainerViewController.java.
UserDefinedVariablesViewController viewcontroller.commands.CommandWindowContainerViewController.myUserDefinedVariablesView private
Definition at line 34 of file CommandWindowContainerViewController.java.
Dimension viewcontroller.commands.CommandWindowContainerViewController.SIZE static private
Initial value:
= new Dimension(Main.SIZE.width / 2 * 9 / 10,
            Main.SIZE.height * 9 / 10)
Definition at line 28 of file CommandWindowContainerViewController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/viewcontroller/commands/CommandWindowContainerViewController.java