slogo_team04: interpreter.expression.syntax.Command Class Reference
interpreter.expression.syntax.Command Class Reference
Public Member Functions
Command ()
void loadArguments (Deque< SLogoExpression > args) throws SLogoParsingException, NullPointerException
SLogoResult evaluate ()
String toString ()
Public Member Functions inherited from interpreter.expression.SyntaxExpression
SyntaxExpression ()
void setNumArgs (int value)
void loadLibrary (CommandReferenceLibrary library)
void loadModel (MainModel model)
void loadArguments (Deque< SLogoExpression > args) throws SLogoParsingException, NullPointerException
int getNumArgs ()
SLogoResult evaluate ()
void setValue (String value)
String getValue ()
Private Attributes
SLogoExpression myCommands
List< String > myVariableReferences
UserDefinedCommandsModel allDefinedCommands
Additional Inherited Members
Protected Attributes inherited from interpreter.expression.SyntaxExpression
CommandReferenceLibrary myLibrary
MainModel myModel
int myNumArgs
Deque< SLogoExpression > myArguments
String myValue
Detailed Description
Author
Will
Definition at line 19 of file Command.java.
Constructor & Destructor Documentation
interpreter.expression.syntax.Command.Command ()
Definition at line 24 of file Command.java.
Member Function Documentation
SLogoResult interpreter.expression.syntax.Command.evaluate ()
evaluates the expression and returns an SLogoResult
Returns
Exceptions
SLogoParsingException
Implements interpreter.expression.SLogoExpression.
Definition at line 42 of file Command.java.
References model.UserDefinedCommandsModel.containsCommand(), interpreter.expression.SLogoExpression.evaluate(), model.UserDefinedCommandsModel.getCommand(), interpreter.result.SLogoResult.getTransition(), interpreter.CommandReferenceLibrary.getUserDefinedVariables(), interpreter.result.SLogoResult.getValue(), interpreter.expression.SyntaxExpression.myArguments, interpreter.expression.SyntaxExpression.myLibrary, interpreter.expression.SyntaxExpression.myNumArgs, interpreter.expression.SyntaxExpression.myValue, model.UserDefinedVariablesModel.putVariable(), model.UserDefinedVariablesModel.remove(), and interpreter.result.SLogoResult.setValue().
void interpreter.expression.syntax.Command.loadArguments (Deque< SLogoExpression > args) throws SLogoParsingException, NullPointerException
loads the list of expressions as arguments for the expression
Parameters
args
Exceptions
NullPointerException
SLogoParsingException
Implements interpreter.expression.SLogoExpression.
Definition at line 30 of file Command.java.
References model.UserDefinedCommandsModel.containsCommand(), model.MainModel.getUserDefinedMethods(), model.UserDefinedCommandsModel.getVariablesForCommand(), interpreter.expression.SyntaxExpression.myArguments, interpreter.expression.SyntaxExpression.myModel, interpreter.expression.SyntaxExpression.myNumArgs, and interpreter.expression.SyntaxExpression.myValue.
String interpreter.expression.syntax.Command.toString ()
Definition at line 68 of file Command.java.
References interpreter.expression.SyntaxExpression.myValue.
Member Data Documentation
UserDefinedCommandsModel interpreter.expression.syntax.Command.allDefinedCommands private
Definition at line 23 of file Command.java.
SLogoExpression interpreter.expression.syntax.Command.myCommands private
Definition at line 21 of file Command.java.
List<String> interpreter.expression.syntax.Command.myVariableReferences private
Definition at line 22 of file Command.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/interpreter/expression/syntax/Command.java