slogo_team04: application.StartMenu Class Reference
application.StartMenu Class Reference
Public Member Functions
StartMenu ()
void show ()
Private Member Functions
void createTitleBox ()
void createLanguageChooser ()
void createOkayButton ()
Private Attributes
Stage myStage
Label myTitleLabel
BorderPane myPane
Button myOkayButton
ComboBox< String > myLanguageChooser
Static Private Attributes
static final String LANGUAGES_KEY = "Languages"
static final String FILE_NAME = "resources.languages.view.SupportedLanguages"
static final String TITLE = "SLOGO: Choose a language"
static final String OKAY = "OK"
Detailed Description
start menu that allows user to choose language
Author
Jonathan Tseng
Definition at line 23 of file StartMenu.java.
Constructor & Destructor Documentation
application.StartMenu.StartMenu ()
Definition at line 36 of file StartMenu.java.
References application.StartMenu.createLanguageChooser(), application.StartMenu.createOkayButton(), and application.StartMenu.createTitleBox().
Member Function Documentation
void application.StartMenu.createLanguageChooser () private
Definition at line 58 of file StartMenu.java.
Referenced by application.StartMenu.StartMenu().
void application.StartMenu.createOkayButton () private
Definition at line 68 of file StartMenu.java.
References viewcontroller.View.init().
Referenced by application.StartMenu.StartMenu().
void application.StartMenu.createTitleBox () private
Definition at line 50 of file StartMenu.java.
Referenced by application.StartMenu.StartMenu().
void application.StartMenu.show ()
Definition at line 46 of file StartMenu.java.
Referenced by application.Main.start().
Member Data Documentation
final String application.StartMenu.FILE_NAME = "resources.languages.view.SupportedLanguages" static private
Definition at line 26 of file StartMenu.java.
final String application.StartMenu.LANGUAGES_KEY = "Languages" static private
Definition at line 25 of file StartMenu.java.
ComboBox<String> application.StartMenu.myLanguageChooser private
Definition at line 34 of file StartMenu.java.
Button application.StartMenu.myOkayButton private
Definition at line 33 of file StartMenu.java.
BorderPane application.StartMenu.myPane private
Definition at line 32 of file StartMenu.java.
Stage application.StartMenu.myStage private
Definition at line 30 of file StartMenu.java.
Label application.StartMenu.myTitleLabel private
Definition at line 31 of file StartMenu.java.
final String application.StartMenu.OKAY = "OK" static private
Definition at line 28 of file StartMenu.java.
final String application.StartMenu.TITLE = "SLOGO: Choose a language" static private
Definition at line 27 of file StartMenu.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/application/StartMenu.java