slogo_team04: interpreter.expression.userdefined.MakeVariable Class Reference
interpreter.expression.userdefined.MakeVariable Class Reference
Public Member Functions
SLogoResult evaluate ()
Public Member Functions inherited from interpreter.expression.UserDefinedExpression
UserDefinedExpression ()
void setNumArgs (int value)
void loadLibrary (CommandReferenceLibrary library)
void loadModel (MainModel model)
void loadArguments (Deque< SLogoExpression > args) throws SLogoParsingException, NullPointerException
int getNumArgs ()
void setValue (String value)
String getValue ()
SLogoResult evaluate ()
Additional Inherited Members
Protected Attributes inherited from interpreter.expression.UserDefinedExpression
CommandReferenceLibrary myLibrary
MainModel myModel
int myNumArgs
Deque< SLogoExpression > myArguments
String myValue
Detailed Description
Author
Will
Definition at line 14 of file MakeVariable.java.
Member Function Documentation
SLogoResult interpreter.expression.userdefined.MakeVariable.evaluate ()
evaluates the expression and returns an SLogoResult
Returns
Exceptions
SLogoParsingException
Implements interpreter.expression.SLogoExpression.
Definition at line 18 of file MakeVariable.java.
References interpreter.CommandReferenceLibrary.getUserDefinedVariables(), interpreter.result.SLogoResult.getValue(), interpreter.expression.UserDefinedExpression.myArguments, interpreter.expression.UserDefinedExpression.myLibrary, and model.UserDefinedVariablesModel.putVariable().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/interpreter/expression/userdefined/MakeVariable.java