slogo_team04: interpreter.result.SLogoResult Class Reference
interpreter.result.SLogoResult Class Reference abstract
Public Member Functions
SLogoResult ()
SLogoResult (SLogoParsingException slpe)
SLogoResult (double value)
abstract Exception getException ()
abstract List< TransitionState > getTransition ()
abstract double getValue ()
boolean getHasError ()
void setValue (double value)
void setLabel (String str)
String toString ()
Protected Attributes
List< TransitionState > myTransitionStates
ResourceBundle myProperties
double myValue
String myLabel
Private Attributes
boolean myHasError
Detailed Description
wrapper class for results of interpreting an SLogo command
Author
Jonathan Tseng and Will Chang
Definition at line 17 of file SLogoResult.java.
Constructor & Destructor Documentation
interpreter.result.SLogoResult.SLogoResult ()
Definition at line 25 of file SLogoResult.java.
interpreter.result.SLogoResult.SLogoResult (SLogoParsingException slpe)
Definition at line 29 of file SLogoResult.java.
interpreter.result.SLogoResult.SLogoResult (double value)
Definition at line 35 of file SLogoResult.java.
Member Function Documentation
abstract Exception interpreter.result.SLogoResult.getException () abstract
returns an exception if found when evaluating the SLogoExpression
Returns
boolean interpreter.result.SLogoResult.getHasError ()
Definition at line 62 of file SLogoResult.java.
References interpreter.result.SLogoResult.myHasError.
Referenced by model.MainModel.interpretSLogoCommand(), and viewcontroller.commands.CommandStatusViewController.update().
abstract List<TransitionState> interpreter.result.SLogoResult.getTransition () abstract
returns a list of transition states from evaluating the SLogoExpression
Returns
Referenced by interpreter.expression.TurtleCommandExpression.applyOperatorAndMerge(), interpreter.expression.ConditionalExpression.applyOperatorAndMerge(), interpreter.expression.DisplayExpression.applyOperatorAndMerge(), interpreter.expression.userdefined.For.evaluate(), interpreter.expression.userdefined.DoTimes.evaluate(), interpreter.expression.userdefined.Repeat.evaluate(), interpreter.expression.syntax.Command.evaluate(), interpreter.expression.userdefined.If.merge(), interpreter.expression.userdefined.IfElse.merge(), interpreter.SLogoResultMerger.mergeAndReturn(), interpreter.expression.MathExpression.mergePreviousResults(), interpreter.expression.singleturtle.ShowTurtle.setNextTransition(), interpreter.expression.singleturtle.HideTurtle.setNextTransition(), interpreter.expression.singleturtle.Left.setNextTransition(), interpreter.expression.singleturtle.Right.setNextTransition(), interpreter.expression.singleturtle.Backward.setNextTransition(), interpreter.expression.singleturtle.PenDown.setNextTransition(), interpreter.expression.singleturtle.SetHeading.setNextTransition(), interpreter.expression.singleturtle.Forward.setNextTransition(), interpreter.expression.singleturtle.PenUp.setNextTransition(), interpreter.expression.singleturtle.SetPosition.setNextTransition(), and model.MainModel.updateModel().
abstract double interpreter.result.SLogoResult.getValue () abstract
returns the integer output from evaluating the SLogoExpression
Returns
Referenced by interpreter.expression.TurtleCommandExpression.applyOperatorAndMerge(), test.MathExpressionTester.arcTanTest(), interpreter.expression.userdefined.MakeVariable.evaluate(), interpreter.expression.userdefined.Repeat.evaluate(), interpreter.expression.syntax.Command.evaluate(), interpreter.expression.conditional.And.hasSatisfiedCondition(), interpreter.expression.conditional.Not.hasSatisfiedCondition(), interpreter.expression.conditional.LessThan.hasSatisfiedCondition(), interpreter.expression.conditional.Equal.hasSatisfiedCondition(), interpreter.expression.conditional.GreaterThan.hasSatisfiedCondition(), interpreter.expression.conditional.NotEqual.hasSatisfiedCondition(), interpreter.SLogoResultMerger.mergeAndReturn(), test.MathExpressionTester.sumTest(), and viewcontroller.commands.CommandStatusViewController.update().
void interpreter.result.SLogoResult.setLabel (String str)
Definition at line 70 of file SLogoResult.java.
Referenced by interpreter.expression.syntax.ListStart.merge().
void interpreter.result.SLogoResult.setValue (double value)
Definition at line 66 of file SLogoResult.java.
Referenced by interpreter.expression.ConditionalExpression.applyOperatorAndMerge(), interpreter.expression.MathExpression.applyOperatorAndMerge(), interpreter.expression.DisplayExpression.applyOperatorAndMerge(), interpreter.expression.syntax.Variable.evaluate(), interpreter.expression.userdefined.For.evaluate(), interpreter.expression.userdefined.DoTimes.evaluate(), interpreter.expression.userdefined.Repeat.evaluate(), interpreter.expression.TurtleQueryExpression.evaluate(), interpreter.expression.syntax.Command.evaluate(), interpreter.expression.userdefined.If.merge(), interpreter.expression.userdefined.IfElse.merge(), interpreter.expression.syntax.ListStart.merge(), interpreter.SLogoResultMerger.mergeAndReturn(), interpreter.expression.singleturtle.ShowTurtle.setNextTransition(), interpreter.expression.singleturtle.Right.setNextTransition(), interpreter.expression.singleturtle.Backward.setNextTransition(), interpreter.expression.singleturtle.Left.setNextTransition(), interpreter.expression.singleturtle.PenDown.setNextTransition(), interpreter.expression.singleturtle.SetHeading.setNextTransition(), interpreter.expression.singleturtle.Forward.setNextTransition(), and interpreter.expression.singleturtle.SetPosition.setNextTransition().
String interpreter.result.SLogoResult.toString ()
Definition at line 74 of file SLogoResult.java.
References interpreter.result.SLogoResult.myLabel.
Member Data Documentation
boolean interpreter.result.SLogoResult.myHasError private
Definition at line 23 of file SLogoResult.java.
Referenced by interpreter.result.SLogoResult.getHasError().
String interpreter.result.SLogoResult.myLabel protected
Definition at line 22 of file SLogoResult.java.
Referenced by interpreter.result.SLogoResult.toString().
ResourceBundle interpreter.result.SLogoResult.myProperties protected
Definition at line 20 of file SLogoResult.java.
List<TransitionState> interpreter.result.SLogoResult.myTransitionStates protected
Definition at line 19 of file SLogoResult.java.
Referenced by interpreter.result.ErrorResult.getTransition(), interpreter.expression.query.QueryResult.getTransition(), interpreter.result.ControlStructureResult.getTransition(), interpreter.expression.conditional.ConditionalResult.getTransition(), interpreter.result.TurtleCommandResult.getTransition(), interpreter.result.UserDefinedResult.getTransition(), interpreter.expression.math.MathResult.getTransition(), interpreter.result.SyntaxResult.getTransition(), and interpreter.result.SyntaxResult.SyntaxResult().
double interpreter.result.SLogoResult.myValue protected
Definition at line 21 of file SLogoResult.java.
Referenced by interpreter.expression.query.QueryResult.getValue(), interpreter.expression.conditional.ConditionalResult.getValue(), interpreter.result.TurtleCommandResult.getValue(), interpreter.expression.math.MathResult.getValue(), interpreter.result.ControlStructureResult.getValue(), interpreter.result.UserDefinedResult.getValue(), interpreter.result.SyntaxResult.getValue(), interpreter.result.TurtleCommandResult.setValue(), interpreter.result.ControlStructureResult.setValue(), and interpreter.result.UserDefinedResult.setValue().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/interpreter/result/SLogoResult.java