slogo_team04: viewcontroller.commands.CommandStatusViewController Class Reference
viewcontroller.commands.CommandStatusViewController Class Reference
Public Member Functions
CommandStatusViewController (int width, int height)
void update (MainModel model)
void updateCommandStatusText (String commandResult)
void applyTranslations ()
Node getNode ()
Public Member Functions inherited from viewcontroller.commands.CommandWindowViewController
CommandWindowViewController (int width, int height)
Private Member Functions
void setStatusLabel ()
Private Attributes
Label myStatusLabel
String myStatusTranslation
Static Private Attributes
static final String STATUS_KEY = "Status"
Additional Inherited Members
Protected Member Functions inherited from viewcontroller.commands.CommandWindowViewController
void setTitle (String titleText)
Protected Attributes inherited from viewcontroller.commands.CommandWindowViewController
BorderPane myPane
VBox myCommandWindowVerticalBox
Label myTitleLabel
Dimension SIZE = new Dimension()
Detailed Description
Display status/return message of evaluated SLogo commands into this ViewController
Author
Abhishek B
Definition at line 21 of file CommandStatusViewController.java.
Constructor & Destructor Documentation
viewcontroller.commands.CommandStatusViewController.CommandStatusViewController (int width, int height)
Definition at line 27 of file CommandStatusViewController.java.
References viewcontroller.commands.CommandStatusViewController.applyTranslations(), viewcontroller.commands.CommandStatusViewController.setStatusLabel(), and viewcontroller.commands.CommandWindowViewController.setTitle().
Member Function Documentation
void viewcontroller.commands.CommandStatusViewController.applyTranslations ()
translate the string using the GUI Reference Library
Implements viewcontroller.ViewController.
Definition at line 68 of file CommandStatusViewController.java.
References viewcontroller.GUIReferenceLibrary.getStringTranslation().
Referenced by viewcontroller.commands.CommandStatusViewController.CommandStatusViewController().
Node viewcontroller.commands.CommandStatusViewController.getNode ()
returns the Node representing the view for a view controller
Returns
Implements viewcontroller.ViewController.
Definition at line 74 of file CommandStatusViewController.java.
References viewcontroller.commands.CommandWindowViewController.myPane.
Referenced by viewcontroller.commands.CommandWindowContainerViewController.placeCommandWindows().
void viewcontroller.commands.CommandStatusViewController.setStatusLabel () private
Set the status Label object with formatting details
Definition at line 37 of file CommandStatusViewController.java.
References viewcontroller.commands.CommandWindowViewController.myCommandWindowVerticalBox.
Referenced by viewcontroller.commands.CommandStatusViewController.CommandStatusViewController().
void viewcontroller.commands.CommandStatusViewController.update (MainModel model)
Display the return messages from the model If the parsing did not function properly (i.e. invalid inputs), then the error message will be displayed.
Implements viewcontroller.MainModelObserver.
Definition at line 50 of file CommandStatusViewController.java.
References interpreter.result.SLogoResult.getHasError(), model.MainModel.getResult(), interpreter.result.SLogoResult.getValue(), and viewcontroller.commands.CommandStatusViewController.updateCommandStatusText().
void viewcontroller.commands.CommandStatusViewController.updateCommandStatusText (String commandResult)
Update the label for the text.
Parameters
commandResult
Definition at line 63 of file CommandStatusViewController.java.
Referenced by viewcontroller.commands.CommandStatusViewController.update().
Member Data Documentation
Label viewcontroller.commands.CommandStatusViewController.myStatusLabel private
Definition at line 23 of file CommandStatusViewController.java.
String viewcontroller.commands.CommandStatusViewController.myStatusTranslation private
Definition at line 25 of file CommandStatusViewController.java.
final String viewcontroller.commands.CommandStatusViewController.STATUS_KEY = "Status" static private
Definition at line 24 of file CommandStatusViewController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/viewcontroller/commands/CommandStatusViewController.java