slogo_team04: turtle.draw.PenTransition Class Reference
turtle.draw.PenTransition Class Reference
Public Member Functions
void setTurtle (Turtle turtle)
void setDistance (double distance)
Public Member Functions inherited from turtle.draw.LinearTransition
void setDistance (double distance)
Public Member Functions inherited from turtle.draw.SLogoTransition
void setTurtle (Turtle turtle)
Protected Member Functions
void setStartPoint ()
void setStartPoint (double x, double y)
void interpolateChanges (double frac)
void performWrappingChanges (Point2D newStartPoint, double frac)
Protected Member Functions inherited from turtle.draw.LinearTransition
LinearTransition ()
void interpolate (double frac)
abstract void interpolateChanges (double frac)
abstract void performWrappingChanges (Point2D newStartPoint, double frac)
void setStartPoint (double x, double y)
abstract void setStartPoint ()
Point2D checkWrapping ()
Protected Member Functions inherited from turtle.draw.SLogoTransition
SLogoTransition ()
Private Member Functions
void createLine ()
void formatLine ()
void drawLine ()
void setEndPoint (double x, double y)
Private Attributes
Line myLine
Additional Inherited Members
Protected Attributes inherited from turtle.draw.LinearTransition
double myStartX
double myStartY
double myX
double myY
double myDistance
double myDoneFrac
boolean myWrappingOccurred
Protected Attributes inherited from turtle.draw.SLogoTransition
Turtle myTurtle
Detailed Description
animation for drawing with the pen of a turtle
Author
Jonathan Tseng
Definition at line 13 of file PenTransition.java.
Member Function Documentation
void turtle.draw.PenTransition.createLine () private
Definition at line 29 of file PenTransition.java.
References turtle.draw.PenTransition.drawLine(), turtle.draw.PenTransition.formatLine(), and turtle.draw.PenTransition.setStartPoint().
Referenced by turtle.draw.PenTransition.performWrappingChanges(), and turtle.draw.PenTransition.setDistance().
void turtle.draw.PenTransition.drawLine () private
Definition at line 43 of file PenTransition.java.
References turtle.draw.Pen.drawLine(), turtle.Turtle.getPen(), turtle.draw.LinearTransition.myDistance, and turtle.draw.SLogoTransition.myTurtle.
Referenced by turtle.draw.PenTransition.createLine().
void turtle.draw.PenTransition.formatLine () private
Definition at line 36 of file PenTransition.java.
References turtle.draw.Pen.getColor(), turtle.draw.Pen.getDash(), turtle.Turtle.getPen(), turtle.draw.Pen.getWidth(), and turtle.draw.SLogoTransition.myTurtle.
Referenced by turtle.draw.PenTransition.createLine().
void turtle.draw.PenTransition.interpolateChanges (double frac) protected
Definition at line 69 of file PenTransition.java.
References turtle.draw.LinearTransition.myDoneFrac, turtle.draw.LinearTransition.myX, turtle.draw.LinearTransition.myY, and turtle.draw.PenTransition.setEndPoint().
void turtle.draw.PenTransition.performWrappingChanges (Point2D newStartPoint, double frac) protected
Definition at line 74 of file PenTransition.java.
References turtle.draw.PenTransition.createLine(), turtle.draw.LinearTransition.myDoneFrac, turtle.draw.LinearTransition.myX, turtle.draw.LinearTransition.myY, turtle.draw.PenTransition.setEndPoint(), and turtle.draw.PenTransition.setStartPoint().
void turtle.draw.PenTransition.setDistance (double distance)
Definition at line 23 of file PenTransition.java.
References turtle.draw.PenTransition.createLine(), turtle.draw.LinearTransition.myStartX, turtle.draw.LinearTransition.myStartY, and turtle.draw.PenTransition.setEndPoint().
Referenced by turtle.draw.TransitionFactory.createForwardTransition().
void turtle.draw.PenTransition.setEndPoint (double x, double y) private
Definition at line 63 of file PenTransition.java.
Referenced by turtle.draw.PenTransition.interpolateChanges(), turtle.draw.PenTransition.performWrappingChanges(), and turtle.draw.PenTransition.setDistance().
void turtle.draw.PenTransition.setStartPoint () protected
Definition at line 50 of file PenTransition.java.
References turtle.Turtle.getTurtle(), and turtle.draw.SLogoTransition.myTurtle.
Referenced by turtle.draw.PenTransition.createLine(), and turtle.draw.PenTransition.performWrappingChanges().
void turtle.draw.PenTransition.setStartPoint (double x, double y) protected
Definition at line 57 of file PenTransition.java.
References turtle.draw.LinearTransition.myStartX, and turtle.draw.LinearTransition.myStartY.
void turtle.draw.PenTransition.setTurtle (Turtle turtle)
Definition at line 18 of file PenTransition.java.
Referenced by turtle.draw.TransitionFactory.createForwardTransition().
Member Data Documentation
Line turtle.draw.PenTransition.myLine private
Definition at line 15 of file PenTransition.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/turtle/draw/PenTransition.java