slogo_team04: viewcontroller.commands.UserDefinedMethodsViewController Class Reference
viewcontroller.commands.UserDefinedMethodsViewController Class Reference
Public Member Functions
UserDefinedMethodsViewController (int width, int height, CommandWindowContainerViewController commandWindowContainer)
void applyTranslations ()
Node getNode ()
void update (MainModel model)
Public Member Functions inherited from viewcontroller.commands.CommandClickableListWindowViewController
CommandClickableListWindowViewController (int width, int height)
Public Member Functions inherited from viewcontroller.commands.CommandListWindowViewController
CommandListWindowViewController (int width, int height)
Public Member Functions inherited from viewcontroller.commands.CommandWindowViewController
CommandWindowViewController (int width, int height)
Private Attributes
String myUserTranslation
Static Private Attributes
static final String User_KEY = "UserMethods"
Additional Inherited Members
Protected Member Functions inherited from viewcontroller.commands.CommandClickableListWindowViewController
void addCommand (String commandLabelString)
Protected Member Functions inherited from viewcontroller.commands.CommandListWindowViewController
void updateScroller ()
Protected Member Functions inherited from viewcontroller.commands.CommandWindowViewController
void setTitle (String titleText)
Protected Attributes inherited from viewcontroller.commands.CommandClickableListWindowViewController
CommandWindowContainerViewController myCommandWindowContainer
Protected Attributes inherited from viewcontroller.commands.CommandListWindowViewController
ScrollPane myScrollPane
VBox myListVerticalBox
Protected Attributes inherited from viewcontroller.commands.CommandWindowViewController
BorderPane myPane
VBox myCommandWindowVerticalBox
Label myTitleLabel
Dimension SIZE = new Dimension()
Detailed Description
ViewController contained User-Defined Method string names
Author
Abhishek B
Definition at line 16 of file UserDefinedMethodsViewController.java.
Constructor & Destructor Documentation
viewcontroller.commands.UserDefinedMethodsViewController.UserDefinedMethodsViewController (int width, int height, CommandWindowContainerViewController commandWindowContainer)
Definition at line 21 of file UserDefinedMethodsViewController.java.
References viewcontroller.commands.UserDefinedMethodsViewController.applyTranslations(), viewcontroller.commands.CommandClickableListWindowViewController.myCommandWindowContainer, and viewcontroller.commands.CommandWindowViewController.setTitle().
Member Function Documentation
void viewcontroller.commands.UserDefinedMethodsViewController.applyTranslations ()
translate the string using the GUI Reference Library
Implements viewcontroller.ViewController.
Definition at line 28 of file UserDefinedMethodsViewController.java.
References viewcontroller.GUIReferenceLibrary.getStringTranslation().
Referenced by viewcontroller.commands.UserDefinedMethodsViewController.UserDefinedMethodsViewController().
Node viewcontroller.commands.UserDefinedMethodsViewController.getNode ()
returns the Node representing the view for a view controller
Returns
Implements viewcontroller.ViewController.
Definition at line 33 of file UserDefinedMethodsViewController.java.
References viewcontroller.commands.CommandWindowViewController.myPane.
Referenced by viewcontroller.commands.CommandWindowContainerViewController.placeUserDefinedBoxes().
void viewcontroller.commands.UserDefinedMethodsViewController.update (MainModel model)
Update this view by replacing the entire list from the model
Implements viewcontroller.MainModelObserver.
Definition at line 40 of file UserDefinedMethodsViewController.java.
References viewcontroller.commands.CommandClickableListWindowViewController.addCommand(), model.UserDefinedCommandsModel.getAllDefinedCommands(), model.MainModel.getUserDefinedMethods(), and viewcontroller.commands.CommandListWindowViewController.myListVerticalBox.
Member Data Documentation
String viewcontroller.commands.UserDefinedMethodsViewController.myUserTranslation private
Definition at line 19 of file UserDefinedMethodsViewController.java.
final String viewcontroller.commands.UserDefinedMethodsViewController.User_KEY = "UserMethods" static private
Definition at line 18 of file UserDefinedMethodsViewController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/viewcontroller/commands/UserDefinedMethodsViewController.java