slogo_team04: turtle.draw.TransitionFactory Class Reference
turtle.draw.TransitionFactory Class Reference
Public Member Functions
TransitionFactory ()
ParallelTransition createAnimation (Turtle turtle, List< TransitionState > states)
Private Member Functions
Transition createTurtleTransition (Turtle turtle, TransitionState state)
TurnTransition createTurnTransition (Turtle turtle, TransitionState state)
ParallelTransition createForwardTransition (Turtle turtle, TransitionState state)
Detailed Description
factory for creating animations given a turtle and transition states
Author
Jonathan Tseng
Definition at line 16 of file TransitionFactory.java.
Constructor & Destructor Documentation
turtle.draw.TransitionFactory.TransitionFactory ()
Definition at line 18 of file TransitionFactory.java.
Member Function Documentation
ParallelTransition turtle.draw.TransitionFactory.createAnimation (Turtle turtle, List< TransitionState > states)
Definition at line 22 of file TransitionFactory.java.
References turtle.draw.TransitionFactory.createTurtleTransition().
Referenced by turtle.Turtle.createAnimation().
ParallelTransition turtle.draw.TransitionFactory.createForwardTransition (Turtle turtle, TransitionState state) private
Definition at line 50 of file TransitionFactory.java.
References transitionstate.TransitionState.getMove(), turtle.Turtle.getPen(), turtle.draw.Pen.getPenDown(), turtle.draw.PenTransition.setDistance(), turtle.draw.LinearTransition.setDistance(), turtle.draw.MoveTransition.setTurtle(), and turtle.draw.PenTransition.setTurtle().
Referenced by turtle.draw.TransitionFactory.createTurtleTransition().
TurnTransition turtle.draw.TransitionFactory.createTurnTransition (Turtle turtle, TransitionState state) private
Definition at line 42 of file TransitionFactory.java.
References transitionstate.TransitionState.getRotateClockwise(), transitionstate.TransitionState.getRotateCounterClockwise(), turtle.draw.TurnTransition.setTurn(), and turtle.draw.SLogoTransition.setTurtle().
Referenced by turtle.draw.TransitionFactory.createTurtleTransition().
Transition turtle.draw.TransitionFactory.createTurtleTransition (Turtle turtle, TransitionState state) private
Definition at line 33 of file TransitionFactory.java.
References turtle.draw.TransitionFactory.createForwardTransition(), turtle.draw.TransitionFactory.createTurnTransition(), and turtle.Turtle.updateVisualState().
Referenced by turtle.draw.TransitionFactory.createAnimation().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/turtle/draw/TransitionFactory.java