slogo_team04: interpreter.expression.SLogoExpression Interface Reference
interpreter.expression.SLogoExpression Interface Reference
Public Member Functions
abstract void loadArguments (Deque< SLogoExpression > args) throws SLogoParsingException, NullPointerException
abstract void setNumArgs (int value)
abstract void loadLibrary (CommandReferenceLibrary library)
abstract void loadModel (MainModel model)
abstract int getNumArgs ()
abstract SLogoResult evaluate ()
abstract void setValue (String value)
abstract String getValue ()
Detailed Description
Interface that SLogo Expressions must implement
Author
Jonathan Tseng and William Chang
Definition at line 16 of file SLogoExpression.java.
Member Function Documentation
abstract SLogoResult interpreter.expression.SLogoExpression.evaluate () abstract
evaluates the expression and returns an SLogoResult
Returns
Exceptions
SLogoParsingException
Implemented in interpreter.expression.DisplayExpression, interpreter.expression.MathExpression, interpreter.expression.ConditionalExpression, interpreter.expression.UserDefinedExpression, interpreter.expression.SyntaxExpression, interpreter.expression.TurtleCommandExpression, interpreter.expression.syntax.Command, interpreter.expression.ErrorExpression, interpreter.expression.syntax.ListStart, interpreter.expression.TurtleQueryExpression, interpreter.expression.syntax.Constant, interpreter.expression.userdefined.DoTimes, interpreter.expression.userdefined.Repeat, interpreter.expression.userdefined.For, interpreter.expression.userdefined.MakeUserInstruction, interpreter.expression.userdefined.MakeVariable, interpreter.expression.syntax.GroupStart, interpreter.expression.syntax.ListEnd, interpreter.expression.syntax.Variable, interpreter.expression.userdefined.IfElse, and interpreter.expression.userdefined.If.
Referenced by interpreter.expression.userdefined.IfElse.evaluate(), interpreter.expression.userdefined.For.evaluate(), interpreter.expression.userdefined.Repeat.evaluate(), interpreter.expression.userdefined.DoTimes.evaluate(), and interpreter.expression.syntax.Command.evaluate().
abstract int interpreter.expression.SLogoExpression.getNumArgs () abstract
Gets the number of arguments for the expression.
Returns
Implemented in interpreter.expression.MathExpression, interpreter.expression.ConditionalExpression, interpreter.expression.TurtleCommandExpression, interpreter.expression.SyntaxExpression, interpreter.expression.UserDefinedExpression, interpreter.expression.TurtleQueryExpression, interpreter.expression.DisplayExpression, interpreter.expression.ErrorExpression, and interpreter.expression.syntax.GroupStart.
abstract String interpreter.expression.SLogoExpression.getValue () abstract
Gets the String value of the expression
Returns
value
Implemented in interpreter.expression.MathExpression, interpreter.expression.ConditionalExpression, interpreter.expression.TurtleCommandExpression, interpreter.expression.SyntaxExpression, interpreter.expression.UserDefinedExpression, interpreter.expression.TurtleQueryExpression, interpreter.expression.ErrorExpression, interpreter.expression.DisplayExpression, interpreter.expression.syntax.GroupStart, and interpreter.expression.syntax.Constant.
abstract void interpreter.expression.SLogoExpression.loadArguments (Deque< SLogoExpression > args) throws SLogoParsingException, NullPointerException abstract
loads the list of expressions as arguments for the expression
Parameters
args
Exceptions
NullPointerException
SLogoParsingException
Implemented in interpreter.expression.DisplayExpression, interpreter.expression.MathExpression, interpreter.expression.SyntaxExpression, interpreter.expression.UserDefinedExpression, interpreter.expression.ConditionalExpression, interpreter.expression.syntax.Command, interpreter.expression.TurtleCommandExpression, interpreter.expression.syntax.ListStart, interpreter.expression.TurtleQueryExpression, interpreter.expression.ErrorExpression, and interpreter.expression.syntax.GroupStart.
Referenced by interpreter.Parser.loadAllExpressionParameters().
abstract void interpreter.expression.SLogoExpression.loadLibrary (CommandReferenceLibrary library) abstract
Sets the library from the CommandReferenceLibrary
Parameters
library
Implemented in interpreter.expression.DisplayExpression, interpreter.expression.MathExpression, interpreter.expression.ConditionalExpression, interpreter.expression.TurtleCommandExpression, interpreter.expression.SyntaxExpression, interpreter.expression.UserDefinedExpression, interpreter.expression.syntax.GroupStart, interpreter.expression.TurtleQueryExpression, and interpreter.expression.ErrorExpression.
Referenced by interpreter.SLogoExpressionFactory.initializeExpression().
abstract void interpreter.expression.SLogoExpression.loadModel (MainModel model) abstract
Loads the model
Parameters
mode
Implemented in interpreter.expression.DisplayExpression, interpreter.expression.MathExpression, interpreter.expression.ConditionalExpression, interpreter.expression.TurtleCommandExpression, interpreter.expression.SyntaxExpression, interpreter.expression.UserDefinedExpression, interpreter.expression.ErrorExpression, interpreter.expression.TurtleQueryExpression, and interpreter.expression.syntax.GroupStart.
Referenced by interpreter.SLogoExpressionFactory.initializeExpression().
abstract void interpreter.expression.SLogoExpression.setNumArgs (int value) abstract
Sets the number of arguments
Parameters
value
Implemented in interpreter.expression.MathExpression, interpreter.expression.ConditionalExpression, interpreter.expression.DisplayExpression, interpreter.expression.SyntaxExpression, interpreter.expression.UserDefinedExpression, interpreter.expression.syntax.GroupStart, interpreter.expression.TurtleCommandExpression, interpreter.expression.ErrorExpression, and interpreter.expression.TurtleQueryExpression.
Referenced by interpreter.SLogoExpressionFactory.initializeExpression().
abstract void interpreter.expression.SLogoExpression.setValue (String value) abstract
Sets the value of the expression
Parameters
value
Implemented in interpreter.expression.MathExpression, interpreter.expression.ConditionalExpression, interpreter.expression.TurtleCommandExpression, interpreter.expression.SyntaxExpression, interpreter.expression.UserDefinedExpression, interpreter.expression.TurtleQueryExpression, interpreter.expression.ErrorExpression, interpreter.expression.DisplayExpression, interpreter.expression.syntax.GroupStart, interpreter.expression.syntax.Constant, and interpreter.expression.syntax.ListEnd.
Referenced by interpreter.SLogoExpressionFactory.checkTypeAndInitialize().
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/interpreter/expression/SLogoExpression.java