slogo_team04: application.MessageBox Class Reference
application.MessageBox Class Reference
Public Member Functions
MessageBox (String message)
void show ()
Private Member Functions
void createMessageBox ()
void createMessageText ()
void createOkayButton ()
Private Attributes
Stage myStage
String myMessage
VBox myMessageBox
Text myMessageText
Button myOkayButton
Static Private Attributes
static final int MESSAGE_SPACING = 10
static final int MESSAGE_PADDING = 20
Detailed Description
creates a message box in another stage to show to the user
Author
Jonathan Tseng
Definition at line 23 of file MessageBox.java.
Constructor & Destructor Documentation
application.MessageBox.MessageBox (String message)
creates instance of message box class to show the associated message
Parameters
message
Definition at line 38 of file MessageBox.java.
Member Function Documentation
void application.MessageBox.createMessageBox () private
creates the VBox to hold the message dialog
Definition at line 59 of file MessageBox.java.
References application.MessageBox.createMessageText(), and application.MessageBox.createOkayButton().
Referenced by application.MessageBox.show().
void application.MessageBox.createMessageText () private
creates the message text for the message dialog
Definition at line 72 of file MessageBox.java.
Referenced by application.MessageBox.createMessageBox().
void application.MessageBox.createOkayButton () private
creates the okay button for the message dialog
Definition at line 80 of file MessageBox.java.
Referenced by application.MessageBox.createMessageBox().
void application.MessageBox.show ()
shows the messsage dialog
Definition at line 45 of file MessageBox.java.
References application.MessageBox.createMessageBox().
Referenced by viewcontroller.View.showMessage().
Member Data Documentation
final int application.MessageBox.MESSAGE_PADDING = 20 static private
Definition at line 25 of file MessageBox.java.
final int application.MessageBox.MESSAGE_SPACING = 10 static private
Definition at line 24 of file MessageBox.java.
String application.MessageBox.myMessage private
Definition at line 28 of file MessageBox.java.
VBox application.MessageBox.myMessageBox private
Definition at line 29 of file MessageBox.java.
Text application.MessageBox.myMessageText private
Definition at line 30 of file MessageBox.java.
Button application.MessageBox.myOkayButton private
Definition at line 31 of file MessageBox.java.
Stage application.MessageBox.myStage private
Definition at line 27 of file MessageBox.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/application/MessageBox.java