slogo_team04: viewcontroller.turtlegrid.GridViewController Class Reference
viewcontroller.turtlegrid.GridViewController Class Reference
Public Member Functions
GridViewController (TurtleWindowViewController parent)
Node getNode ()
void update (MainModel model)
void toggleGridLines ()
void applyTranslations ()
Static Public Attributes
static final Dimension SIZE
Private Member Functions
void setUpGridKeyListeners ()
void listenKeys (KeyEvent event)
void forwardKeyPressed (boolean forward)
void rightKeyPressed (boolean clockwise)
void createBackground ()
void setBackgroundColor (Color color)
void updateTurtles (List< Turtle > turtles)
void fixGridBackground (double pad)
void moveTurtles (ParallelTransition animation)
Private Attributes
TurtleWindowViewController myParent
GridLines myGridLines
Group myGrid
Rectangle myGridBackground
List< Turtle > myTurtles
Static Private Attributes
static final String FORWARD_KEY = "Forward"
static final String RIGHT_KEY = "Right"
static final double KEY_FORWARD_VALUE = 25
static final double KEY_RIGHT_VALUE = 15
Detailed Description
View Controller for Grid view that has the turtles
Author
Jonathan Tseng
Definition at line 24 of file GridViewController.java.
Constructor & Destructor Documentation
viewcontroller.turtlegrid.GridViewController.GridViewController (TurtleWindowViewController parent)
Definition at line 41 of file GridViewController.java.
References viewcontroller.turtlegrid.GridViewController.createBackground(), and viewcontroller.turtlegrid.GridViewController.setUpGridKeyListeners().
Member Function Documentation
void viewcontroller.turtlegrid.GridViewController.applyTranslations ()
translate the string using the GUI Reference Library
Implements viewcontroller.ViewController.
Definition at line 140 of file GridViewController.java.
void viewcontroller.turtlegrid.GridViewController.createBackground () private
Definition at line 72 of file GridViewController.java.
References viewcontroller.View.BACKGROUND_COLOR.
Referenced by viewcontroller.turtlegrid.GridViewController.GridViewController().
void viewcontroller.turtlegrid.GridViewController.fixGridBackground (double pad) private
Definition at line 117 of file GridViewController.java.
References viewcontroller.turtlegrid.GridLines.changeSize().
Referenced by viewcontroller.turtlegrid.GridViewController.updateTurtles().
void viewcontroller.turtlegrid.GridViewController.forwardKeyPressed (boolean forward) private
Definition at line 62 of file GridViewController.java.
References viewcontroller.turtlegrid.GridViewController.KEY_FORWARD_VALUE, and viewcontroller.turtlegrid.TurtleWindowViewController.passSLogoCommand().
Referenced by viewcontroller.turtlegrid.GridViewController.listenKeys().
Node viewcontroller.turtlegrid.GridViewController.getNode ()
returns the Node representing the view for a view controller
Returns
Implements viewcontroller.ViewController.
Definition at line 84 of file GridViewController.java.
References viewcontroller.turtlegrid.GridViewController.myGrid.
Referenced by viewcontroller.turtlegrid.TurtleWindowViewController.placeGridView().
void viewcontroller.turtlegrid.GridViewController.listenKeys (KeyEvent event) private
Definition at line 54 of file GridViewController.java.
References viewcontroller.turtlegrid.GridViewController.forwardKeyPressed(), and viewcontroller.turtlegrid.GridViewController.rightKeyPressed().
void viewcontroller.turtlegrid.GridViewController.moveTurtles (ParallelTransition animation) private
Definition at line 129 of file GridViewController.java.
Referenced by viewcontroller.turtlegrid.GridViewController.update().
void viewcontroller.turtlegrid.GridViewController.rightKeyPressed (boolean clockwise) private
Definition at line 67 of file GridViewController.java.
References viewcontroller.turtlegrid.GridViewController.KEY_RIGHT_VALUE, and viewcontroller.turtlegrid.TurtleWindowViewController.passSLogoCommand().
Referenced by viewcontroller.turtlegrid.GridViewController.listenKeys().
void viewcontroller.turtlegrid.GridViewController.setBackgroundColor (Color color) private
Definition at line 79 of file GridViewController.java.
Referenced by viewcontroller.turtlegrid.GridViewController.update().
void viewcontroller.turtlegrid.GridViewController.setUpGridKeyListeners () private
Definition at line 49 of file GridViewController.java.
Referenced by viewcontroller.turtlegrid.GridViewController.GridViewController().
void viewcontroller.turtlegrid.GridViewController.toggleGridLines ()
Definition at line 98 of file GridViewController.java.
References viewcontroller.turtlegrid.GridLines.toggle().
Referenced by viewcontroller.turtlegrid.TurtleWindowViewController.toggleGridLines().
void viewcontroller.turtlegrid.GridViewController.update (MainModel model)
Extract the appropriate data from the model to update the view
Parameters
model - MainModel
Implements viewcontroller.MainModelObserver.
Definition at line 89 of file GridViewController.java.
References model.MainModel.getAnimation(), model.MainModel.getBackgroundColor(), model.MainModel.getFailedParse(), model.MainModel.getTurtles(), model.MainModel.isTurtleAdded(), viewcontroller.turtlegrid.GridViewController.moveTurtles(), viewcontroller.turtlegrid.GridViewController.setBackgroundColor(), and viewcontroller.turtlegrid.GridViewController.updateTurtles().
void viewcontroller.turtlegrid.GridViewController.updateTurtles (List< Turtle > turtles) private
Definition at line 102 of file GridViewController.java.
References viewcontroller.turtlegrid.GridViewController.fixGridBackground().
Referenced by viewcontroller.turtlegrid.GridViewController.update().
Member Data Documentation
final String viewcontroller.turtlegrid.GridViewController.FORWARD_KEY = "Forward" static private
Definition at line 26 of file GridViewController.java.
final double viewcontroller.turtlegrid.GridViewController.KEY_FORWARD_VALUE = 25 static private
Definition at line 28 of file GridViewController.java.
Referenced by viewcontroller.turtlegrid.GridViewController.forwardKeyPressed().
final double viewcontroller.turtlegrid.GridViewController.KEY_RIGHT_VALUE = 15 static private
Definition at line 29 of file GridViewController.java.
Referenced by viewcontroller.turtlegrid.GridViewController.rightKeyPressed().
Group viewcontroller.turtlegrid.GridViewController.myGrid private
Definition at line 37 of file GridViewController.java.
Referenced by viewcontroller.turtlegrid.GridViewController.getNode().
Rectangle viewcontroller.turtlegrid.GridViewController.myGridBackground private
Definition at line 38 of file GridViewController.java.
GridLines viewcontroller.turtlegrid.GridViewController.myGridLines private
Definition at line 36 of file GridViewController.java.
TurtleWindowViewController viewcontroller.turtlegrid.GridViewController.myParent private
Definition at line 35 of file GridViewController.java.
List<Turtle> viewcontroller.turtlegrid.GridViewController.myTurtles private
Definition at line 39 of file GridViewController.java.
final String viewcontroller.turtlegrid.GridViewController.RIGHT_KEY = "Right" static private
Definition at line 27 of file GridViewController.java.
final Dimension viewcontroller.turtlegrid.GridViewController.SIZE static
Initial value:
= new Dimension(
            TurtleWindowViewController.SIZE.width * 12 / 10,
            TurtleWindowViewController.SIZE.height * 9 / 10)
Definition at line 31 of file GridViewController.java.
Referenced by turtle.draw.LinearTransition.checkWrapping(), turtle.Turtle.getX(), and turtle.Turtle.getY().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/viewcontroller/turtlegrid/GridViewController.java