slogo_team04: interpreter.expression.syntax.ListStart Class Reference
interpreter.expression.syntax.ListStart Class Reference
Public Member Functions
ListStart ()
void loadArguments (Deque< SLogoExpression > args) throws SLogoParsingException, NullPointerException
SLogoResult evaluate ()
Public Member Functions inherited from interpreter.expression.SyntaxExpression
SyntaxExpression ()
void setNumArgs (int value)
void loadLibrary (CommandReferenceLibrary library)
void loadModel (MainModel model)
void loadArguments (Deque< SLogoExpression > args) throws SLogoParsingException, NullPointerException
int getNumArgs ()
SLogoResult evaluate ()
void setValue (String value)
String getValue ()
Private Member Functions
SLogoResult merge (Deque< SLogoResult > results)
Private Attributes
int mySize
Additional Inherited Members
Protected Attributes inherited from interpreter.expression.SyntaxExpression
CommandReferenceLibrary myLibrary
MainModel myModel
int myNumArgs
Deque< SLogoExpression > myArguments
String myValue
Detailed Description
Author
Will Chang
Definition at line 17 of file ListStart.java.
Constructor & Destructor Documentation
interpreter.expression.syntax.ListStart.ListStart ()
Definition at line 20 of file ListStart.java.
Member Function Documentation
SLogoResult interpreter.expression.syntax.ListStart.evaluate ()
evaluates the expression and returns an SLogoResult
Returns
Exceptions
SLogoParsingException
Implements interpreter.expression.SLogoExpression.
Definition at line 40 of file ListStart.java.
References interpreter.expression.syntax.ListStart.merge(), and interpreter.expression.SyntaxExpression.myArguments.
void interpreter.expression.syntax.ListStart.loadArguments (Deque< SLogoExpression > args) throws SLogoParsingException, NullPointerException
loads the list of expressions as arguments for the expression
Parameters
args
Exceptions
NullPointerException
SLogoParsingException
Implements interpreter.expression.SLogoExpression.
Definition at line 25 of file ListStart.java.
References interpreter.expression.SyntaxExpression.myArguments.
SLogoResult interpreter.expression.syntax.ListStart.merge (Deque< SLogoResult > results) private
Definition at line 50 of file ListStart.java.
References interpreter.result.SyntaxResult.getTransition(), interpreter.expression.SyntaxExpression.myArguments, interpreter.expression.SyntaxExpression.myValue, interpreter.result.SyntaxResult.setGroupedExpressions(), interpreter.result.SLogoResult.setLabel(), and interpreter.result.SLogoResult.setValue().
Referenced by interpreter.expression.syntax.ListStart.evaluate().
Member Data Documentation
int interpreter.expression.syntax.ListStart.mySize private
Definition at line 18 of file ListStart.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/interpreter/expression/syntax/ListStart.java