slogo_team04: interpreter.expression.TurtleCommandExpression Class Reference
interpreter.expression.TurtleCommandExpression Class Reference abstract
Public Member Functions
TurtleCommandExpression ()
void setNumArgs (int value)
void loadArguments (Deque< SLogoExpression > args) throws SLogoParsingException, NullPointerException
void loadLibrary (CommandReferenceLibrary library)
void loadModel (MainModel model)
SLogoResult evaluate ()
int getNumArgs ()
void setValue (String value)
String getValue ()
Protected Member Functions
SLogoResult applyOperatorAndMerge (Deque< SLogoResult > results)
abstract void setNextTransition (SLogoResult myResult, Deque< Double > value)
Protected Attributes
Deque< SLogoExpression > myArguments
int myNumArgs
CommandReferenceLibrary myLibrary
MainModel myModel
String myValue
Detailed Description
superclass for SLogoExpressions that are commands
Author
Will Chang
Definition at line 14 of file TurtleCommandExpression.java.
Constructor & Destructor Documentation
interpreter.expression.TurtleCommandExpression.TurtleCommandExpression ()
Definition at line 20 of file TurtleCommandExpression.java.
Member Function Documentation
SLogoResult interpreter.expression.TurtleCommandExpression.applyOperatorAndMerge (Deque< SLogoResult > results) protected
Definition at line 50 of file TurtleCommandExpression.java.
References interpreter.result.SLogoResult.getTransition(), interpreter.result.SLogoResult.getValue(), and interpreter.expression.TurtleCommandExpression.setNextTransition().
Referenced by interpreter.expression.TurtleCommandExpression.evaluate().
SLogoResult interpreter.expression.TurtleCommandExpression.evaluate ()
evaluates the expression and returns an SLogoResult
Returns
Exceptions
SLogoParsingException
Implements interpreter.expression.SLogoExpression.
Definition at line 43 of file TurtleCommandExpression.java.
References interpreter.expression.TurtleCommandExpression.applyOperatorAndMerge().
int interpreter.expression.TurtleCommandExpression.getNumArgs ()
Gets the number of arguments for the expression.
Returns
Implements interpreter.expression.SLogoExpression.
Definition at line 63 of file TurtleCommandExpression.java.
References interpreter.expression.TurtleCommandExpression.myNumArgs.
String interpreter.expression.TurtleCommandExpression.getValue ()
Gets the String value of the expression
Returns
value
Implements interpreter.expression.SLogoExpression.
Definition at line 71 of file TurtleCommandExpression.java.
References interpreter.expression.TurtleCommandExpression.myValue.
void interpreter.expression.TurtleCommandExpression.loadArguments (Deque< SLogoExpression > args) throws SLogoParsingException, NullPointerException
loads the list of expressions as arguments for the expression
Parameters
args
Exceptions
NullPointerException
SLogoParsingException
Implements interpreter.expression.SLogoExpression.
Definition at line 28 of file TurtleCommandExpression.java.
References interpreter.expression.TurtleCommandExpression.myNumArgs.
void interpreter.expression.TurtleCommandExpression.loadLibrary (CommandReferenceLibrary library)
Sets the library from the CommandReferenceLibrary
Parameters
library
Implements interpreter.expression.SLogoExpression.
Definition at line 35 of file TurtleCommandExpression.java.
void interpreter.expression.TurtleCommandExpression.loadModel (MainModel model)
Loads the model
Parameters
mode
Implements interpreter.expression.SLogoExpression.
Definition at line 39 of file TurtleCommandExpression.java.
abstract void interpreter.expression.TurtleCommandExpression.setNextTransition (SLogoResult myResult, Deque< Double > value) abstract protected
Referenced by interpreter.expression.TurtleCommandExpression.applyOperatorAndMerge().
void interpreter.expression.TurtleCommandExpression.setNumArgs (int value)
Sets the number of arguments
Parameters
value
Implements interpreter.expression.SLogoExpression.
Definition at line 24 of file TurtleCommandExpression.java.
void interpreter.expression.TurtleCommandExpression.setValue (String value)
Sets the value of the expression
Parameters
value
Implements interpreter.expression.SLogoExpression.
Definition at line 67 of file TurtleCommandExpression.java.
Member Data Documentation
Deque<SLogoExpression> interpreter.expression.TurtleCommandExpression.myArguments protected
Definition at line 15 of file TurtleCommandExpression.java.
CommandReferenceLibrary interpreter.expression.TurtleCommandExpression.myLibrary protected
Definition at line 17 of file TurtleCommandExpression.java.
MainModel interpreter.expression.TurtleCommandExpression.myModel protected
Definition at line 18 of file TurtleCommandExpression.java.
Referenced by interpreter.expression.singleturtle.SetHeading.setNextTransition(), and interpreter.expression.singleturtle.SetPosition.setNextTransition().
int interpreter.expression.TurtleCommandExpression.myNumArgs protected
Definition at line 16 of file TurtleCommandExpression.java.
Referenced by interpreter.expression.TurtleCommandExpression.getNumArgs(), and interpreter.expression.TurtleCommandExpression.loadArguments().
String interpreter.expression.TurtleCommandExpression.myValue protected
Definition at line 19 of file TurtleCommandExpression.java.
Referenced by interpreter.expression.TurtleCommandExpression.getValue().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/interpreter/expression/TurtleCommandExpression.java