slogo_team04: turtle.UserChosenTurtleImage Class Reference
turtle.UserChosenTurtleImage Class Reference
Public Member Functions
UserChosenTurtleImage (Image image)
double getRadius ()
Public Member Functions inherited from turtle.TurtleImage
TurtleImage ()
boolean isSelected ()
void toggleSelection ()
void setSelection (boolean isSelected)
abstract double getRadius ()
void updateVisible (boolean visible)
Protected Member Functions
void selectedChanged ()
Protected Member Functions inherited from turtle.TurtleImage
abstract void selectedChanged ()
Private Member Functions
void createImageView (Image image)
void createBorder ()
Private Attributes
ImageView myImageView
Rectangle myBorder
Static Private Attributes
static final double myBorderWidth = 5
Additional Inherited Members
Static Public Member Functions inherited from turtle.TurtleImage
static void setSize (Dimension size)
Protected Attributes inherited from turtle.TurtleImage
boolean myIsSelected
Static Protected Attributes inherited from turtle.TurtleImage
static final Color ourSelectedColor = Color.GOLD
static Dimension ourSize
Detailed Description
turtle image to represent imageview for image loaded by user
Author
Jonathan Tseng
Definition at line 13 of file UserChosenTurtleImage.java.
Constructor & Destructor Documentation
turtle.UserChosenTurtleImage.UserChosenTurtleImage (Image image)
Definition at line 19 of file UserChosenTurtleImage.java.
References turtle.UserChosenTurtleImage.createImageView(), turtle.UserChosenTurtleImage.myBorderWidth, and turtle.TurtleImage.ourSize.
Member Function Documentation
void turtle.UserChosenTurtleImage.createBorder () private
Definition at line 34 of file UserChosenTurtleImage.java.
References turtle.UserChosenTurtleImage.myBorderWidth, and turtle.TurtleImage.ourSize.
Referenced by turtle.UserChosenTurtleImage.createImageView().
void turtle.UserChosenTurtleImage.createImageView (Image image) private
Definition at line 27 of file UserChosenTurtleImage.java.
References turtle.UserChosenTurtleImage.createBorder().
Referenced by turtle.UserChosenTurtleImage.UserChosenTurtleImage().
double turtle.UserChosenTurtleImage.getRadius ()
Definition at line 49 of file UserChosenTurtleImage.java.
References turtle.UserChosenTurtleImage.myBorderWidth, and turtle.TurtleImage.ourSize.
void turtle.UserChosenTurtleImage.selectedChanged () protected
Definition at line 40 of file UserChosenTurtleImage.java.
References turtle.TurtleImage.myIsSelected, and turtle.TurtleImage.ourSelectedColor.
Member Data Documentation
Rectangle turtle.UserChosenTurtleImage.myBorder private
Definition at line 16 of file UserChosenTurtleImage.java.
final double turtle.UserChosenTurtleImage.myBorderWidth = 5 static private
Definition at line 17 of file UserChosenTurtleImage.java.
Referenced by turtle.UserChosenTurtleImage.createBorder(), turtle.UserChosenTurtleImage.getRadius(), and turtle.UserChosenTurtleImage.UserChosenTurtleImage().
ImageView turtle.UserChosenTurtleImage.myImageView private
Definition at line 15 of file UserChosenTurtleImage.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/turtle/UserChosenTurtleImage.java