slogo_team04: turtle.draw.Pen Class Reference
turtle.draw.Pen Class Reference
Public Member Functions
Pen (Node turtle)
Pen (Node turtle, Color color, double width)
void setColor (Color color)
void setWidth (double width)
Color getColor ()
double getWidth ()
List< Double > getDash ()
void setDash (List< Double > dash)
void attachGrid (Group grid)
void drawLine (Line line)
List< Line > getDrawnLines ()
void update (boolean penDown)
void update (PenChange penChange)
boolean getPenDown ()
Private Attributes
Color myColor
double myWidth
Group myGrid
boolean myPenDown
Node myTurtleNode
List< Line > myDrawnLines
List< Double > myDash
Static Private Attributes
static double ourDefaultWidth = 5
static Color ourDefaultColor = Color.BLACK
Detailed Description
class for creating paths drawn stores state about a turtle's pen
Author
Jonathan Tseng
Definition at line 18 of file Pen.java.
Constructor & Destructor Documentation
turtle.draw.Pen.Pen (Node turtle)
Definition at line 33 of file Pen.java.
References turtle.draw.Pen.ourDefaultColor, and turtle.draw.Pen.ourDefaultWidth.
turtle.draw.Pen.Pen (Node turtle, Color color, double width)
Definition at line 37 of file Pen.java.
References turtle.draw.Pen.ourDefaultColor, and turtle.draw.Pen.ourDefaultWidth.
Member Function Documentation
void turtle.draw.Pen.attachGrid (Group grid)
attaches the grid on which the pen is drawing
Parameters
grid
Definition at line 74 of file Pen.java.
void turtle.draw.Pen.drawLine (Line line)
Definition at line 78 of file Pen.java.
Referenced by turtle.draw.PenTransition.drawLine().
Color turtle.draw.Pen.getColor ()
Definition at line 54 of file Pen.java.
References turtle.draw.Pen.myColor.
Referenced by turtle.draw.PenTransition.formatLine(), and turtle.SerialisableTurtle.SerialisableTurtle().
List<Double> turtle.draw.Pen.getDash ()
Definition at line 62 of file Pen.java.
References turtle.draw.Pen.myDash.
Referenced by turtle.draw.PenTransition.formatLine().
List<Line> turtle.draw.Pen.getDrawnLines ()
Definition at line 87 of file Pen.java.
References turtle.draw.Pen.myDrawnLines.
Referenced by turtle.SerialisableTurtle.SerialisableTurtle().
boolean turtle.draw.Pen.getPenDown ()
Definition at line 105 of file Pen.java.
References turtle.draw.Pen.myPenDown.
Referenced by turtle.draw.TransitionFactory.createForwardTransition(), and turtle.SerialisableTurtle.SerialisableTurtle().
double turtle.draw.Pen.getWidth ()
Definition at line 58 of file Pen.java.
References turtle.draw.Pen.myWidth.
Referenced by turtle.draw.PenTransition.formatLine().
void turtle.draw.Pen.setColor (Color color)
Definition at line 46 of file Pen.java.
void turtle.draw.Pen.setDash (List< Double > dash)
Definition at line 66 of file Pen.java.
void turtle.draw.Pen.setWidth (double width)
Definition at line 50 of file Pen.java.
void turtle.draw.Pen.update (boolean penDown)
Definition at line 93 of file Pen.java.
Referenced by turtle.Turtle.updateVisualState().
void turtle.draw.Pen.update (PenChange penChange)
Definition at line 97 of file Pen.java.
References transitionstate.TransitionState.PenChange.CHANGE_DOWN, and transitionstate.TransitionState.PenChange.CHANGE_UP.
Member Data Documentation
Color turtle.draw.Pen.myColor private
Definition at line 24 of file Pen.java.
Referenced by turtle.draw.Pen.getColor().
List<Double> turtle.draw.Pen.myDash private
Definition at line 31 of file Pen.java.
Referenced by turtle.draw.Pen.getDash().
List<Line> turtle.draw.Pen.myDrawnLines private
Definition at line 30 of file Pen.java.
Referenced by turtle.draw.Pen.getDrawnLines().
Group turtle.draw.Pen.myGrid private
Definition at line 26 of file Pen.java.
boolean turtle.draw.Pen.myPenDown private
Definition at line 27 of file Pen.java.
Referenced by turtle.draw.Pen.getPenDown().
Node turtle.draw.Pen.myTurtleNode private
Definition at line 28 of file Pen.java.
double turtle.draw.Pen.myWidth private
Definition at line 25 of file Pen.java.
Referenced by turtle.draw.Pen.getWidth().
Color turtle.draw.Pen.ourDefaultColor = Color.BLACK static private
Definition at line 22 of file Pen.java.
Referenced by turtle.draw.Pen.Pen().
double turtle.draw.Pen.ourDefaultWidth = 5 static private
Definition at line 21 of file Pen.java.
Referenced by turtle.draw.Pen.Pen().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team04/repository/src/turtle/draw/Pen.java